table vwChargeMasterExtended
	lineageTag: 312f9442-ee49-46f2-8192-231de9b6e256

	column ChargeID
		dataType: int64
		formatString: 0
		lineageTag: b0c79ae4-34ba-4c5c-9a82-a09120a21fe7
		summarizeBy: none
		sourceColumn: ChargeID

		annotation SummarizationSetBy = User

	column EncounterID
		dataType: int64
		formatString: 0
		lineageTag: a934e4ba-9c9d-468a-9105-a99944f8ac5d
		summarizeBy: count
		sourceColumn: EncounterID

		annotation SummarizationSetBy = Automatic

	column PatientID
		dataType: int64
		formatString: 0
		lineageTag: 0a1e5af7-2c59-49cf-a827-fdb156fce371
		summarizeBy: none
		sourceColumn: PatientID

		annotation SummarizationSetBy = User

	column FacilityID
		dataType: int64
		formatString: 0
		lineageTag: 95f1d634-2073-4335-a9ee-3bd756fd124e
		summarizeBy: none
		sourceColumn: FacilityID

		annotation SummarizationSetBy = User

	column ProviderID
		dataType: int64
		formatString: 0
		lineageTag: 7a28260e-1229-40dc-9176-dc069f9554bd
		summarizeBy: none
		sourceColumn: ProviderID

		annotation SummarizationSetBy = User

	column PostingDate
		dataType: dateTime
		formatString: mm/dd/yyyy
		lineageTag: 734d927b-ef36-4e16-8d3e-10fbdb659195
		summarizeBy: none
		sourceColumn: PostingDate

		variation Variation
			isDefault
			relationship: 00ae0f6c-29df-4514-aa55-835a19fdd13e
			defaultHierarchy: LocalDateTable_aefebb1c-69ba-41b7-9d7d-3c6efe878dcc.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column VisitType
		dataType: string
		lineageTag: 4cd82246-3553-4579-bb35-294af8835a73
		summarizeBy: none
		sourceColumn: VisitType

		annotation SummarizationSetBy = Automatic

	column Charges
		dataType: double
		lineageTag: f04b1572-80ef-4595-b24f-a4e1d0b3e80a
		summarizeBy: none
		sourceColumn: Charges

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ExpectedAmount
		dataType: decimal
		lineageTag: 659672ba-7e51-4656-ace2-ed9928dd26c7
		summarizeBy: none
		sourceColumn: ExpectedAmount

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ProviderCategoryID
		dataType: int64
		formatString: 0
		lineageTag: 1615c5d7-e78b-417f-8334-4a3c02216c60
		summarizeBy: none
		sourceColumn: ProviderCategoryID

		annotation SummarizationSetBy = User

	column ClaimDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5478fd48-7bc2-4b13-bca3-dbe5a635be5b
		summarizeBy: none
		sourceColumn: ClaimDate

		variation Variation
			isDefault
			relationship: d288ac87-9756-4bf7-9598-a152d1060fac
			defaultHierarchy: LocalDateTable_5f4144c6-8273-4a47-bd15-c0f9ceae8d6e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column EncounterDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8e94fa10-e65b-4b39-b37d-fa94d583e91b
		summarizeBy: none
		sourceColumn: EncounterDate

		variation Variation
			isDefault
			relationship: 2d8d7e73-2d3f-4e6c-9eb8-1c51f85492f8
			defaultHierarchy: LocalDateTable_f94fee28-68be-4909-909c-deed7f43c4e5.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column OldExpectedAmount
		dataType: double
		lineageTag: 55f352a3-3bd7-4436-aeac-52e51ef1dce1
		summarizeBy: sum
		sourceColumn: OldExpectedAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PayerName
		dataType: string
		lineageTag: 71cc5ab4-b7a1-4a6f-93d1-10083b82d3ed
		summarizeBy: none
		sourceColumn: PayerName

		annotation SummarizationSetBy = Automatic

	partition vwChargeMasterExtended-ccf53f35-eb69-4ccc-8c62-c7ecc7799a92 = m
		mode: import
		queryGroup: FACT\RCM
		source =
				let
				    Source = Sql.Database("azr-cbh-use1-sql-server01.database.windows.net", "CollectiveBH"),
				    dbo_vwChargeMasterExtended = Source{[Schema="dbo",Item="vwChargeMasterExtended"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(dbo_vwChargeMasterExtended,{{"ProviderCategoryID", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Exception

