table vwPanelAge
	lineageTag: 165a5dd2-c64d-413e-922c-c9a3556260d5

	column ResourceId
		dataType: int64
		formatString: 0
		lineageTag: 9b044c64-4af8-46e9-8007-9c7a06dc3a64
		summarizeBy: none
		sourceColumn: ResourceId

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: 04ad3786-a9ac-416c-9beb-4a85e8c4c269
		summarizeBy: none
		sourceColumn: LastName

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		lineageTag: f186b59c-80e2-4f58-849f-c2183b699c97
		summarizeBy: none
		sourceColumn: FirstName

		annotation SummarizationSetBy = Automatic

	column RangeName
		dataType: string
		lineageTag: f06fcc8c-b332-4e15-bee8-1b5209ae5454
		summarizeBy: none
		sourceColumn: RangeName
		sortByColumn: 'Sort Col'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column TotalRangeAge
		dataType: int64
		formatString: 0
		lineageTag: 749cc668-a86c-4433-a677-6e1c3d63e0f3
		summarizeBy: sum
		sourceColumn: TotalRangeAge

		annotation SummarizationSetBy = Automatic

	column ActiveRangeAge
		dataType: int64
		formatString: 0
		lineageTag: 2fb6d341-5de3-4ac4-8e64-9f6d22c09c5b
		summarizeBy: sum
		sourceColumn: ActiveRangeAge

		annotation SummarizationSetBy = Automatic

	column 'Sort Col'
		dataType: int64
		formatString: 0
		lineageTag: 977e11b4-d324-4682-aabe-73dbce09ee03
		summarizeBy: sum
		sourceColumn: Sort Col

		annotation SummarizationSetBy = Automatic

	partition vwPanelAge = m
		mode: import
		queryGroup: FACT\Panel
		source =
				let
				    Source = Source,
				    #"Filtered Rows" = Table.SelectRows(Source, each Text.Contains([Name], "Panel") and Text.Contains([Name], "Combined")),
				    dbo_vwSumClinicianPanelAge = #"Filtered Rows"{[Schema="dbo",Item="vwSumClinicianPanelAgeCombined"]}[Data],
				    #"Added Conditional Column" = Table.AddColumn(dbo_vwSumClinicianPanelAge, "Sort Col", each if [RangeName] = "01-17 yrs" then 10 else if [RangeName] = "18-25 yrs" then 20 else if [RangeName] = "26-30 yrs" then 30 else if [RangeName] = "31-35 yrs" then 40 else if [RangeName] = "36-40 yrs" then 50 else if [RangeName] = "41-45 yrs" then 60 else if [RangeName] = "46-50 yrs" then 70 else if [RangeName] = "51-55 yrs" then 80 else if [RangeName] = "56-60 yrs" then 90 else if [RangeName] = ">60 yrs" then 100 else null, Int64.Type),
				    #"Replaced Value" = Table.ReplaceValue(#"Added Conditional Column","(","",Replacer.ReplaceText,{"RangeName"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",")","",Replacer.ReplaceText,{"RangeName"})
				in
				    #"Replaced Value1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

