table vwProviderUtilization
	lineageTag: d8abfe3e-402c-450e-bc7d-a294936131ff

	column MonthDate
		dataType: dateTime
		formatString: mm/dd/yyyy
		lineageTag: c67ee837-0c6a-4ced-a36c-45214b66ca83
		summarizeBy: none
		sourceColumn: MonthDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Clinician
		dataType: string
		lineageTag: c5b8536f-ec9d-475e-ad7f-e040421ee7fd
		summarizeBy: none
		sourceColumn: Clinician

		annotation SummarizationSetBy = Automatic

	column Actual
		dataType: int64
		formatString: 0
		lineageTag: 94bbb0ef-05fb-4ddf-bc64-fc7d44c924a2
		summarizeBy: sum
		sourceColumn: Actual

		annotation SummarizationSetBy = Automatic

	column FollowUp
		dataType: int64
		formatString: 0
		lineageTag: 8508e626-a89d-405e-8bcd-40d3a19a8c95
		summarizeBy: sum
		sourceColumn: FollowUp

		annotation SummarizationSetBy = Automatic

	column PTO
		dataType: int64
		formatString: 0
		lineageTag: a01ed174-4e37-4381-afea-ddb26cf8c440
		summarizeBy: sum
		sourceColumn: PTO

		annotation SummarizationSetBy = Automatic

	column Worked
		dataType: int64
		formatString: 0
		lineageTag: 8284e425-9f06-42a0-9965-f2223073fe55
		summarizeBy: sum
		sourceColumn: Worked

		annotation SummarizationSetBy = Automatic

	column Goal
		dataType: int64
		lineageTag: 3baf4fb9-ae77-4403-a74c-4dc93cf55407
		summarizeBy: sum
		sourceColumn: Goal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FollowUp60
		dataType: int64
		formatString: 0
		lineageTag: 98b7b648-0984-478f-ba3b-0f7acd2097bd
		summarizeBy: sum
		sourceColumn: FollowUp60

		annotation SummarizationSetBy = Automatic

	column ResourceId
		dataType: int64
		formatString: 0
		lineageTag: b6b5534a-9163-4bce-8bf8-b6543c3e05c5
		summarizeBy: count
		sourceColumn: ResourceId

		annotation SummarizationSetBy = Automatic

	column PreferredFacility
		dataType: string
		lineageTag: 1cb02321-4a24-4989-901f-30d68f1bf375
		summarizeBy: none
		sourceColumn: PreferredFacility

		annotation SummarizationSetBy = Automatic

	column Market
		dataType: string
		lineageTag: 5a56a285-96b7-4807-86b0-db9dc34c8f36
		summarizeBy: none
		sourceColumn: Market

		annotation SummarizationSetBy = Automatic

	column ProviderCategory
		dataType: string
		lineageTag: fa758bba-deb7-441b-8c10-bfddecd0bf94
		summarizeBy: none
		sourceColumn: ProviderCategory

		annotation SummarizationSetBy = Automatic

	column MonHours
		dataType: int64
		formatString: 0
		lineageTag: e4f87273-0b47-489d-9fb1-9fc910afa95d
		summarizeBy: sum
		sourceColumn: MonHours

		annotation SummarizationSetBy = Automatic

	column TueHours
		dataType: int64
		formatString: 0
		lineageTag: c2efda80-126f-44af-a6e3-3833f59a173c
		summarizeBy: sum
		sourceColumn: TueHours

		annotation SummarizationSetBy = Automatic

	column WedHours
		dataType: int64
		formatString: 0
		lineageTag: bd514fcb-d9d0-4076-8747-d2c9d73dc602
		summarizeBy: sum
		sourceColumn: WedHours

		annotation SummarizationSetBy = Automatic

	column ThuHours
		dataType: int64
		formatString: 0
		lineageTag: 603beeea-6f92-4c24-b9fa-102e2842dbbc
		summarizeBy: sum
		sourceColumn: ThuHours

		annotation SummarizationSetBy = Automatic

	column FriHours
		dataType: int64
		formatString: 0
		lineageTag: 42886689-0361-4418-918d-77b94842e6bd
		summarizeBy: sum
		sourceColumn: FriHours

		annotation SummarizationSetBy = Automatic

	column WeeklyGoal
		dataType: int64
		formatString: 0
		lineageTag: 5e50ba71-346b-4eb2-ae75-b88e59dbb210
		summarizeBy: sum
		sourceColumn: WeeklyGoal

		annotation SummarizationSetBy = Automatic

	column WorkDays
		dataType: int64
		formatString: 0
		lineageTag: fe76fcc5-182a-4349-8d9b-2217646b3a9f
		summarizeBy: sum
		sourceColumn: WorkDays

		annotation SummarizationSetBy = Automatic

	column 'Clinician Schedule' = ```
			vwProviderUtilization[Clinician] & " - ( " 
			    & vwProviderUtilization[MonHours] & " | " 
			    & vwProviderUtilization[TueHours] & " | " 
			    & vwProviderUtilization[WedHours] & " | " 
			    & vwProviderUtilization[ThuHours] & " | " 
			    & vwProviderUtilization[FriHours] & " )"
			```
		lineageTag: ee0fce83-d211-4e5b-86a6-4d582592e390
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column AddOn
		dataType: int64
		formatString: 0
		lineageTag: 83cd677d-0e60-42c6-9a7c-dab636c4611e
		summarizeBy: sum
		sourceColumn: AddOn

		annotation SummarizationSetBy = Automatic

	partition vwProviderUtilization = m
		mode: import
		queryGroup: Settings
		source =
				let
				    Source = Sql.Database(ServerName, DBName),
				    dbo_vwProviderUtilization = Source{[Schema="dbo",Item="vwProviderUtilization"]}[Data],
				    #"Merged Columns" = Table.CombineColumns(dbo_vwProviderUtilization,{"LastName", "FirstName"},Combiner.CombineTextByDelimiter(", ", QuoteStyle.None),"Clinician")
				in
				    #"Merged Columns"

	annotation PBI_ResultType = Exception

