table cfgDailyBudget
	lineageTag: 4041d783-b673-4991-a931-b1c6b94df8fc

	column Market
		dataType: string
		lineageTag: 34775e9b-184b-4032-8731-fe7f7ae55eb4
		summarizeBy: none
		sourceColumn: Market

		annotation SummarizationSetBy = Automatic

	column FacilityId
		dataType: int64
		formatString: 0
		lineageTag: 04953faa-e804-4211-b14e-6e0da6551139
		summarizeBy: none
		sourceColumn: FacilityId

		annotation SummarizationSetBy = User

	column FacilityName
		dataType: string
		lineageTag: 41382078-c55e-48dc-af37-27f7b49c9f94
		summarizeBy: none
		sourceColumn: FacilityName

		annotation SummarizationSetBy = Automatic

	column ProviderCategory
		dataType: string
		lineageTag: 306fda31-809f-48ed-ba8f-1f1776403e9d
		summarizeBy: none
		sourceColumn: ProviderCategory

		annotation SummarizationSetBy = Automatic

	column BudgetType
		dataType: string
		lineageTag: ea51d192-df7a-44ac-8f9c-a8b2e7cf66d6
		summarizeBy: none
		sourceColumn: BudgetType

		annotation SummarizationSetBy = Automatic

	column VisitType
		dataType: string
		lineageTag: da45682b-18e9-4462-bd4a-3577b6ecaa24
		summarizeBy: none
		sourceColumn: VisitType

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: string
		lineageTag: 7fe2f47d-8180-42e5-9ab6-6faf99dbb973
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: e74aeb9a-006f-4ef8-a100-81e601bd5e6f
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthDate
		dataType: dateTime
		formatString: mm/dd/yyyy
		lineageTag: 142810e6-3d03-4b82-92d9-1dc54177c2ec
		summarizeBy: none
		sourceColumn: MonthDate

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column DayRevenue
		dataType: int64
		lineageTag: 4caf0295-47e9-47e8-8f14-30ef8533e199
		summarizeBy: none
		sourceColumn: DayRevenue

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MtdRevenue
		dataType: int64
		lineageTag: 9dc4b4e1-f970-46ce-b3da-c80535dc4b0b
		summarizeBy: none
		sourceColumn: MtdRevenue

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DayVisTotal
		dataType: int64
		lineageTag: 46e30cf7-e1a9-498d-aa45-ee185b7c7b2f
		summarizeBy: none
		sourceColumn: DayVisTotal

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MtdVisTotal
		dataType: int64
		lineageTag: 478369f4-2ac6-4ae5-baca-03b0d8bb22ed
		summarizeBy: none
		sourceColumn: MtdVisTotal

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DayVisComp
		dataType: int64
		lineageTag: f297cfdd-7c60-4faf-8065-8a87e85bcde4
		summarizeBy: none
		sourceColumn: DayVisComp

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MtdVisComp
		dataType: int64
		lineageTag: 2f2fd388-ba18-457a-962a-eb6c9efbd503
		summarizeBy: none
		sourceColumn: MtdVisComp

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DayVisNoShow
		dataType: int64
		lineageTag: 060a7751-a646-4560-9c27-57a559ea73ad
		summarizeBy: none
		sourceColumn: DayVisNoShow

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MtdVisNoShow
		dataType: int64
		lineageTag: 1d45def3-cd36-4fee-a454-db79f2c79c63
		summarizeBy: none
		sourceColumn: MtdVisNoShow

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition cfgDailyBudget-6cc1761e-6b0c-4f33-a72e-5c7726a84993 = m
		mode: import
		queryGroup: CFGs
		source =
				let
				    Source = Sql.Database(ServerName, DBName),
				    dbo_cfgDailyBudget = Source{[Schema="dbo",Item="cfgDailyBudget"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(dbo_cfgDailyBudget,{{"DayVisTotal", Int64.Type}, {"MtdVisTotal", Int64.Type}, {"DayVisComp", Int64.Type}, {"MtdVisComp", Int64.Type}, {"DayVisNoShow", Int64.Type}, {"MtdVisNoShow", Int64.Type}, {"DayRevenue", Int64.Type}, {"MtdRevenue", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Exception

