table 'Measures - model'
	lineageTag: 4dcc1e12-722a-4f0a-a165-840b57221455

	measure 'Appts - Goal' = ```
			
			SUM(vwResourceDetails[WkAptGoals])
			
			```
		formatString: #,0
		displayFolder: _Operations\_Utilization
		lineageTag: 8c1bfb11-df34-4cf4-bd51-6fab874ffc2f

		changedProperty = FormatString

	measure 'DayVisitTotal - DailyBudget - Therapy - Intake' =
			
			CALCULATE(
			    SUM(cfgDailyBudget[DayVisTotal]),
			    cfgDailyBudget[BudgetType] = "V",
			    cfgDailyBudget[ProviderCategory] = "Therapy",
			    --cfgDailyBudget[FacilityName] = "All Locations",
			    cfgDailyBudget[VisitType] = "Intakes",
			    cfgDailyBudget[Market] = "CO")
		formatString: #,0
		isHidden
		displayFolder: _PnL
		lineageTag: fa8e4521-8bce-42a3-95c2-411645ccc999

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'DayRevenueTotal - DailyBudget - Total' =
			
			[DayRevenueTotal - DailyBudget - Psy] +
			[DayRevenueTotal - DailyBudget - Therapy]
		formatString: #,0
		displayFolder: _PnL\Budget Revenue
		lineageTag: e8a4af72-1441-4220-9afe-420cf1d484f1

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'CumulativeRevenueTotal - DailyBudget' =
			
			CALCULATE(
			    SUM(cfgDailyBudget[MtdRevenue]),
			    cfgDailyBudget[BudgetType] = "R",
			    cfgDailyBudget[ProviderCategory] = "Total"
			)
		formatString: #,0
		displayFolder: _PnL\Cumulative Revenue
		lineageTag: 7e3010c9-a064-450e-99ea-52fb39c801de

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'DayVisitTotal - DailyBudget - Therapy - FU' =
			
			CALCULATE (
			    SUM ( cfgDailyBudget[DayVisTotal] ),
			    cfgDailyBudget[BudgetType] = "V",
			    cfgDailyBudget[ProviderCategory] = "Therapy",
			    --cfgDailyBudget[FacilityName] = "All Locations",
			    cfgDailyBudget[VisitType] = "Follow-Ups",
			    cfgDailyBudget[Market] = "CO"
			)
		formatString: #,0
		isHidden
		displayFolder: _PnL
		lineageTag: 991568b8-a5ba-4707-9fd9-334e8256aaf0

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'DayVisitTotal - DailyBudget - Total - Therapy' = ```
			[DayVisitTotal - DailyBudget - Therapy - Intake] 
			+ 
			[DayVisitTotal - DailyBudget - Therapy - FU]
			```
		formatString: #,0
		isHidden
		displayFolder: _PnL
		lineageTag: f01a604b-76bb-4d0b-8c4f-1ed84fb37e35

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '# Checkout Visits - Therapy' = ```
			
			[# Completed - Intake - Th] + 
			[# Completed - FU Patient - Th]
			```
		formatString: #,0
		displayFolder: _PnL\Completed Visits
		lineageTag: 7db4a1e3-13ec-4670-9c31-6568e281814d

		changedProperty = FormatString

	measure '# Checkout Visits - Psychiatric' = ```
			
			[# Completed - Intake - Psy] + 
			[# Completed - FU Patient - Psy]
			```
		formatString: #,0
		displayFolder: _PnL\Completed Visits
		lineageTag: 3ee749f5-0efe-4f4f-9804-bb3c2c34eec7

		changedProperty = FormatString

	measure 'DayVisitTotal - DailyBudget - Psy - FU' =
			
			CALCULATE(
			    SUM(cfgDailyBudget[DayVisTotal]),
			    cfgDailyBudget[BudgetType] = "V",
			    cfgDailyBudget[ProviderCategory] = "Psychiatry",
			    --cfgDailyBudget[FacilityName] = "All Locations",
			    cfgDailyBudget[VisitType] = "Follow-Ups",
			    cfgDailyBudget[Market] = "CO")
		formatString: #,0
		isHidden
		displayFolder: _PnL
		lineageTag: 16d7e211-3797-464e-9214-fe48ffa6212f

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'DayVisitTotal - DailyBudget - Psy - Intake' =
			
			CALCULATE(
			    SUM(cfgDailyBudget[DayVisTotal]),
			    cfgDailyBudget[BudgetType] = "V",
			    cfgDailyBudget[ProviderCategory] = "Psychiatry",
			    --cfgDailyBudget[FacilityName] = "All Locations",
			    cfgDailyBudget[VisitType] = "Intakes",
			    cfgDailyBudget[Market] = "CO")
		formatString: #,0
		isHidden
		displayFolder: _PnL
		lineageTag: 9d2abfde-a529-46dc-91e8-8f3746f4ee0b

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'DayVisitTotal - DailyBudget - Total - Psychiatric' = ```
			[DayVisitTotal - DailyBudget - Psy - Intake] 
			+ 
			[DayVisitTotal - DailyBudget - Psy - FU]
			```
		formatString: #,0
		isHidden
		displayFolder: _PnL
		lineageTag: 9731ea77-a20d-4df4-a459-a63e8fe6ae56

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'DayRevenueTotal - DailyBudget - Therapy' =
			
			CALCULATE(
			    SUM(cfgDailyBudget[DayRevenue]),
			    cfgDailyBudget[BudgetType] = "R",
			    cfgDailyBudget[ProviderCategory] = "Therapy"
			    )
		formatString: #,0
		displayFolder: _PnL\Budget Revenue
		lineageTag: b161287d-8c57-4ac6-a66d-023e5004d41f

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'DayRevenueTotal - DailyBudget - Psy' =
			
			CALCULATE(
			    SUM(cfgDailyBudget[DayRevenue]),
			    cfgDailyBudget[BudgetType] = "R",
			    cfgDailyBudget[ProviderCategory] = "Psychiatry"
			    )
		formatString: #,0
		displayFolder: _PnL\Budget Revenue
		lineageTag: 15ab07e4-9468-438d-b090-61df40e717a8

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'DayVisComp - DailyBudget - Psy - FU' =
			
			CALCULATE (
			    SUM ( cfgDailyBudget[DayVisComp] ),
			    cfgDailyBudget[BudgetType] = "V",
			    cfgDailyBudget[ProviderCategory] = "Psychiatry",
			    cfgDailyBudget[VisitType] = "Follow-Ups"
			)
		formatString: #,0
		displayFolder: _PnL\Budget Visits
		lineageTag: 09a8804a-27da-4737-9daa-d475f99d8fd0

	measure 'DayVisComp - DailyBudget - Psy - Intake' =
			
			CALCULATE (
			    SUM ( cfgDailyBudget[DayVisComp] ),
			    cfgDailyBudget[BudgetType] = "V",
			    cfgDailyBudget[ProviderCategory] = "Psychiatry",
			    cfgDailyBudget[VisitType] = "Intakes"
			)
		formatString: #,0
		displayFolder: _PnL\Budget Visits
		lineageTag: 6ac39c1a-1308-4fee-8e6c-1849d4ae3542

	measure 'DayVisComp - DailyBudget - Therapy - FU' =
			
			CALCULATE (
			    SUM ( cfgDailyBudget[DayVisComp] ),
			    cfgDailyBudget[BudgetType] = "V",
			    cfgDailyBudget[ProviderCategory] = "Therapy",
			    cfgDailyBudget[VisitType] = "Follow-Ups"
			)
		formatString: #,0
		displayFolder: _PnL\Budget Visits
		lineageTag: 704c8fc7-1eba-45c1-8eaa-a73203d4e020

	measure 'DayVisComp - DailyBudget - Therapy - Intake' =
			
			CALCULATE (
			    SUM ( cfgDailyBudget[DayVisComp] ),
			    cfgDailyBudget[BudgetType] = "V",
			    cfgDailyBudget[ProviderCategory] = "Therapy",
			    cfgDailyBudget[VisitType] = "Intakes"
			)
		formatString: #,0
		displayFolder: _PnL\Budget Visits
		lineageTag: 9f381855-c2e8-443f-a91d-19a30b9064c9

	measure 'DayVisComp - DailyBudget - Total - Psy' = ```
			
			[DayVisComp - DailyBudget - Psy - Intake] 
			+ 
			[DayVisComp - DailyBudget - Psy - FU]
			```
		formatString: #,0
		displayFolder: _PnL\Budget Visits
		lineageTag: 2b699367-3885-4481-8831-eeb1cd02d373

	measure 'DayVisComp - DailyBudget - Total - Therapy' = ```
			
			[DayVisComp - DailyBudget - Therapy - Intake] 
			+ 
			[DayVisComp - DailyBudget - Therapy - FU]
			```
		formatString: #,0
		displayFolder: _PnL\Budget Visits
		lineageTag: 11b9c3e9-b868-47f5-b562-4f52fbc1bcb5

	measure 'Cumulative Visits - Therapy - FU-1' =
			
			CALCULATE (
			    [# Completed - FU Patient - Th],
			    FILTER ( ALLSELECTED ( dimDate ), dimDate[Date] <= MAX ( dimDate[Date] ) )
			)
		formatString: 0
		isHidden
		displayFolder: _PnL\Cumulatives - old
		lineageTag: d9053d30-143d-48dc-8926-b95cd54163d0

	measure 'Cumulative Visits - Therapy - Intake-1' =
			
			CALCULATE (
			    [# Completed - Intake - Th],
			    FILTER ( ALLSELECTED ( dimDate ), dimDate[Date] <= MAX ( dimDate[Date] ) )
			)
		isHidden
		displayFolder: _PnL\Cumulatives - old
		lineageTag: e05693e1-51ee-4535-ad6c-bbd66d080151

	measure 'Cumulative Visits - Psy - FU - 1' =
			
			CALCULATE (
			    [# Completed - FU Patient - Psy],
			    FILTER ( ALLSELECTED ( dimDate ), dimDate[Date] <= MAX ( dimDate[Date] ) )
			)
		formatString: 0
		isHidden
		displayFolder: _PnL\Cumulatives - old
		lineageTag: e940dd54-369c-405d-8f74-f1d476b81a4c

	measure 'Cumulative Visits - Psy - Intake -1' = ```
			
			CALCULATE (
			    [# Completed - Intake - Psy],
			    FILTER ( 
			        ALLSELECTED ( dimDate ), 
			        dimDate[Date] <= MAX ( dimDate[Date] ) 
			    )
			)
			```
		formatString: 0
		isHidden
		displayFolder: _PnL\Cumulatives - old
		lineageTag: d12dfea5-233a-4ce7-a340-bf37f51dcaef

	measure 'Cumulative Visits - Total - Psy-1' =
			
			[Cumulative Visits - Psy - FU - 1]
			+
			[Cumulative Visits - Psy - Intake -1]
		isHidden
		displayFolder: _PnL\Cumulatives - old
		lineageTag: 2cf6d7c7-5da4-4223-a506-74078261d00f

	measure 'Cumulative Visits - Total - Therapy-1' =
			[Cumulative Visits - Therapy - FU-1]
			+
			[Cumulative Visits - Therapy - Intake-1]
		isHidden
		displayFolder: _PnL\Cumulatives - old
		lineageTag: 69a9eef1-b2ce-4f81-aef5-58eb481ebf9e

	measure 'Cumulative Budget - Psy - FU' =
			CALCULATE (
			    SUM ( cfgDailyBudget[MtdVisComp] ),
			    cfgDailyBudget[BudgetType] = "V",
			    cfgDailyBudget[ProviderCategory] = "Psychiatry",
			    cfgDailyBudget[VisitType] = "Follow-Ups",
			    cfgDailyBudget[Market] = "CO"
			)
		isHidden
		displayFolder: _PnL\Cumulatives - old
		lineageTag: 5c882fb8-d813-4eb4-8ff9-a5165319518b

	measure 'Cumulative Budget - Psy - Intake' =
			
			CALCULATE (
			    SUM ( cfgDailyBudget[MtdVisComp] ),
			    cfgDailyBudget[BudgetType] = "V",
			    cfgDailyBudget[ProviderCategory] = "Psychiatry",
			    cfgDailyBudget[VisitType] = "Intakes",
			    cfgDailyBudget[Market] = "CO"
			)
		isHidden
		displayFolder: _PnL\Cumulatives - old
		lineageTag: ef110036-c3b9-4c62-9e31-f44a6a6710ad

	measure 'Cumulative Budget - Therapy - FU' =
			CALCULATE (
			    SUM ( cfgDailyBudget[MtdVisComp] ),
			    cfgDailyBudget[BudgetType] = "V",
			    cfgDailyBudget[ProviderCategory] = "Therapy",
			    cfgDailyBudget[VisitType] = "Follow-Ups",
			    cfgDailyBudget[Market] = "CO"
			)
		formatString: 0
		isHidden
		displayFolder: _PnL\Cumulatives - old
		lineageTag: 99bd368b-7aaf-4788-b4a4-b8caec637dc0

	measure 'Cumulative Budget - Therapy - Intake' =
			CALCULATE (
			    SUM ( cfgDailyBudget[MtdVisComp] ),
			    cfgDailyBudget[BudgetType] = "V",
			    cfgDailyBudget[ProviderCategory] = "Therapy",
			    cfgDailyBudget[VisitType] = "Intakes",
			    cfgDailyBudget[Market] = "CO"
			)
		isHidden
		displayFolder: _PnL\Cumulatives - old
		lineageTag: c74980e9-2335-4763-a4f5-c5cdf842ed8c

	measure 'Cumulative Budget - Total - Psy' =
			[Cumulative Budget - Psy - FU]
			+
			[Cumulative Budget - Psy - Intake]
		isHidden
		displayFolder: _PnL\Cumulatives - old
		lineageTag: 2ce3a202-0628-4a8b-98b3-ae93a178fa77

	measure 'Cumulative Budget - Total - Therapy' =
			[Cumulative Budget - Therapy - FU]
			+
			[Cumulative Budget - Therapy - Intake]
		isHidden
		displayFolder: _PnL\Cumulatives - old
		lineageTag: 73f41cf1-28fc-4ab4-b541-6a601a918a59

	measure 'Cumulative Visits - Psy - FU' = ```
			
			CALCULATE (
			    [# Completed - FU Patient - Psy],
			    FILTER ( 
			        ALLSELECTED ( '2_Date_Expander' ), 
			        '2_Date_Expander'[Date] <= MAX ( '2_Date_Expander'[Date] ) 
			    )
			)
			```
		formatString: #,0
		displayFolder: _PnL\Cumulative Visits
		lineageTag: af82909d-7441-4e76-9665-a6a72298dbc0

	measure 'Cumulative Visits - Psy - Intake' = ```
			
			CALCULATE (
			    [# Completed - Intake - Psy],
			    FILTER ( 
			        ALLSELECTED ( '2_Date_Expander' ), 
			        '2_Date_Expander'[Date] <= MAX ( '2_Date_Expander'[Date] ) 
			    )
			)
			```
		formatString: #,0
		displayFolder: _PnL\Cumulative Visits
		lineageTag: 7a754710-3ee9-4c66-be2a-fc5abf95d372

	measure 'Cumulative Visits - Therapy - FU' =
			
			CALCULATE (
			    [# Completed - FU Patient - Th],
			    FILTER (
			        ALLSELECTED ( '2_Date_Expander' ),
			        '2_Date_Expander'[Date] <= MAX ( '2_Date_Expander'[Date] )
			    )
			)
		formatString: #,0
		displayFolder: _PnL\Cumulative Visits
		lineageTag: 1c7c2b84-cb8b-4058-b605-4f017afe9521

	measure 'Cumulative Visits - Therapy - Intake' =
			
			CALCULATE (
			    [# Completed - Intake - Th],
			    FILTER (
			        ALLSELECTED ( '2_Date_Expander' ),
			        '2_Date_Expander'[Date] <= MAX ( '2_Date_Expander'[Date] )
			    )
			)
		formatString: #,0
		displayFolder: _PnL\Cumulative Visits
		lineageTag: 4eb0317c-bd0a-440e-8c01-f5265a08fc70

	measure 'Cumulative Visits - Total - Psy' =
			
			[Cumulative Visits - Psy - FU]
			+
			[Cumulative Visits - Psy - Intake]
		formatString: #,0
		displayFolder: _PnL\Cumulative Visits
		lineageTag: a7d98968-dd98-457a-8e13-c18840b8e68a

	measure 'Cumulative Visits - Total - Therapy' =
			[Cumulative Visits - Therapy - FU]
			+
			[Cumulative Visits - Therapy - Intake]
		formatString: #,0
		displayFolder: _PnL\Cumulative Visits
		lineageTag: 6e31a983-e319-4b5c-a7e3-fc9bda9f2917

	measure 'Budget Cumulative - Psy - FU' =
			CALCULATE (
			    [DayVisComp - DailyBudget - Psy - FU],
			    FILTER (
			        ALLSELECTED ( '2_Date_Expander' ),
			        '2_Date_Expander'[Date] <= MAX ( '2_Date_Expander'[Date] )
			    )
			)
		formatString: #,0
		displayFolder: _PnL\Cumulative Budget
		lineageTag: 339b37ce-ae40-4d13-b216-46dfea130c35

	measure 'Budget Cumulative - Psy - Intake' =
			CALCULATE (
			    [DayVisComp - DailyBudget - Psy - Intake],
			    FILTER (
			        ALLSELECTED ( '2_Date_Expander' ),
			        '2_Date_Expander'[Date] <= MAX ( '2_Date_Expander'[Date] )
			    )
			)
		formatString: #,0
		displayFolder: _PnL\Cumulative Budget
		lineageTag: 46b28868-bff0-49f5-a47e-dba601277eb7

	measure 'Budget Cumulative - Therapy - FU' =
			CALCULATE (
			    [DayVisComp - DailyBudget - Therapy - FU],
			    FILTER (
			        ALLSELECTED ( '2_Date_Expander' ),
			        '2_Date_Expander'[Date] <= MAX ( '2_Date_Expander'[Date] )
			    )
			)
		formatString: #,0
		displayFolder: _PnL\Cumulative Budget
		lineageTag: 2ca50f41-8c8d-41c9-b6a5-ac1b2ba4f6b9

	measure 'Budget Cumulative - Therapy - Intake' =
			CALCULATE (
			    [DayVisComp - DailyBudget - Therapy - Intake],
			    FILTER (
			        ALLSELECTED ( '2_Date_Expander' ),
			        '2_Date_Expander'[Date] <= MAX ( '2_Date_Expander'[Date] )
			    )
			)
		formatString: #,0
		displayFolder: _PnL\Cumulative Budget
		lineageTag: 630f21a8-d663-4227-81d1-809af51e1dd6

	measure 'Budget Cumulative - Total - Psy' =
			
			[Budget Cumulative - Psy - FU]
			+
			[Budget Cumulative - Psy - Intake]
		formatString: #,0
		displayFolder: _PnL\Cumulative Budget
		lineageTag: 5f44e684-d4de-4179-96b7-82dad41b430c

	measure 'Budget Cumulative - Total - Therapy' =
			
			[Budget Cumulative - Therapy - FU]
			+
			[Budget Cumulative - Therapy - Intake]
		formatString: #,0
		displayFolder: _PnL\Cumulative Budget
		lineageTag: d9d11bfa-9144-45f3-ad30-bda8ee2503e9

	measure 'CumulativeRevenue - Visits - Psy' =
			CALCULATE (
			    [Revenue Visits - Psychiatric],
			    FILTER (
			        ALLSELECTED ( '2_Date_Expander' ),
			        '2_Date_Expander'[Date] <= MAX ( '2_Date_Expander'[Date] )
			    )
			)
		formatString: #,0
		displayFolder: _PnL\Cumulative Revenue
		lineageTag: bec8597e-b01a-4e2d-9875-70356ef5ef6e

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'CumulativeRevenue - Visits - Therapy' =
			CALCULATE (
			    [Revenue Visits - Therapy] ,
			    FILTER (
			        ALLSELECTED ( '2_Date_Expander' ),
			        '2_Date_Expander'[Date] <= MAX ( '2_Date_Expander'[Date] )
			    )
			)
		formatString: #,0
		displayFolder: _PnL\Cumulative Revenue
		lineageTag: eb894bf5-c09a-4750-8fe1-4ce0c1ba3eb4

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'CumulativeRevenue - Budget - Psy' =
			CALCULATE (
			    [DayRevenueTotal - DailyBudget - Psy],
			    FILTER (
			        ALLSELECTED ( '2_Date_Expander' ),
			        '2_Date_Expander'[Date] <= MAX ( '2_Date_Expander'[Date] )
			    )
			)
		formatString: #,0
		displayFolder: _PnL\Cumulative Revenue
		lineageTag: 7576f739-3730-4f26-9cf0-a5ac89668f64

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'CumulativeRevenue - Budget - Therapy' =
			CALCULATE (
			    [DayRevenueTotal - DailyBudget - Therapy],
			    FILTER (
			        ALLSELECTED ( '2_Date_Expander' ),
			        '2_Date_Expander'[Date] <= MAX ( '2_Date_Expander'[Date] )
			    )
			)
		formatString: #,0
		displayFolder: _PnL\Cumulative Revenue
		lineageTag: 646b6bcb-ea4e-46fa-ac3d-3e50c14a308c

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '# Checkout Visits - Total' = ```
			
			[# Checkout Visits - Psychiatric] 
			+
			[# Checkout Visits - Therapy]
			```
		formatString: #,0
		displayFolder: _PnL\Completed Visits
		lineageTag: 073827c6-f085-4730-9ee7-dfb7263e6d96

		changedProperty = FormatString

	measure 'DayVisComp - DailyBudget - Total' =
			
			[DayVisComp - DailyBudget - Total - Psy]
			+
			[DayVisComp - DailyBudget - Total - Therapy]
		formatString: #,0
		displayFolder: _PnL\Budget Visits
		lineageTag: 892fd3c7-ee6d-47db-bc69-9b96584b83d8

		changedProperty = FormatString

	measure 'Cumulative Visits - Total' =
			[Cumulative Visits - Total - Psy]
			+
			[Cumulative Visits - Total - Therapy]
		formatString: #,0
		displayFolder: _PnL\Cumulative Visits
		lineageTag: a1fc8fb4-804c-4fec-9ea5-0c2482383b82

		changedProperty = FormatString

	measure 'Budget Cumulative - Total' =
			
			[Budget Cumulative - Total - Psy]
			+
			[Budget Cumulative - Total - Therapy]
		formatString: #,0
		displayFolder: _PnL\Cumulative Budget
		lineageTag: bae149a4-d165-4b63-adbc-1cb682879e15

		changedProperty = FormatString

	measure 'CumulativeRevenue - Visits - Total' =
			[CumulativeRevenue - Visits - Psy]
			+
			[CumulativeRevenue - Visits - Therapy]
		formatString: #,0
		displayFolder: _PnL\Cumulative Revenue
		lineageTag: 613a1466-d429-4893-bc64-451d2d70558f

		changedProperty = FormatString

	measure 'CumulativeRevenue - Budget - Total' =
			
			[CumulativeRevenue - Budget - Psy]
			+
			[CumulativeRevenue - Budget - Therapy]
		formatString: #,0
		displayFolder: _PnL\Cumulative Revenue
		lineageTag: 80d049a9-a400-47f1-8f11-4316c61c0be9

		changedProperty = FormatString

	measure 'Cumulative Visits - Total - FU' = ```
			
			[Cumulative Visits - Psy - FU] + 
			[Cumulative Visits - Therapy - FU]
			```
		formatString: #,0
		displayFolder: _PnL\Cumulative Visits
		lineageTag: bc890b0e-14dd-4f34-a0f0-2f512cc7c017

		changedProperty = FormatString

	measure 'Cumulative Visits - Total - Intake' = ```
			
			[Cumulative Visits - Therapy - Intake] + 
			[Cumulative Visits - Psy - Intake]
			```
		formatString: #,0
		displayFolder: _PnL\Cumulative Visits
		lineageTag: 500e3d65-20cb-48eb-ac24-ed75d0036f8a

		changedProperty = FormatString

	measure 'Budget Cumulative - Total - FU' = ```
			
			[Budget Cumulative - Psy - FU] + 
			[Budget Cumulative - Therapy - FU]
			```
		formatString: #,0
		displayFolder: _PnL\Cumulative Budget
		lineageTag: 8684b06a-067b-4684-ab64-fa3060d2c92f

	measure 'Budget Cumulative - Total - Intake' = ```
			
			[Budget Cumulative - Psy - Intake] + 
			[Budget Cumulative - Therapy - Intake]
			```
		formatString: #,0
		displayFolder: _PnL\Cumulative Budget
		lineageTag: 91dde509-e854-40dd-9b87-ae4bd9827098

	measure '# Checkout Visits - Intake' = ```
			
			[# Completed - Intake - Psy] + 
			[# Completed - Intake - Th]
			```
		formatString: #,0
		displayFolder: _PnL\Completed Visits
		lineageTag: 2c2fddd0-9595-4e0b-aa34-89403e28645a

		changedProperty = FormatString

	measure '# Checkout Visits - FU' = ```
			
			[# Completed - FU Patient - Psy] + 
			[# Completed - FU Patient - Th]
			```
		formatString: #,0
		displayFolder: _PnL\Completed Visits
		lineageTag: 303c6c56-09e2-4e80-9889-67c202bf664a

		changedProperty = FormatString

	measure 'DayVisComp - DailyBudget - Total - FU' = ```
			
			[DayVisComp - DailyBudget - Therapy - FU]
			+ 
			[DayVisComp - DailyBudget - Psy - FU]
			```
		formatString: #,0
		displayFolder: _PnL\Budget Visits
		lineageTag: 9a0a1ef9-af7e-4748-8fb2-e199fb0e528c

	measure 'DayVisComp - DailyBudget - Total - Intake' = ```
			
			[DayVisComp - DailyBudget - Psy - Intake] 
			+ 
			[DayVisComp - DailyBudget - Therapy - Intake]
			```
		formatString: #,0
		displayFolder: _PnL\Budget Visits
		lineageTag: 443fd67a-47e6-4404-80c0-fe8ade81b0d1

	measure 'BudgetVisits -- Test' =
			
			CALCULATE (
			    SUM ( cfgDailyBudget[DayVisComp] ),
			    FILTER( 'cfgDailyBudget', [Market] = "CO" ),
			    cfgDailyBudget[BudgetType] = "V" ,
			    NOT( cfgDailyBudget[ProviderCategory] IN { "Total" } ),
			    cfgDailyBudget[VisitType] IN { "Follow-Ups", "Intakes" }
			)
		formatString: #,0
		isHidden
		displayFolder: _PnL\Budget Visits
		lineageTag: 8ff277a6-1f27-4109-be04-d909f8cb9332

		changedProperty = FormatString

		changedProperty = IsHidden

	measure '# Leads' = ```
			
			 COUNT(
			     vwCollectiveLead[LeadStatus]
			    )
			```
		formatString: #,0
		displayFolder: _Marketing\Inquiry
		lineageTag: 75fd4764-6ac7-4535-a30f-351acb4547d1

		changedProperty = FormatString

	measure '# Converted - DLM' =
			
			calculate(
			    [# Leads - DLM],
			    vwCollectiveLead[Status] = "Converted"
			)
		formatString: #,0
		displayFolder: _Marketing\DLM
		lineageTag: 11b65e09-53f4-4764-bd99-8f72da09d753

	measure '# Leads - DLM' =
			CALCULATE(
			     COUNTROWS(vwCollectiveLead),
			     USERELATIONSHIP(vwCollectiveLead[DateLastModified], dimDate[Date]))
		formatString: #,0
		displayFolder: _Marketing\DLM
		lineageTag: 851c1fd5-8d46-4f4a-8aad-e67f56cc91a8

	measure '# Not Converted - DLM' =
			calculate(
			    [# Leads - DLM],
			    vwCollectiveLead[Status] = "Not Converted"
			)
		formatString: #,0
		displayFolder: _Marketing\DLM
		lineageTag: 9bbd9719-c0a3-4e7a-9bee-3d03e98ab61a

	measure '% Conversion - DLM' = [# Converted - DLM] / [# Leads - DLM]
		formatString: 0\ %;-0\ %;0\ %
		displayFolder: _Marketing\DLM
		lineageTag: 1f298ea2-4b22-438c-ba9a-952b50945f4f

	measure '# Converted' =
			
			calculate(
			    [# Leads],
			    vwCollectiveLead[CompletionStatus] = "Converted"
			)
		formatString: #,0
		displayFolder: _Marketing\Inquiry
		lineageTag: 1bfa074f-e5ef-48ab-bca2-66cc951352df

	measure '# Not Converted' =
			
			calculate(
			    [# Leads],
			    vwCollectiveLead[Status] = "Not Converted"
			)
		formatString: #,0
		displayFolder: _Marketing\Inquiry
		lineageTag: fa7e24b0-d7cd-40a9-9039-9d51b15a1eb1

	measure '% Conversion' = ([# Converted] + [# Completed] )/ [# Leads]
		formatString: 0\ %;-0\ %;0\ %
		displayFolder: _Marketing\Inquiry
		lineageTag: 75957a5f-e23a-4624-9f43-b3dcd4510742

	measure 'Revenue - New visits' = ```
			var _selectedMonth =
			IF (
				SELECTEDVALUE ( dimDate[Slicer Month] ) = "Current Month",
				FORMAT ( EOMONTH ( TODAY (), 0 ), "YYYY-MM-DD" ),
				FORMAT ( EOMONTH ( SELECTEDVALUE ( dimDate[Slicer Month] ), 0 ), "YYYY-MM-DD" )
			    )
			    
			RETURN 
			CALCULATE(
				SUM(cfgRevenueVisits[New Revenue Visit]),
				AND(
					DATEVALUE(_selectedMonth) > cfgRevenueVisits[FromDate] , 
					DATEVALUE(_selectedMonth) <= cfgRevenueVisits[ThruDate]
				)
			)
			```
		formatString: 0
		displayFolder: _Finance\_Complement measures
		lineageTag: 284ae49f-1f71-45f9-a5b7-4a93ea97eda1

	measure 'Revenue - Existent Visits' = ```
			
			--SUM(
			    --cfgRevenueVisits[Existent Revenue Visit])
			
			var _selectedMonth =
			IF (
			    SELECTEDVALUE ( dimDate[Slicer Month] ) = "Current Month",
			    FORMAT ( EOMONTH ( TODAY (), 0 ), "YYYY-MM-DD" ),
			    FORMAT ( EOMONTH ( SELECTEDVALUE ( dimDate[Slicer Month] ), 0 ), "YYYY-MM-DD" )
			)
			    
			RETURN 
			
			CALCULATE(
			    SUM(cfgRevenueVisits[Existent Revenue Visit]),
			    AND(
			        DATEVALUE(_selectedMonth) > cfgRevenueVisits[FromDate], 
			        DATEVALUE(_selectedMonth) <= cfgRevenueVisits[ThruDate]
			    )
			)
			```
		formatString: 0
		displayFolder: _Finance\_Complement measures
		lineageTag: 61ae3cea-b75c-468b-9511-7ea46005ce29

	measure 'Revenue Visits - Therapy' =
			
			SUM(vwDailySales[ThrFupRev])+SUM(vwDailySales[ThrIntRev])
		formatString: #,0
		displayFolder: _Finance\_Complement measures
		lineageTag: d695443e-779e-4b99-a2e8-d1d040e849bd

		changedProperty = FormatString

	measure 'Revenue Visits - Psychiatric' =
			
			SUM(vwDailySales[PsyFupRev])+SUM(vwDailySales[PsyIntRev])
		formatString: #,0
		displayFolder: _Finance\_Complement measures
		lineageTag: c2c98d38-dedc-4499-a46f-22e7b0603a4d

		changedProperty = FormatString

	measure 'Revenue - Recast Monthly For Table' = ```
			VAR CurrentMonth =
			    IF (
			        SELECTEDVALUE ( dimDate[Slicer Month] ) = "Current Month",
			        FORMAT ( EOMONTH ( TODAY (), 0 ), "YYYY-MM-DD" ),
			        FORMAT ( EOMONTH ( SELECTEDVALUE ( dimDate[Slicer Month] ), 0 ), "YYYY-MM-DD" )
			    )
			    
			RETURN
			    CALCULATE (
			        SUM ( cfgDailyBudget[MtdRevenue] ),
			        ALLEXCEPT (
			            cfgDailyBudget,
			            dimDate[Slicer Month],
			            dimMarket[Market],
			            vwFacilitiesMaster[FacilityName]
			        ),
			        cfgDailyBudget[MonthDate] = DATEVALUE ( CurrentMonth ),
			        cfgDailyBudget[BudgetType] = "R",
			        cfgDailyBudget[FacilityName] <> "All Locations",
			        cfgDailyBudget[ProviderCategory] = "Total"
			    )
			/*
			VAR CurrentMonth =
			    IF (
			        SELECTEDVALUE ( dimDate[Slicer Month] ) = "Current Month",
			        MONTH(TODAY()),
			        MONTH ( SELECTEDVALUE ( dimDate[Slicer Month] ) )
			    )
			
			VAR CurrentYear =
			    IF (
			        SELECTEDVALUE ( dimDate[Slicer Month] ) = "Current Month",
			        YEAR(TODAY()),
			        YEAR ( SELECTEDVALUE ( dimDate[Slicer Month] ) )
			    )
			
			VAR LastDay =
			    IF (
			        SELECTEDVALUE ( dimDate[Slicer Month] ) = "Current Month",
			        EOMONTH ( TODAY (), 0 ),
			        EOMONTH ( SELECTEDVALUE ( dimDate[Slicer Month] ), 0 )
			    )
			
			VAR FirstDay =
			    DATE(CurrentYear, CurrentMonth, 01)
			
			RETURN
			    CALCULATE (
			        SUM ( cfgDailyBudget[DayRevenue] ),
			        cfgDailyBudget[BudgetType] = "R",
			        cfgDailyBudget[FacilityName] <> "All Locations",
			        cfgDailyBudget[ProviderCategory] = "Total",
			        DATESBETWEEN('dimDate'[Date],FirstDay,LastDay)
			    )
			*/
			```
		formatString: 0
		displayFolder: _Finance\_Complement measures
		lineageTag: fea7401f-18c9-43dc-9e2d-7667ad508c1b

	measure 'CH - % Compl/30 Hours' =
			
			[PW - Comp Hrs] / [Hour - Goal]
		formatString: 0%;-0%;0%
		displayFolder: _Operations\_Utilization
		lineageTag: 2c1938ae-9ee2-4f88-a84a-b4ab33650b4c

		changedProperty = FormatString

	measure 'CH - Fwd Sched/32 Hour' =
			
			[CW - Hrs] / [CW - Goal]
		formatString: 0%;-0%;0%
		displayFolder: _Operations\_Utilization
		lineageTag: 04307ece-55c1-4e91-b6d7-6e0586c8d124

		changedProperty = FormatString

	measure 'CH - PWK Schedule / 32 Hrs' =
			
			( [PW - Comp Hrs] + [PW - Pending Hrs] + [PW - NoShow Hrs] ) / [Hour - Goal]
		formatString: 0%;-0%;0%
		displayFolder: _Operations\_Utilization
		lineageTag: fd99843c-e60f-40fb-959a-6aa772d9526a

		changedProperty = FormatString

	measure 'Hour - Goal' = SUM ( vwResourceDetails[WKGoals] )
		formatString: #,0
		displayFolder: _Operations\_Utilization
		lineageTag: d467ade2-4f62-434e-91bd-39db2c2cc3eb

		changedProperty = FormatString

	measure 'CW - Appts' =
			
			VAR PreviousWeek =
			    IF (
			        SELECTEDVALUE ( dimDate[Slicer Week] ) = "Previous Week",
			        TODAY () - 1 - WEEKDAY ( TODAY () ),
			        SELECTEDVALUE ( dimDate[Slicer Week] )
			    )
			RETURN
			    CALCULATE (
			        [# Completed Visits - op] + [# No Show Visits - op] + [# Pending Visits - op],
			        DATESBETWEEN ( 'dimDate'[Date], PreviousWeek + 3, PreviousWeek + 7 )
			    )
		formatString: #,0
		displayFolder: _Operations\_Utilization
		lineageTag: 823bbcbf-bfe1-4afc-8f2a-19fd06dbcf03

	measure 'CW - Hrs' =
			VAR PreviousWeek =
			    IF (
			        SELECTEDVALUE ( dimDate[Slicer Week] ) = "Previous Week",
			        TODAY () - 1 - WEEKDAY ( TODAY () ),
			        SELECTEDVALUE ( dimDate[Slicer Week] )
			    )
			RETURN
			    CALCULATE (
			        [Duration Comp (Hours)] + [Duration Pending (Hours)] + [Duration NoShow (Hours)],
			        DATESBETWEEN ( 'dimDate'[Date], PreviousWeek + 3, PreviousWeek + 7 )
			    )
		displayFolder: _Operations\_Utilization
		lineageTag: 0915c9cc-826e-4d3d-8aca-af6fca4ad517

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MTD - Appts' = ```
			
			VAR PreviousWeek =
			    IF(
			        SELECTEDVALUE( dimDate[Slicer Week] ) = "Previous Week",
			        TODAY() - 1 - WEEKDAY( TODAY() ),
			        SELECTEDVALUE( dimDate[Slicer Week] )
			    )
			VAR SelectedMonth = MONTH( PreviousWeek )
			    
			VAR SelectedYear = YEAR( PreviousWeek )
			    
			VAR BeginMonth = DATE( SelectedYear, SelectedMonth, 01 )
			    
			    
			RETURN
			    CALCULATE(
			        [# Completed Visits - op],
			        DATESBETWEEN( 'dimDate'[Date], BeginMonth, PreviousWeek )
			    )
			```
		formatString: #,0
		displayFolder: _Operations\_Utilization
		lineageTag: e174c640-333d-4275-b785-6d3ea961f464

		changedProperty = FormatString

	measure 'MTD - Hours' = ```
			
			
			VAR PreviousWeek = 
			    IF(
			        SELECTEDVALUE(dimDate[Slicer Week]) = "Previous Week", 
			        TODAY() - 1 - WEEKDAY(Today()),
			        SELECTEDVALUE(dimDate[Slicer Week])
			        )
			
			VAR SelectedMonth = MONTH(PreviousWeek)
			VAR SelectedYear = YEAR(PreviousWeek)
			VAR BeginMonth = DATE(SelectedYear, SelectedMonth, 01)
			
			RETURN 
			   CALCULATE([Duration Comp (Hours)],
			      DATESBETWEEN('dimDate'[Date], BeginMonth, PreviousWeek)
			   )
			```
		displayFolder: _Operations\_Utilization
		lineageTag: 4ee2ec1f-7b91-4890-82c6-fa9be373f956

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PW - Cancel Appts' =
			VAR PreviousWeek =
			    IF (
			        SELECTEDVALUE ( dimDate[Slicer Week] ) = "Previous Week",
			        TODAY () - 1 - WEEKDAY ( TODAY () ),
			        SELECTEDVALUE ( dimDate[Slicer Week] )
			    )
			RETURN
			    CALCULATE (
			        [# Cancel Visits - op],
			        DATESBETWEEN ( 'dimDate'[Date], PreviousWeek - 4, PreviousWeek )
			    )
		formatString: #,0
		displayFolder: _Operations\_Utilization
		lineageTag: b08cdd6f-d876-48f9-a809-f5b56657d627

		changedProperty = FormatString

	measure 'PW - NoShow Appts' =
			VAR PreviousWeek =
			    IF (
			        SELECTEDVALUE ( dimDate[Slicer Week] ) = "Previous Week",
			        TODAY () - 1 - WEEKDAY ( TODAY () ),
			        SELECTEDVALUE ( dimDate[Slicer Week] )
			    )
			RETURN
			    CALCULATE (
			        [# No Show Visits - op],
			        DATESBETWEEN ( 'dimDate'[Date], PreviousWeek - 4, PreviousWeek )
			    )
		formatString: #,0
		displayFolder: _Operations\_Utilization
		lineageTag: 80c9fcd4-6763-4285-ac02-63dbe816413a

	measure 'PW - Comp Appts' =
			
			VAR PreviousWeek =
			    IF (
			        SELECTEDVALUE ( dimDate[Slicer Week] ) = "Previous Week",
			        TODAY () - 1 - WEEKDAY ( TODAY () ),
			        SELECTEDVALUE ( dimDate[Slicer Week] )
			    )
			RETURN
			    CALCULATE (
			        [# Completed Visits - op],
			        DATESBETWEEN ( 'dimDate'[Date], PreviousWeek - 4, PreviousWeek )
			    )
		formatString: #,0
		displayFolder: _Operations\_Utilization
		lineageTag: 3aff6ede-e3c1-40c1-9c7b-c530de8b8f4d

	measure 'PW - Cancel Hrs' =
			VAR PreviousWeek =
			    IF (
			        SELECTEDVALUE ( dimDate[Slicer Week] ) = "Previous Week",
			        TODAY () - 1 - WEEKDAY ( TODAY () ),
			        SELECTEDVALUE ( dimDate[Slicer Week] )
			    )
			RETURN
			    CALCULATE (
			        [Duration Cancel (Hours)],
			        DATESBETWEEN ( 'dimDate'[Date], PreviousWeek - 4, PreviousWeek )
			    )
		displayFolder: _Operations\_Utilization
		lineageTag: b4656ffc-380e-485d-ad50-4ca5456fdf1c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PW - Comp Hrs' =
			
			VAR PreviousWeek =
			    IF (
			        SELECTEDVALUE ( dimDate[Slicer Week] ) = "Previous Week",
			        TODAY () - 1 - WEEKDAY ( TODAY () ),
			        SELECTEDVALUE ( dimDate[Slicer Week] )
			    )
			RETURN
			    CALCULATE (
			        [Duration Comp (Hours)],
			        DATESBETWEEN ( 'dimDate'[Date], PreviousWeek - 4, PreviousWeek )
			    )
		displayFolder: _Operations\_Utilization
		lineageTag: 7a731383-179a-490e-91d6-53f1d5b02ba4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PW - NoShow Hrs' =
			VAR PreviousWeek =
			    IF (
			        SELECTEDVALUE ( dimDate[Slicer Week] ) = "Previous Week",
			        TODAY () - 1 - WEEKDAY ( TODAY () ),
			        SELECTEDVALUE ( dimDate[Slicer Week] )
			    )
			RETURN
			    CALCULATE (
			        [Duration NoShow (Hours)],
			        DATESBETWEEN ( 'dimDate'[Date], PreviousWeek - 4, PreviousWeek )
			    )
		displayFolder: _Operations\_Utilization
		lineageTag: 8e7737ef-476e-4348-9f42-641b80d614d2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FUS - Day To FU' =
			
			IF (
			    [# Future Appts] = 0,
			    BLANK (),
			    [FUS - Total Days to Next Appt] / ( [# Future Appts] )
			)
		formatString: 0
		displayFolder: _Operations\_Utilization
		lineageTag: 581159c2-acbd-4270-920d-9ba1a85ca816

		changedProperty = FormatString

	measure 'FUS - Sched % after Cancel' =
			
			[# Future Appts - Cancel] / [PW - Cancel Appts]
		formatString: 0%;-0%;0%
		displayFolder: _Operations\_Utilization
		lineageTag: d738274e-d7d1-46d3-97d2-d8009a96f61e

		changedProperty = FormatString

	measure 'FUS - Sched % after Compl' =
			
			[# Future Appts - Checkout] / [PW - Comp Appts]
		formatString: 0%;-0%;0%
		displayFolder: _Operations\_Utilization
		lineageTag: bcdc7491-d4d7-47d7-872b-401e8a2e1a2d

		changedProperty = FormatString

	measure 'FUS - Sched % after No Show' =
			
			[# Future Appts - No Show] / [PW - NoShow Appts]
		formatString: 0%;-0%;0%
		displayFolder: _Operations\_Utilization
		lineageTag: fda930c6-d4c2-4265-8672-f2a65f5a1660

		changedProperty = FormatString

	measure 'Revenue - Psychiatric - Existent Patient' =
			
			CALCULATE(
			    [Revenue - Existent Visits],
			    cfgRevenueVisits[Type Provider ID] = 2
			)
		formatString: 0
		displayFolder: _Finance\_Complement measures
		lineageTag: 194016c3-6f61-428e-80c5-f03c08b6912c

	measure 'Revenue - Psychiatric - New Patient' =
			
			CALCULATE(
			    [Revenue - New visits],
			    cfgRevenueVisits[Type Provider ID] = 2
			)
		formatString: 0
		displayFolder: _Finance\_Complement measures
		lineageTag: 83052296-57e6-418f-a656-8353bd5e04d7

	measure 'Revenue - Therapy - Existent Patient' =
			
			CALCULATE(
			    [Revenue - Existent Visits],
			    cfgRevenueVisits[Type Provider ID] = 1
			)
		formatString: 0
		displayFolder: _Finance\_Complement measures
		lineageTag: 4488b20d-fa41-4a90-893d-5bf89155433b

	measure 'Revenue - Therapy - New Patient' =
			
			CALCULATE(
			    [Revenue - New visits],
			    cfgRevenueVisits[Type Provider ID] = 1
			)
		formatString: 0
		displayFolder: _Finance\_Complement measures
		lineageTag: 82569f2e-6e7d-479f-b01b-64f5c2aef31c

	measure '# Converted - DLM 1' =
			
			calculate(
			    [# Leads - DLM 1],
			    'vwCollectiveLead - DQ'[Status] = "Converted"
			)
		formatString: #,0
		displayFolder: _Marketing\DLM - DQ
		lineageTag: 4b49bcb5-6295-4b4a-91a8-a13515492f16

	measure '# Leads - DLM 1' =
			CALCULATE(
			     COUNTROWS('vwCollectiveLead - DQ'),
			     USERELATIONSHIP('vwCollectiveLead - DQ'[DateLastModified], dimDate[Date]))
		formatString: #,0
		displayFolder: _Marketing\DLM - DQ
		lineageTag: a85d80f0-b54a-476b-b146-d36360b2487e

	measure '# Not Converted - DLM 1' =
			calculate(
			    [# Leads - DLM 1],
			    'vwCollectiveLead - DQ'[Status] = "Not Converted"
			)
		formatString: #,0
		displayFolder: _Marketing\DLM - DQ
		lineageTag: b06fa0f9-aa9e-4d22-8aca-e87a78eb0467

	measure '% Conversion - DLM 1' = [# Converted - DLM 1] / [# Leads - DLM 1]
		formatString: 0\ %;-0\ %;0\ %
		displayFolder: _Marketing\DLM - DQ
		lineageTag: 48f5a5ea-8dd9-446e-bd8f-cfbd1fd8ec8c

	measure '# Converted_Full 1' =
			
			calculate(
			    [# Leads 1],
			    'vwCollectiveLead - DQ'[Status] = "Converted"
			)
		formatString: #,0
		displayFolder: _Marketing\Inquiry - DQ
		lineageTag: 2cd39e4b-5584-4968-ad0b-857d381fc037

	measure '# Leads 1' = ```
			
			 COUNT(
			     'vwCollectiveLead - DQ'[LeadStatus]
			    )
			```
		formatString: #,0
		displayFolder: _Marketing\Inquiry - DQ
		lineageTag: 8c8855bd-e6d2-4649-8d51-e825cb9e7dc6

		changedProperty = FormatString

	measure '# Not Converted 1' =
			
			calculate(
			    [# Leads 1],
			    'vwCollectiveLead - DQ'[Status] = "Not Converted"
			)
		formatString: #,0
		displayFolder: _Marketing\Inquiry - DQ
		lineageTag: 6dc49a06-6b3d-4b32-96a1-aa2a30ad795b

	measure '% Conversion 1' = [# Converted 1] + [# Completed 1] / [# Leads 1]
		formatString: 0\ %;-0\ %;0\ %
		displayFolder: _Marketing\Inquiry - DQ
		lineageTag: aafa3eb3-8252-486e-90ed-1781811d2d0d

	measure '# Completed - FU - Psy - Claim' =
			CALCULATE (
			    COUNTROWS ( 'vwChargeMasterExtended' ),
			    FILTER ( 'vwChargeMasterExtended', [VisitType] = "FollowUp" ),
			    FILTER ( 'vwChargeMasterExtended', [ProviderCategoryID] = 2 )
			)
		formatString: 0
		displayFolder: _Finance\_Claims
		lineageTag: a1aa3c15-a360-4af2-b38f-fbcdb52ce559

	measure '# Completed - FU - Th - Claim' =
			
			CALCULATE (
			    COUNTROWS ( 'vwChargeMasterExtended' ),
			    FILTER('vwChargeMasterExtended', [VisitType] = "FollowUp"),
			    FILTER('vwChargeMasterExtended', [ProviderCategoryID] in {1,3} )
			)
		formatString: 0
		displayFolder: _Finance\_Claims
		lineageTag: 24ec61c0-797a-43f1-9abe-ded68bb65439

	measure '# Completed - Intake - Psy - Claim' =
			
			CALCULATE (
			    COUNTROWS ( 'vwChargeMasterExtended' ),
			    FILTER('vwChargeMasterExtended', [VisitType] = "Intake"),
			    FILTER('vwChargeMasterExtended', [ProviderCategoryID] = 2)
			)
		formatString: 0
		displayFolder: _Finance\_Claims
		lineageTag: 6137795c-2f14-42c5-8257-ac781e171aa5

	measure '# Completed - Intake - Th - Claim' =
			
			CALCULATE (
			    COUNTROWS ( 'vwChargeMasterExtended' ),
			    FILTER('vwChargeMasterExtended', [VisitType] = "Intake"),
			    FILTER('vwChargeMasterExtended', [ProviderCategoryID] in {1,3} )
			)
		formatString: 0
		displayFolder: _Finance\_Claims
		lineageTag: 12aa5c2b-7d02-44a8-8832-ec88a796c144

	measure '# Completed - Total - Claim' = ```
			[# Completed - FU - Psy - Claim] + 
			[# Completed - FU - Th - Claim] +
			[# Completed - Intake - Psy - Claim] +
			[# Completed - Intake - Th - Claim]
			```
		formatString: #,0
		displayFolder: _Finance\_Claims
		lineageTag: 0727bffd-15d8-4c7e-abbf-71e18a2eb14b

		changedProperty = FormatString

	measure '# Cancel Visits - Claim' =
			
			CALCULATE (
			    COUNTROWS ( 'vwChargeMasterExtended' ),
			    FILTER ( 'vwChargeMasterExtended', [VisitType] = "Cancel" ),
			    FILTER ( 'vwChargeMasterExtended', [ProviderCategoryID] IN { 1, 2, 3 } )
			)
		displayFolder: _Finance\_Claims
		lineageTag: 859c830f-319b-4705-ae80-f3a3486bb79d

	measure '# No Show Visits - Claim' =
			
			CALCULATE (
			    COUNTROWS ( 'vwChargeMasterExtended' ),
			    FILTER ( 'vwChargeMasterExtended', [VisitType] = "NoShow" ),
			    FILTER ( 'vwChargeMasterExtended', [ProviderCategoryID] IN { 1, 2, 3 } )
			)
		displayFolder: _Finance\_Claims
		lineageTag: da51a01d-bca3-4ff5-9d88-b00689d0cf84

	measure Goal_total_Hrs = ```
			
			SUM( 
			    vwSummaryUtilSchdByResource[Goal] 
			)
			```
		formatString: #,0
		displayFolder: _Operations\Comp-Sched
		lineageTag: 8551fb31-046a-42d6-9ee5-30b02c112223

		annotation PBI_FormatHint = {"isDecimal":true}

	measure Total_Hrs = ```
			
			SUM( 
			    vwSummaryUtilSchdByResource[TotHours] 
			)
			```
		formatString: #,0
		displayFolder: _Operations\Comp-Sched
		lineageTag: 1441ca41-a5a6-4e8a-8a75-ca3dca4370df

		annotation PBI_FormatHint = {"isDecimal":true}

	measure Hours_trend =
			
			SUM(
			    vwSummaryUtilizationByResource[Hours]
			)
		formatString: #,0
		displayFolder: _Operations\Hours Trend
		lineageTag: 72fef3f2-66d3-4047-bf06-1dad9273ef2c

		annotation PBI_FormatHint = {"isDecimal":true}

	measure Goal_trend =
			
			SUM(
			    vwSummaryUtilizationByResource[Goal]
			)
		formatString: #,0
		displayFolder: _Operations\Hours Trend
		lineageTag: 025a2c53-9c5c-4745-9566-6edef525a71d

		annotation PBI_FormatHint = {"isDecimal":true}

	measure Duration_Average = ```
			
			AVERAGE(
			    vwMktgwithLTV[Duration]
			)
			
			```
		displayFolder: _LifeTimeValue
		lineageTag: c16ccb24-f582-49a4-a370-dd344181d7b9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Patients = ```
			
			countrows(
			    vwMktgwithLTV
			)
			
			-- Countrows because there are patients IDs repeated. 
			```
		formatString: #,0
		displayFolder: _LifeTimeValue
		lineageTag: 218c6fc7-c8a0-4721-98bc-b6d4b5e34623

	measure Tot_Revenue =
			
			SUM(
			    vwMktgwithLTV[TotalRevenue]
			)
		formatString: #,0
		displayFolder: _LifeTimeValue
		lineageTag: 0ce34c52-740d-4afa-98fd-fdd6b3a05adc

	measure Visit_Cancel =
			
			SUM(
			    vwMktgwithLTV[CancelVisits]
			)
		formatString: #,0
		displayFolder: _LifeTimeValue
		lineageTag: dd562f76-9268-4690-8b73-28f32f0b7859

	measure Visit_NoShow =
			
			SUM(
			    vwMktgwithLTV[NoShowVisits]
			)
		formatString: #,0
		displayFolder: _LifeTimeValue
		lineageTag: 18a797ed-88ab-4788-acd2-44867ff2ce43

	measure Visit_PSY =
			
			SUM(
			    vwMktgwithLTV[PsychVisits]
			)
		formatString: #,0
		displayFolder: _LifeTimeValue
		lineageTag: 9f67e467-cd16-450f-b138-7fd74f275fc4

	measure Visit_TH =
			
			SUM(
			    vwMktgwithLTV[TherapyVisits]
			)
		formatString: #,0
		displayFolder: _LifeTimeValue
		lineageTag: 41b88cce-8aa5-47ec-9724-2c370199a617

	measure Visit_Total =
			
			[Visit_NoShow] + [Visit_PSY] + [Visit_TH]
		formatString: #,0
		displayFolder: _LifeTimeValue
		lineageTag: 5695f500-1d22-4d59-be77-cafcd7fed4c4

	measure 'Visits_Pending Encounter' =
			
			CALCULATE (
			        COUNT ( vwScheduleVisitDetails[VisitID] ),
			        'vwScheduleVisitDetails'[VisitStatusID] in {3}
			        -- last 9 weeks and 3 next weeks
			        --USERELATIONSHIP ( vwScheduleVisitDetails[ResourceID], vwResourceDetails[ResourceId] ),
			        --USERELATIONSHIP ( vwScheduleVisitDetails[FacilityID], vwFacilitiesMaster[FacilityId] )
			)
		formatString: #,0
		displayFolder: _Encounters
		lineageTag: 68e9e1e9-429d-4769-8de3-e087d27d5fc4

	measure 'Visits_Full Encounter' = ```
			
			CALCULATE (
			        COUNT ( vwScheduleVisitDetails[VisitID] ),
			        'vwScheduleVisitDetails'[VisitStatusID] in {1,2,3,7} 
			        -- last 9 weeks and 3 next weeks
			        --USERELATIONSHIP ( vwScheduleVisitDetails[ResourceID], vwResourceDetails[ResourceId] ),
			        --USERELATIONSHIP ( vwScheduleVisitDetails[FacilityID], vwFacilitiesMaster[FacilityId] )
			)
			```
		formatString: #,0
		displayFolder: _Encounters
		lineageTag: 97c2844a-6afb-4011-ab1a-82f2d67de3a3

	measure 'Visits_Completed Encounter' =
			
			CALCULATE (
			    COUNT ( vwScheduleVisitDetails[VisitID] ),
			    'vwScheduleVisitDetails'[VisitStatusID] IN { 1,2 }
			    -- last 9 weeks and 3 next weeks
			    --USERELATIONSHIP ( vwScheduleVisitDetails[ResourceID], vwResourceDetails[ResourceId] ),
			    --USERELATIONSHIP ( vwScheduleVisitDetails[FacilityID], vwFacilitiesMaster[FacilityId] )
			)
		formatString: #,0
		displayFolder: _Encounters
		lineageTag: 20ee4c32-5d7f-4fb3-97d1-ad8220932050

	measure Encounters = ```
			COUNT(vwEncounter[EncounterID]) 
			```
		formatString: #,0
		displayFolder: _Encounters
		lineageTag: 1d15869c-d474-4acb-a65a-5562ea8d9a45

	measure Clinicians =
			
			CALCULATE(
			    COUNT(vwResourceDetails[Full Name]),
			    FILTER(
			        vwEncounter,
			        [Encounters] > 0
			    )
			)
		formatString: #,0
		displayFolder: _Encounters
		lineageTag: 266d2651-ae73-498f-93f0-1dac611eaac8

	measure 'Average Encounters' = ```
			
			    [Encounters] / [Clinicians]
			```
		formatString: #,0
		displayFolder: _Encounters
		lineageTag: e09b4883-91f1-478f-a9f5-7011cb4eca61

		annotation PBI_FormatHint = {"isDecimal":true}

	measure Color_Encounter = ```
			
			
			VAR LastFriday = TODAY() - WEEKDAY(TODAY(), 1) + 6
			VAR result = FORMAT(LastFriday, "yyyy-mm-dd")
			VAR Week = SELECTEDVALUE(dimDate[LastFridayOfWeek])
			
			RETURN
			IF( week = result, 
			        "#FFF8D5",
			        IF( week > result, 
			            "#FBF1E5", 
			            "#FFFFFF" 
			        )
			)
			```
		displayFolder: _Encounters
		lineageTag: 4ce59a5a-e127-4f80-973b-faaabe4d4f07

	measure 'Visits_NoShow Encounter' =
			
			CALCULATE (
			        COUNT ( vwScheduleVisitDetails[VisitID] ),
			        'vwScheduleVisitDetails'[VisitStatusID] in {7}
			        -- last 9 weeks and 3 next weeks
			        --USERELATIONSHIP ( vwScheduleVisitDetails[ResourceID], vwResourceDetails[ResourceId] ),
			        --USERELATIONSHIP ( vwScheduleVisitDetails[FacilityID], vwFacilitiesMaster[FacilityId] )
			)
		formatString: #,0
		displayFolder: _Encounters
		lineageTag: e58d4b3f-279f-479f-b24c-d71ff223487b

	measure 'Revenue Per Patient' = [Tot_Revenue] / [Patients]
		formatString: #,0
		displayFolder: _LifeTimeValue
		lineageTag: f6f0d1b6-6fcc-4da1-b4c8-bbb6ee0f3f98

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'PW - Pending Hrs' =
			
			VAR PreviousWeek =
			    IF (
			        SELECTEDVALUE ( dimDate[Slicer Week] ) = "Previous Week",
			        TODAY () - 1 - WEEKDAY ( TODAY () ),
			        SELECTEDVALUE ( dimDate[Slicer Week] )
			    )
			RETURN
			    CALCULATE (
			        [Duration Pending (Hours)],
			        DATESBETWEEN ( 'dimDate'[Date], PreviousWeek - 4, PreviousWeek )
			    )
		displayFolder: _Operations\_Utilization
		lineageTag: 526d48b4-1908-4096-ac6a-2866d43841c4

	measure Measure_filter_utilization =
			
			IF(
			    [CW - Appts] + [PW - Comp Appts] = 0 ,
			    0,
			    1
			)
		formatString: 0
		displayFolder: _Operations\_Utilization
		lineageTag: 74679714-16ba-4097-908a-9decf933d505

	measure '# Cancel Visits - op' = ```
			
			CALCULATE (
			    COUNTROWS ( 'vwScheduleVisitDetails' ),
			    FILTER (
			        'vwScheduleVisitDetails',
			        [VisitStatusID] = 4
			    ) 
			    --,USERELATIONSHIP(vwScheduleVisitDetails[ResourceID],vwResourceDetails[ResourceId])
			    --,USERELATIONSHIP(vwScheduleVisitDetails[FacilityID],vwFacilitiesMaster[FacilityId])
			)
			```
		formatString: 0
		displayFolder: _Operations\_Complement Measures
		lineageTag: 9078d8be-0259-42eb-b9b9-e8532d0e18dc

	measure '# Checkin Visits - op' =
			
			CALCULATE (
			    COUNTROWS ( 'vwScheduleVisitDetails' ),
			    FILTER ( 'vwScheduleVisitDetails', [VisitStatusID] IN { 1 } ),
			    NOT ( vwScheduleVisitDetails[VisitTypeID] = 716 )
			    --,USERELATIONSHIP ( vwScheduleVisitDetails[ResourceID], vwResourceDetails[ResourceId] )
			    --,USERELATIONSHIP ( vwScheduleVisitDetails[FacilityID], vwFacilitiesMaster[FacilityId] )
			)
		formatString: #,0
		displayFolder: _Operations\_Complement Measures
		lineageTag: 2bae829f-b865-4d0b-8f34-b39cdfeada87

		changedProperty = FormatString

	measure '# Checkout Visits - op' =
			
			CALCULATE (
			    COUNTROWS ( 'vwScheduleVisitDetails' ),
			    FILTER ( 'vwScheduleVisitDetails', [VisitStatusID] IN { 2 } ),
			    NOT ( vwScheduleVisitDetails[VisitTypeID] = 716 )
			    --,USERELATIONSHIP ( vwScheduleVisitDetails[ResourceID], vwResourceDetails[ResourceId] )
			    --,USERELATIONSHIP ( vwScheduleVisitDetails[FacilityID], vwFacilitiesMaster[FacilityId] )
			)
		formatString: 0
		displayFolder: _Operations\_Complement Measures
		lineageTag: adde02d6-80b0-4d56-b091-70852dc7540b

		changedProperty = FormatString

	measure '# Completed Visits - op' = ```
			
			[# Checkout Visits - op] 
			+ 
			[# Checkin Visits - op]
			```
		formatString: #,0
		displayFolder: _Operations\_Complement Measures
		lineageTag: f3ef3991-8d2d-404a-9d5a-ba619a2294a8

		changedProperty = FormatString

	measure '# Future Appts' = [# Future Appts - Completed] + [# Future Appts - Cancel]
		formatString: 0
		displayFolder: _Operations\_Complement Measures
		lineageTag: fb6109a3-a1f9-42d0-a3be-be91fa09c93b

	measure '# Future Appts - Cancel' =
			
			VAR PreviousWeek =
			    IF (
			        SELECTEDVALUE ( dimDate[Slicer Week] ) = "Previous Week",
			        TODAY () - 1
			            - WEEKDAY ( TODAY () ),
			        SELECTEDVALUE ( dimDate[Slicer Week] )
			    )
			RETURN
			    CALCULATE (
			        COUNT ( vwScheduleVisitDetails[NextAppt] ),
			        'vwScheduleVisitDetails'[VisitStatusID] = 4,
			        DATESBETWEEN ( 'dimDate'[Date], PreviousWeek - 5, PreviousWeek )
			        --,USERELATIONSHIP ( vwScheduleVisitDetails[ResourceID], vwResourceDetails[ResourceId] )
			        --,USERELATIONSHIP ( vwScheduleVisitDetails[FacilityID], vwFacilitiesMaster[FacilityId] )
			    )
		formatString: 0
		displayFolder: _Operations\_Complement Measures
		lineageTag: 8111e751-5281-428c-92d6-2fac76bc3c92

	measure '# Future Appts - Checkout' =
			
			VAR PreviousWeek =
			    IF (
			        SELECTEDVALUE ( dimDate[Slicer Week] ) = "Previous Week",
			        TODAY () - 1 - WEEKDAY ( TODAY () ),
			        SELECTEDVALUE ( dimDate[Slicer Week] )
			    )
			RETURN
			    CALCULATE (
			        COUNT ( vwScheduleVisitDetails[NextAppt] ),
			        'vwScheduleVisitDetails'[VisitStatusID] = 2,
			        DATESBETWEEN ( 'dimDate'[Date], PreviousWeek - 5, PreviousWeek )
			        --,USERELATIONSHIP ( vwScheduleVisitDetails[ResourceID], vwResourceDetails[ResourceId] )
			        --,USERELATIONSHIP ( vwScheduleVisitDetails[FacilityID], vwFacilitiesMaster[FacilityId] )
			    )
		formatString: 0
		displayFolder: _Operations\_Complement Measures
		lineageTag: 85cb53ab-d051-4a1f-959b-aa3883888363

	measure '# Future Appts - Completed' = [# Future Appts - Checkout] + [# Future Appts - No Show]
		formatString: 0
		displayFolder: _Operations\_Complement Measures
		lineageTag: 7932489b-c344-4e02-afd4-2dd41b771ba0

	measure '# Future Appts - No Show' =
			
			VAR PreviousWeek =
			    IF (
			        SELECTEDVALUE ( dimDate[Slicer Week] ) = "Previous Week",
			        TODAY () - 1 - WEEKDAY ( TODAY () ),
			        SELECTEDVALUE ( dimDate[Slicer Week] )
			    )
			RETURN
			    CALCULATE (
			        COUNT ( vwScheduleVisitDetails[NextAppt] ),
			        'vwScheduleVisitDetails'[VisitStatusID] = 7,
			        DATESBETWEEN ( 'dimDate'[Date], PreviousWeek - 5, PreviousWeek )
			        --,USERELATIONSHIP ( vwScheduleVisitDetails[ResourceID], vwResourceDetails[ResourceId] )
			        --,USERELATIONSHIP ( vwScheduleVisitDetails[FacilityID], vwFacilitiesMaster[FacilityId] )
			    )
		formatString: 0
		displayFolder: _Operations\_Complement Measures
		lineageTag: b41b9060-2ee6-4498-9ca8-c2b5da8f17a0

	measure '# No Show Visits - op' =
			
			CALCULATE (
			    COUNTROWS ( 'vwScheduleVisitDetails' ),
			    FILTER ( 'vwScheduleVisitDetails', [VisitStatusID] = 7 ),
			    NOT ( vwScheduleVisitDetails[VisitTypeID] = 716 )
			    --,USERELATIONSHIP ( vwScheduleVisitDetails[ResourceID], vwResourceDetails[ResourceId] )
			    --,USERELATIONSHIP ( vwScheduleVisitDetails[FacilityID], vwFacilitiesMaster[FacilityId] )
			)
		formatString: 0
		displayFolder: _Operations\_Complement Measures
		lineageTag: e2881c2b-1bbc-476f-a44a-debb8fc91d33

	measure '# Pending Visits - op' =
			
			CALCULATE (
			    COUNTROWS ( 'vwScheduleVisitDetails' ),
			    FILTER ( 'vwScheduleVisitDetails', [VisitStatusID] = 3 ),
			    NOT ( vwScheduleVisitDetails[VisitTypeID] = 716 )
			    --,USERELATIONSHIP ( vwScheduleVisitDetails[ResourceID], vwResourceDetails[ResourceId] )
			    --,USERELATIONSHIP ( vwScheduleVisitDetails[FacilityID], vwFacilitiesMaster[FacilityId] )
			)
		formatString: 0
		displayFolder: _Operations\_Complement Measures
		lineageTag: d10c3035-6e72-4d01-b6b3-1186372fe909

	measure '# Planned Visits' = [# Completed Visits - op] + [# Pending Visits - op]
		formatString: 0
		displayFolder: _Operations\_Complement Measures
		lineageTag: ba1cdad3-2094-436d-af0d-f8c2eeede567

	measure 'CW - Goal' =
			
			SUM(
			    vwResourceDetails[WKGoals]
			)
		formatString: #,0
		displayFolder: _Operations\_Complement Measures
		lineageTag: 62da9958-e829-4b03-ad6c-50f8add532ca

	measure 'Duration Cancel (Hours)' = [Duration Cancel (Minutes)] / 60
		displayFolder: _Operations\_Complement Measures
		lineageTag: fcc00eae-1676-49a8-83ac-3583bd1b991b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Duration Cancel (Minutes)' =
			CALCULATE (
			    SUM( vwScheduleVisitDetails[Duration] ),
			    FILTER(
			        vwScheduleVisitDetails,
			        vwScheduleVisitDetails[VisitStatusID] IN { 4 }
			    )
			    --,USERELATIONSHIP ( vwScheduleVisitDetails[ResourceID], vwResourceDetails[ResourceId] )
			    --,USERELATIONSHIP ( vwScheduleVisitDetails[FacilityID], vwFacilitiesMaster[FacilityId] )
			)
		formatString: 0
		displayFolder: _Operations\_Complement Measures
		lineageTag: 137779a3-5dd7-4dff-9421-5790d76b614c

	measure 'Duration Comp (Hours)' = [Duration Comp (Minutes)] / 60
		displayFolder: _Operations\_Complement Measures
		lineageTag: 1cb7f850-4a57-4007-a367-fb7e8762aaff

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Duration Comp (Minutes)' =
			CALCULATE (
			    SUM( vwScheduleVisitDetails[Duration] ),
			    FILTER(
			        vwScheduleVisitDetails,
			        vwScheduleVisitDetails[VisitStatusID] IN { 2 }
			    )
			    --,USERELATIONSHIP ( vwScheduleVisitDetails[ResourceID], vwResourceDetails[ResourceId] )
			    --,USERELATIONSHIP ( vwScheduleVisitDetails[FacilityID], vwFacilitiesMaster[FacilityId] )
			)
		formatString: 0
		displayFolder: _Operations\_Complement Measures
		lineageTag: 58b61449-b228-4493-a468-8eaf1cfd5d5e

	measure 'Duration NoShow (Hours)' = [Duration NoShow (Minutes)] / 60
		displayFolder: _Operations\_Complement Measures
		lineageTag: c74db0dd-4acf-410e-abd0-1ba6da97b6c9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Duration NoShow (Minutes)' =
			
			CALCULATE (
			    SUM( vwScheduleVisitDetails[Duration] ),
			    FILTER(
			        vwScheduleVisitDetails,
			        vwScheduleVisitDetails[VisitStatusID] IN { 7 }
			    )
			    --,USERELATIONSHIP ( vwScheduleVisitDetails[ResourceID], vwResourceDetails[ResourceId] )
			    --,USERELATIONSHIP ( vwScheduleVisitDetails[FacilityID], vwFacilitiesMaster[FacilityId] )
			)
		formatString: 0
		displayFolder: _Operations\_Complement Measures
		lineageTag: 606197d9-74e4-4906-b127-9c1ec1b2af68

	measure 'Duration Pending (Hours)' = [Duration Pending (Minutes)] / 60
		displayFolder: _Operations\_Complement Measures
		lineageTag: f45a0e8f-2c54-4fa6-98d0-4b14f9f80494

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Duration Pending (Minutes)' =
			CALCULATE (
			    SUM( vwScheduleVisitDetails[Duration] ),
			    FILTER(
			        vwScheduleVisitDetails,
			        vwScheduleVisitDetails[VisitStatusID] IN { 3 }
			    )
			    --,USERELATIONSHIP ( vwScheduleVisitDetails[ResourceID], vwResourceDetails[ResourceId] )
			    --,USERELATIONSHIP ( vwScheduleVisitDetails[FacilityID], vwFacilitiesMaster[FacilityId] )
			)
		formatString: 0
		displayFolder: _Operations\_Complement Measures
		lineageTag: c965fc7d-7ef2-496f-ba8b-705995423900

	measure 'FUS - Total Days to Next Appt' =
			
			VAR PreviousWeek =
			    IF (
			        SELECTEDVALUE( dimDate[Slicer Week] ) = "Previous Week",
			        TODAY() - 1 - WEEKDAY( TODAY() ),
			        SELECTEDVALUE( dimDate[Slicer Week] )
			    )
			RETURN
			    CALCULATE (
			        SUM( vwScheduleVisitDetails[Difference Between Dates] ),
			        OR(
			            vwScheduleVisitDetails[VisitStatusID] = 2,
			            OR(
			                vwScheduleVisitDetails[VisitStatusID] = 4,
			                vwScheduleVisitDetails[VisitStatusID] = 7
			            )
			        ),
			        vwScheduleVisitDetails[PatientID] <> 0,
			        DATESBETWEEN( 'dimDate'[Date], PreviousWeek - 5, PreviousWeek )
			        --,USERELATIONSHIP ( vwScheduleVisitDetails[ResourceID], vwResourceDetails[ResourceId] )
			        --,USERELATIONSHIP ( vwScheduleVisitDetails[FacilityID], vwFacilitiesMaster[FacilityId] )
			    )
		displayFolder: _Operations\_Complement Measures
		lineageTag: 5e35e94a-2431-4177-8d8f-b2fffe06486e

	measure 'Contractual Adjustments' = ```
			
			    SUM(vwSumPaymentDetailExtended[CreditAdjustment])
			```
		displayFolder: _RCM
		lineageTag: dbbe8db3-3405-4149-8645-1265981481e5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Debit Adjustment' = ```
			
			    SUM(vwSumPaymentDetailExtended[DebitAdjustment])
			```
		displayFolder: _RCM
		lineageTag: 5ca92825-c69b-44ef-bfc8-11344b52a5fa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Grand total Ending A/R' = ```
			
			    SUM(vwSumPaymentDetailExtended[GrandTotalAR])
			```
		displayFolder: _RCM
		lineageTag: 5a15014d-5754-46ae-86c7-08c906253fe2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Expected Amount' = ```
			
			    SUM(vwSumPaymentDetailExtended[PayerFee])
			```
		displayFolder: _RCM
		lineageTag: e5e15532-3055-4df0-8523-55b5265c48ed

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Insurance Payments' = ```
			
			    SUM(vwSumPaymentDetailExtended[InsurancePayment])
			```
		displayFolder: _RCM
		lineageTag: 3f2602b2-5d14-4f7c-885a-913feee15263

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Patient Payments' = ```
			
			    SUM(vwSumPaymentDetailExtended[PatientPayment])
			```
		displayFolder: _RCM
		lineageTag: f2bc110d-847d-418d-b449-c1aacb1718b9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Refunds = ```
			
			    SUM(vwSumPaymentDetailExtended[Refund])
			```
		displayFolder: _RCM
		lineageTag: e40f43c0-2e24-4d68-ac89-5e8522a6e035

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Write-Off = ```
			
			    SUM(vwSumPaymentDetailExtended[WriteOff])
			```
		displayFolder: _RCM
		lineageTag: 27553a5e-c4c9-4ed6-bd6b-6878b5183111

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DAR = ```
			
			
			var endDate = TODAY()-1
			var startDate = TODAY()-91
			
			var result = 
			    CALCULATE([Gross Collections]
			                ,DATESBETWEEN(dimDate[Date],startDate,endDate)
			            )/90
			return [Total Gross A/R]/result
			```
		displayFolder: _RCM
		lineageTag: 009cdcb3-582c-4c79-82a1-a673cf772d57

	measure 'Grand Total' = [Expected Amount] - [Total Net A/R]
		displayFolder: _RCM
		lineageTag: de9fd90a-0b0d-4656-9985-22bdb3b0c8b4

	measure 'Gross Collections' = [Patient Payments] + [Insurance Payments]
		displayFolder: _RCM
		lineageTag: a20b2153-aca3-4f23-8b6a-099c0244df05

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net Charges' = [Expected Amount] - [Contractual Adjustments]
		displayFolder: _RCM
		lineageTag: 5a87d2a9-0970-4aa6-9366-dc423f4b5921

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net Collections' = [Gross Collections] - [Refunds]
		displayFolder: _RCM
		lineageTag: 5db752e6-ddc3-4ce7-bedb-315fcece2592

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Other Adjustments' = [Write-Off] + [Debit Adjustment]
		displayFolder: _RCM
		lineageTag: 29b4c64d-5e6f-4425-8895-7d3e6ab720c3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Days To Convert' = AVERAGE('vwMktgwithLTV'[Days to Convert])
		displayFolder: _LifeTimeValue
		lineageTag: a5c2c278-a3a9-499a-ac2d-ff785c0c800a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Days To First Appt' = AVERAGE('vwMktgwithLTV'[Days to First Appt])
		displayFolder: _LifeTimeValue
		lineageTag: ef18a649-7558-46f7-89bc-06597a71f8e7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Intakes Booked' =
			
			CALCULATE (
			    COUNTROWS ( 'vwScheduleVisitDetails' ),
			    --FILTER ( 'vwScheduleVisitDetails', [VisitStatusID] IN { 1, 2 } ),
			    vwScheduleVisitDetails[VisitTypeID] IN { 1126, 1127, 1128, 1129 },
			    vwScheduleVisitDetails[VisitDate] < TODAY()
			    --vwResourceDetails[ProviderCategoryID] IN {1,3},
			
			)
		formatString: 0
		displayFolder: _Operations\_Intake Analysis
		lineageTag: 1a2d05f1-9242-4b75-8cc4-899ac8bebcdb

	measure 'Intakes Completed' =
			
			CALCULATE (
			    COUNTROWS ( 'vwScheduleVisitDetails' ),
			    vwScheduleVisitDetails[VisitStatusID] IN { 1, 2 } ,
			    vwScheduleVisitDetails[VisitTypeID] IN { 1126, 1127, 1128, 1129 }
			    --vwScheduleVisitDetails[VisitDate] < TODAY()
			    --vwResourceDetails[ProviderCategoryID] IN {1,3},
			
			)
		formatString: #,0
		displayFolder: _Operations\_Intake Analysis
		lineageTag: 86978f68-620b-46f9-9718-dfbd78f9163c

	measure 'Intakes Completed %' = [Intakes Completed] / [Intakes Booked]
		formatString: 0%;-0%;0%
		displayFolder: _Operations\_Intake Analysis
		lineageTag: 1af9a616-5e5e-430b-a8b5-29bbc5dcf086

	measure 'Visits Completed wo Next Visit' =
			
			CALCULATE (
			    COUNTROWS ( 'vwScheduleVisitDetails' ),
			    'vwScheduleVisitDetails'[VisitStatusID] IN { 1, 2, 3, 6, 10 } ,
			    vwScheduleVisitDetails[VisitTypeID] <> 716,
			    vwScheduleVisitDetails[NextAppt] = BLANK()
			    --vwResourceDetails[ProviderCategoryID] IN {1,3},
			
			)
		formatString: 0
		displayFolder: _Daily Operations
		lineageTag: 391ebd98-9222-43a8-ae63-06d6d84dedba

	measure 'Visits Cancel/NoShow wo Next Visit' =
			
			CALCULATE (
			    COUNTROWS ( 'vwScheduleVisitDetails' ),
			    'vwScheduleVisitDetails'[VisitStatusID] IN { 4, 7} ,
			    vwScheduleVisitDetails[VisitTypeID] <> 716,
			    vwScheduleVisitDetails[NextAppt] = BLANK()
			    --vwResourceDetails[ProviderCategoryID] IN {1,3},
			
			)
		formatString: 0
		displayFolder: _Daily Operations
		lineageTag: 749af1c2-dbfb-4aec-8869-eaf16354f409

	measure Goal_Encounter = SUM( 'cfgProvSched'[Appts] )
		displayFolder: _Encounters
		lineageTag: af318b87-8632-435a-8b50-ae3b060351b7

	measure 'Visits | Goal' = ```
			IF (
			        [Goal_Encounter] = BLANK() && [Visits_Full Encounter] = BLANK()
			        ,BLANK()
			        ,IF(
			            [Goal_Encounter] = BLANK()
			            ,FORMAT([Visits_Full Encounter],"#,0") & " | " 
			            ,FORMAT([Visits_Full Encounter],"#,0") & " | " & FORMAT([Goal_Encounter],"#,0")
			        )
			    )
			    
			```
		displayFolder: _Encounters
		lineageTag: e32fec50-4a0f-48ad-9751-72a8dee4b530

	measure Color_text = ```
			IF ( 
			    [Visits_Full Encounter] >= SUM ( 'cfgProvSched'[Appts] ), 
			    "Green"
			    , "Red" 
			    )
			```
		displayFolder: _Encounters
		lineageTag: f60d340d-0b81-415e-9825-fa9c4d4cfac3

	measure 'Daily Leads Budget' = SUM(vwLeadIntakeDashboard[DailyLeadsReqd])
		formatString: #,0
		displayFolder: _LeadsIntakes
		lineageTag: 341aacfa-7c09-4fc3-ad05-39679f6187b6

	measure 'Daily Leads Actual' = SUM(vwLeadIntakeDashboard[NumLeads])
		formatString: #,0
		displayFolder: _LeadsIntakes
		lineageTag: d8819d56-5baa-4ea3-92eb-687b3f2714c8

	measure 'Daily Intakes Actual' = SUM(vwLeadIntakeDashboard[NumIntakes])
		formatString: #,0
		displayFolder: _LeadsIntakes
		lineageTag: 3a185cb6-4c6a-4836-95e4-0d5b2da5d1bb

	measure 'Daily Intakes Budget' = SUM(vwLeadIntakeDashboard[DailyIntakesReqd])
		formatString: #,0
		displayFolder: _LeadsIntakes
		lineageTag: 8592fac8-e15e-4e47-b926-46ba561da4e1

	measure 'Monthly Cumulative Intakes Budget' =
			
			VAR BeginPeriod =
			    IF (
			        SELECTEDVALUE ( dimDate[Slicer Month] ) = "Current Month",
			        DATE( YEAR( TODAY() ), MONTH ( TODAY() ), "01"),
			        DATE( YEAR( SELECTEDVALUE ( dimDate[Slicer Month] ) ), MONTH( SELECTEDVALUE( dimDate[Slicer Month] ) ), "01" )
			    )
			RETURN
			    CALCULATE (
			        [Daily Intakes Budget],
			        FILTER (
			            ALL ( 'dimDate'[Date] ),
			            AND (
			                'dimDate'[Date] <= MAX ( 'dimDate'[Date] ),
			                'dimDate'[Date] >= BeginPeriod
			            )
			        )
			    )
		formatString: #,0
		displayFolder: _LeadsIntakes
		lineageTag: ff0e4646-da1e-4aa8-b7d9-48ff4e74ad93

	measure 'Monthly Cumulative Intakes Actual' =
			
			VAR BeginPeriod =
			    IF (
			        SELECTEDVALUE ( dimDate[Slicer Month] ) = "Current Month",
			        DATE( YEAR( TODAY() ), MONTH ( TODAY() ), "01"),
			        DATE( YEAR( SELECTEDVALUE ( dimDate[Slicer Month] ) ), MONTH( SELECTEDVALUE( dimDate[Slicer Month] ) ), "01" )
			    )
			RETURN
			    CALCULATE (
			        [Daily Intakes Actual],
			        FILTER (
			            ALL ( 'dimDate'[Date] ),
			            AND (
			                'dimDate'[Date] <= MAX ( 'dimDate'[Date] ),
			                'dimDate'[Date] >= BeginPeriod
			            )
			        )
			    )
		formatString: #,0
		displayFolder: _LeadsIntakes
		lineageTag: 3ad6f318-8444-485b-9979-112b7aaa39bc

	measure 'Monthly Cumulative Leads Budget' =
			
			VAR BeginPeriod =
			    IF (
			        SELECTEDVALUE ( dimDate[Slicer Month] ) = "Current Month",
			        DATE( YEAR( TODAY() ), MONTH ( TODAY() ), "01"),
			        DATE( YEAR( SELECTEDVALUE ( dimDate[Slicer Month] ) ), MONTH( SELECTEDVALUE( dimDate[Slicer Month] ) ), "01" )
			    )
			RETURN
			    CALCULATE (
			        [Daily Leads Budget],
			        FILTER (
			            ALL ( 'dimDate'[Date] ),
			            AND (
			                'dimDate'[Date] <= MAX ( 'dimDate'[Date] ),
			                'dimDate'[Date] >= BeginPeriod
			            )
			        )
			    )
		formatString: #,0
		displayFolder: _LeadsIntakes
		lineageTag: 69072cff-09b0-4770-94c9-5c9a2948458e

	measure 'Monthly Cumulative Leads Actual' =
			
			VAR BeginPeriod =
			    IF (
			        SELECTEDVALUE ( dimDate[Slicer Month] ) = "Current Month",
			        DATE( YEAR( TODAY() ), MONTH ( TODAY() ), "01"),
			        DATE( YEAR( SELECTEDVALUE ( dimDate[Slicer Month] ) ), MONTH( SELECTEDVALUE( dimDate[Slicer Month] ) ), "01" )
			    )
			RETURN
			    CALCULATE (
			        [Daily Leads Actual],
			        FILTER (
			            ALL ( 'dimDate'[Date] ),
			            AND (
			                'dimDate'[Date] <= MAX ( 'dimDate'[Date] ),
			                'dimDate'[Date] >= BeginPeriod
			            )
			        )
			    )
		formatString: #,0
		displayFolder: _LeadsIntakes
		lineageTag: 7dedec41-13f7-40b0-bf3a-f17ac5c079d0

	measure 'Monthly Intakes Budget' = ```
			
			VAR BeginPeriod =
			    IF (
			        SELECTEDVALUE ( dimDate[Slicer Month] ) = "Current Month",
			        DATE( YEAR( TODAY() ), MONTH ( TODAY() ), "01"),
			        DATE( YEAR( SELECTEDVALUE ( dimDate[Slicer Month] ) ), MONTH( SELECTEDVALUE( dimDate[Slicer Month] ) ), "01" )
			    )
			RETURN 
			    CALCULATE(
			        SUM(vwLeadIntakeDashboard[IntakesReqd])
			        ,vwLeadIntakeDashboard[MonthDate] = BeginPeriod
			    )
			```
		formatString: #,0
		displayFolder: _LeadsIntakes
		lineageTag: 689a0173-5cf0-497e-abaa-eebcb5ce1bc2

	measure 'Monthly Leads Budget' = ```
			
			VAR BeginPeriod =
			    IF (
			        SELECTEDVALUE ( dimDate[Slicer Month] ) = "Current Month",
			        DATE( YEAR( TODAY() ), MONTH ( TODAY() ), "01"),
			        DATE( YEAR( SELECTEDVALUE ( dimDate[Slicer Month] ) ), MONTH( SELECTEDVALUE( dimDate[Slicer Month] ) ), "01" )
			    )
			RETURN 
			    CALCULATE(
			        SUM(vwLeadIntakeDashboard[LeadsReqd])
			        ,vwLeadIntakeDashboard[MonthDate] = BeginPeriod
			    )
			```
		formatString: #,0
		displayFolder: _LeadsIntakes
		lineageTag: 5add0f6c-643c-473e-bf07-db4da6d6012f

	measure 'Weight LIA - MTD' = ```
			
			VAR CurrentMonth =
			    IF (
			        SELECTEDVALUE ( dimDate[Slicer Month] ) = "Current Month",
			        FORMAT ( TODAY()-1, "YYYY-MM-DD" ),
			        FORMAT ( EOMONTH ( SELECTEDVALUE ( dimDate[Slicer Month] ), 0 ), "YYYY-MM-DD" )
			    )
			    
			RETURN 
			    CALCULATE(
			        SUM('vwLeadIntakeDashboard'[MtdCumWeight]),
			        vwLeadIntakeDashboard[MonthDate] = DATEVALUE(CurrentMonth)
			    )
			```
		displayFolder: _LeadsIntakes
		lineageTag: 5d87fcd1-b0ff-4384-bee2-bcc8c8b5b11e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Leads %' = [Daily Leads Actual] / [Daily Leads Budget]
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: _LeadsIntakes
		lineageTag: d6d1b8ca-c851-422a-bd0b-e0f767d64b7c

	measure 'Intakes %' = [Daily Intakes Actual] / [Daily Intakes Budget]
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: _LeadsIntakes
		lineageTag: 5a63501a-6faa-4fcd-8349-022f7a83a20f

	measure 'MTD Intakes %' = [Monthly Cumulative Intakes Actual] / [Monthly Cumulative Intakes Budget]
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: _LeadsIntakes
		lineageTag: 2fe34538-c253-4440-9f34-410b714d2112

	measure 'MTD Leads %' = [Monthly Cumulative Leads Actual] / [Monthly Cumulative Leads Budget]
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: _LeadsIntakes
		lineageTag: fd76f82a-de65-4f4c-943b-905aaed16e0e

	measure '# Cancel Visits' = ```
			
			    SUM(vwDailySales[CancelVis])
			```
		formatString: #,0
		displayFolder: _Finance
		lineageTag: 2297bd17-81f5-4f5f-8ee1-58d32e4c6159

		changedProperty = FormatString

	measure '# Cancel Visits - Comb' = ```
			
			    SUM(vwDailySalesCombined[CancelVis])
			```
		formatString: #,0
		displayFolder: _Finance
		lineageTag: 44ddeea7-f7b2-4c4d-96b4-f5d730c5b437

	measure '# Completed - FU Patient - Psy' = ```
			
			    SUM(vwDailySales[PsyFupVis])
			```
		formatString: #,0
		displayFolder: _Finance
		lineageTag: 6e24e2d6-c661-4988-a55f-c2a1077d1784

		changedProperty = FormatString

	measure '# Completed - FU Patient - Psy - Comb' = ```
			
			    SUM(vwDailySalesCombined[PsyFupVis])
			```
		formatString: #,0
		displayFolder: _Finance
		lineageTag: d0548f79-7c20-478d-8350-25b9657384a7

	measure '# Completed - FU Patient - Th' = ```
			
			    SUM(vwDailySales[ThrFupVis])
			```
		formatString: #,0
		displayFolder: _Finance
		lineageTag: c25a2153-9265-4a61-8757-d024316f2258

		changedProperty = FormatString

	measure '# Completed - FU Patient - Th - Comb' = ```
			
			    SUM(vwDailySalesCombined[ThrFupVis])
			```
		formatString: #,0
		displayFolder: _Finance
		lineageTag: 3f0696d7-78af-4eca-b627-6f43271baf21

	measure '# Completed - Intake - Psy' = ```
			
			    SUM(vwDailySales[PsyIntVis])
			```
		formatString: #,0
		displayFolder: _Finance
		lineageTag: e9b39f60-1564-4891-ab88-9d39a056a310

		changedProperty = FormatString

	measure '# Completed - Intake - Psy - Comb' = ```
			
			    SUM(vwDailySalesCombined[PsyIntVis])
			```
		formatString: #,0
		displayFolder: _Finance
		lineageTag: 5097a18c-c7e2-486c-b1c3-577511cf07b0

	measure '# Completed - Intake - Th' = ```
			
			    SUM(vwDailySales[ThrIntVis])
			```
		formatString: #,0
		displayFolder: _Finance
		lineageTag: 97006113-9611-421c-9cbb-d97d3077be86

		changedProperty = FormatString

	measure '# Completed - Intake - Th - Comb' = ```
			
			    SUM(vwDailySalesCombined[ThrIntVis])
			```
		formatString: #,0
		displayFolder: _Finance
		lineageTag: 54c55e96-b8d2-495a-9285-1b726cbaaeae

	measure '# Completed - Total' =
			[# Completed - FU Patient - Psy] +
			[# Completed - FU Patient - Th] +
			[# Completed - Intake - Psy] +
			[# Completed - Intake - Th]
		formatString: #,0
		displayFolder: _Finance
		lineageTag: 385aff74-8a5a-4801-821a-87eb223e342b

		changedProperty = FormatString

	measure '# Completed - Total - Comb' =
			[# Completed - FU Patient - Psy - Comb] +
			[# Completed - FU Patient - Th - Comb] +
			[# Completed - Intake - Psy - Comb] +
			[# Completed - Intake - Th - Comb]
		formatString: #,0
		displayFolder: _Finance
		lineageTag: 82769dbf-85a8-40fe-9f77-6ddf3ebc7e76

	measure '# No Show Visits' = ```
			
			VAR _resu = SUM(vwDailySales[NoShowVis])
			RETURN 
			    IF( _resu = 0, BLANK(), _resu)
			```
		formatString: #,0
		displayFolder: _Finance
		lineageTag: c79c3a1c-f2b1-4a77-9c89-e2a637eaf970

		changedProperty = IsHidden

	measure '# No Show Visits - Comb' = ```
			
			    SUM(vwDailySalesCombined[NoShowVis])
			```
		formatString: #,0
		displayFolder: _Finance
		lineageTag: 29835a1c-072f-4e0e-9ae5-4c2a2693d987

	measure Budget = ```
			
			var _resu =  
			    CALCULATE(        
			    SUM(cfgDailyBudget[DayVisComp]),        
			    cfgDailyBudget[BudgetType] = "V",        
			    cfgDailyBudget[ProviderCategory] = "Total",            
			    cfgDailyBudget[VisitType] = "Total" 
			    )
			
			RETURN 
			    IF( 
			        _resu = 0 ,
			        BLANK(),
			        _resu
			    )
			
			```
		formatString: #,0
		displayFolder: _Finance
		lineageTag: f71e0e09-b6ff-49b4-b38d-174d4847d839

		changedProperty = FormatString

	measure 'Budget NoShow' = ```
			
			VAR _resu =  
			    CALCULATE(        
			    SUM(cfgDailyBudget[DayVisNoShow]),        
			    cfgDailyBudget[BudgetType] = "V",        
			    cfgDailyBudget[ProviderCategory] = "Total",        
			    cfgDailyBudget[VisitType] = "Total"
			    )
			RETURN
			    IF( 
			        _resu = 0 , 
			        BLANK(),
			        _resu
			    )
			```
		formatString: #,0
		displayFolder: _Finance
		lineageTag: 95ad40e0-800b-4706-8c4c-a1739690676f

	measure 'Monthly - Cumulative Revenue' = ```
			
			VAR BeginPeriod =
			    IF (
			        SELECTEDVALUE ( dimDate[Slicer Month] ) = "Current Month",
			        DATE( YEAR( TODAY() ), MONTH ( TODAY() ), "01"),
			        DATE( YEAR( SELECTEDVALUE ( dimDate[Slicer Month] ) ), MONTH( SELECTEDVALUE( dimDate[Slicer Month] ) ), "01" )
			    )
			VAR _resu =
			    CALCULATE (
			        [Revenue Visits - Total],
			        FILTER (
			            
			            ALL ( 'dimDate'[Date] ),
			            AND (
			                'dimDate'[Date] <= MAX ( 'dimDate'[Date] ),
			                'dimDate'[Date] >= BeginPeriod
			            )
			        )
			    )
			
			RETURN 
			    IF( [# Completed - Total] = BLANK(), BLANK(), _resu )
			```
		formatString: #,0
		displayFolder: _Finance
		lineageTag: e9333b90-64ff-4e02-9acc-80401ad3c675

		changedProperty = FormatString

	measure Projection =
			
			[Monthly - Cumulative Revenue] / [Monthly - Cumulative Budget] *
			[Revenue - Recast Monthly For Table]
		formatString: #,0
		displayFolder: _Finance
		lineageTag: 3d9904bb-5565-460c-a38d-abbe5396b4f7

		changedProperty = FormatString

	measure 'Projection By Facility' =
			
			[Monthly - Cumulative Revenue] / [Revenue Recast Total - MTD] *
			[Revenue - Recast Monthly For Table]
		formatString: #,0
		displayFolder: _Finance
		lineageTag: 70f6da15-9b07-4461-b929-bc4f0886f99e

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Revenue - No Show' = ```
			
			--SUM(
			--    cfgRevenueVisits[Revenue No Show]
			--)
			
			var _selectedMonth =
			IF (
			    SELECTEDVALUE ( dimDate[Slicer Month] ) = "Current Month",
			    FORMAT ( 
			        EOMONTH( TODAY(), 0 ), "YYYY-MM-DD" ),
			    FORMAT ( 
			        EOMONTH ( SELECTEDVALUE ( dimDate[Slicer Month] ), 0 ), "YYYY-MM-DD" )
			)
			    
			RETURN 
			CALCULATE(
			    SUM(cfgRevenueVisits[Revenue No Show]) ,
			    AND(
			        DATEVALUE(_selectedMonth) > cfgRevenueVisits[FromDate],
			        DATEVALUE(_selectedMonth) <= cfgRevenueVisits[ThruDate]
			    )
			)
			```
		formatString: #,0
		displayFolder: _Finance
		lineageTag: 4732db7b-ee3a-496a-9e66-a761239bdf72

	measure 'Revenue - Recast Monthly' =
			
			VAR CurrentMonth =
			    IF (
			        SELECTEDVALUE ( dimDate[Slicer Month] ) = "Current Month",
			        FORMAT ( EOMONTH ( TODAY (), 0 ), "YYYY-MM-DD" ),
			        FORMAT ( EOMONTH ( SELECTEDVALUE ( dimDate[Slicer Month] ), 0 ), "YYYY-MM-DD" )
			    )
			RETURN
			    CALCULATE (
			        SUM ( cfgDailyBudget[MtdRevenue] ),
			        FILTER (
			            'cfgDailyBudget',
			            cfgDailyBudget[MonthDate] = DATEVALUE ( CurrentMonth )
			        ),
			        cfgDailyBudget[BudgetType] = "R",
			        cfgDailyBudget[FacilityName] <> "All Locations",
			        cfgDailyBudget[ProviderCategory] = "Total"
			        --cfgDailyBudget[Market] = "CO"
			    )
		formatString: #,0
		displayFolder: _Finance
		lineageTag: 075c0848-bc59-4023-a378-4e3bda6c4e65

	measure 'Revenue NoShow - Total' = ```
			
			    SUM(vwDailySales[NoShowRev])
			```
		formatString: #,0
		displayFolder: _Finance
		lineageTag: 0e94f975-6d7a-4654-a9c4-8648adaa8332

	measure 'Revenue NoShow - Total - Comb' = ```
			
			    SUM(vwDailySalesCombined[NoShowRev])
			```
		formatString: #,0
		displayFolder: _Finance
		lineageTag: ccc6a631-9e65-4054-8243-85c2c6e843eb

	measure 'Revenue Recast -Total' = ```
			
			VAR _resu =
			    CALCULATE (
			        SUM ( cfgDailyBudget[DayRevenue] ),
			        cfgDailyBudget[BudgetType] = "R",
			        cfgDailyBudget[ProviderCategory] = "Total"
			    )
			RETURN
			    IF(
			        _resu = 0, 
			        BLANK(),
			        _resu
			    )
			```
		formatString: #,0
		displayFolder: _Finance
		lineageTag: e1b9a4cb-e961-407f-af6c-91d069a959ac

		changedProperty = FormatString

	measure 'Revenue Recast Total - MTD' = ```
			
			VAR CurrentMonth =
			    IF (
			        SELECTEDVALUE ( dimDate[Slicer Month] ) = "Current Month",
			        FORMAT ( TODAY() -1 , "YYYY-MM-DD" ),
			        FORMAT ( EOMONTH ( SELECTEDVALUE ( dimDate[Slicer Month] ), 0 ), "YYYY-MM-DD" )
			    )
			    
			RETURN 
			    CALCULATE(
			        SUM('cfgDailyBudget'[MtdRevenue]),
			        cfgDailyBudget[BudgetType] = "R",
			        cfgDailyBudget[ProviderCategory] = "Total",
			        --cfgDailyBudget[FacilityName] = "CO - Cherry Creek"
			        cfgDailyBudget[MonthDate] = DATEVALUE(CurrentMonth)
			    )
			```
		formatString: #,0
		displayFolder: _Finance
		lineageTag: 4fc0dc3d-e4dd-44ec-b577-b20c55da0d11

	measure 'Revenue Visits - Total' = ```
			
			SUM(vwDailySales[PsyFupRev]) + SUM(vwDailySales[PsyIntRev]) + SUM(vwDailySales[ThrFupRev]) + SUM(vwDailySales[ThrIntRev])
			   
			```
		formatString: #,0
		displayFolder: _Finance
		lineageTag: 4fd16e6c-21f5-4636-ba6e-b5899bb5cbff

		changedProperty = FormatString

	measure 'Revenue Visits - Total - Comb' = ```
			
			    SUM(vwDailySalesCombined[PsyFupRev]) + SUM(vwDailySalesCombined[PsyIntRev]) + SUM(vwDailySalesCombined[ThrFupRev]) + SUM(vwDailySalesCombined[ThrIntRev])
			```
		formatString: #,0
		displayFolder: _Finance
		lineageTag: 5c9b9db1-b22a-43d0-a27b-47f4a782bbb2

	measure 'Var - Visit vs Budget' = ```
			
			    [# Completed - Total] - [Budget]
			```
		formatString: #,0
		displayFolder: _Finance
		lineageTag: b4941f27-501c-41ef-84f5-4294fe82c4e9

		changedProperty = FormatString

	measure 'Var - Visit vs Budget - Comb' = ```
			
			    [# Completed - Total - Comb] - [Budget]
			```
		formatString: #,0
		displayFolder: _Finance
		lineageTag: 3de6733d-20b1-49fa-b28a-4e8565cb9cee

	measure 'Weight - Daily' = ```
			
			    IF(
			        SUM(cfgWeekDayWts[WeekDayWeight]) = 0 , 
			        BLANK(), 
			        SUM(cfgWeekDayWts[WeekDayWeight]) 
			    )
			```
		displayFolder: _Finance
		lineageTag: d8fd6b6d-74f4-4cc3-84b2-ec5f0b08563c

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Weight - MTD' = ```
			
			--SUM(cfgWeekDayWts[MtdCumWeight])
			VAR CurrentMonth =
			    IF (
			        SELECTEDVALUE ( dimDate[Slicer Month] ) = "Current Month",
			        FORMAT ( TODAY()-1, "YYYY-MM-DD" ),
			        FORMAT ( EOMONTH ( SELECTEDVALUE ( dimDate[Slicer Month] ), 0 ), "YYYY-MM-DD" )
			    )
			    
			RETURN 
			    CALCULATE(
			        SUM('cfgWeekDayWts'[MtdCumWeight]),
			        cfgWeekDayWts[MonthDate] = DATEVALUE(CurrentMonth)
			    )
			```
		formatString: 0.00
		displayFolder: _Finance
		lineageTag: 15f1745f-a3f5-4eb1-b7e2-ed4c0841aa6f

	measure 'Monthly - Cumulative Budget' = ```
			
			VAR BeginPeriod =
			    IF (
			        SELECTEDVALUE ( dimDate[Slicer Month] ) = "Current Month",
			        DATE( YEAR( TODAY() ), MONTH ( TODAY() ), "01" ),
			        DATE( YEAR( SELECTEDVALUE ( dimDate[Slicer Month] ) ), MONTH( SELECTEDVALUE( dimDate[Slicer Month] ) ), "01" )
			    )
			VAR _resu = 
			    CALCULATE (
			        [Revenue Recast -Total],
			        FILTER (
			            ALL ( 'dimDate'[Date] ),
			            AND (
			                'dimDate'[Date] <= MAX ( 'dimDate'[Date] ),
			                'dimDate'[Date] >= BeginPeriod
			            )
			        )
			    )
			
			RETURN 
			    IF( [# Completed - Total] = BLANK(), BLANK(), _resu)
			```
		formatString: #,0
		displayFolder: _Finance
		lineageTag: 580e6578-4e64-4b9b-9122-c52e310430e9

		changedProperty = FormatString

	measure _dateFilter = ```
			
			VAR _selectedDate = SELECTEDVALUE(dimDate[Date])
			RETURN 
			    IF(_selectedDate < TODAY(), 1, 0)
			```
		formatString: 0
		displayFolder: _Finance
		lineageTag: 19073401-37ea-479d-a9e4-274944e0a4c3

	measure Actual =
			
			CALCULATE(
			    SUM(vwAccountDetails[EndBalv2]),
			    cfgAccountingReport[PNL_BUDGET_ACTUAL_PARENT] <> "N/A"
			    )
		formatString: #,0
		displayFolder: _AccountDetails
		lineageTag: 3decc2c5-e7c8-46fd-b33f-cdacd8f699eb

	measure COGS =
			
			CALCULATE(
			    SUM(vwAccountDetails[EndBalv2]),
			    cfgAccountingReport[PNL_BUDGET_ACTUAL_PARENT] = "COGS"
			    )
		formatString: #,0
		displayFolder: _AccountDetails\2.COGS
		lineageTag: ccbd9476-558f-48fe-b408-798288937e2d

	measure '5000 - COGS - Psychiatric Salaries' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "5000 - COGS - Psychiatric Salaries" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\2.COGS
		lineageTag: ba6e7322-6f3a-4878-9fb8-729460d36642

	measure '5010 - COGS - Psychiatric Bonus' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "5010 - COGS - Psychiatric Bonus" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\2.COGS
		lineageTag: 5df3e9ae-95f8-4c57-8fb2-2ac61ea4f0e7

	measure '5020 - COGS - Psychiatric Contract Labor' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "5020 - COGS - Psychiatric Contract Labor" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\2.COGS
		lineageTag: 36a98c08-3ae3-4b1b-bf57-c79aa295919f

	measure '5030 - COGS - Psychiatric Payroll Taxes' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "5030 - COGS - Psychiatric Payroll Taxes" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\2.COGS
		lineageTag: 370aa52a-fe4c-4512-9b81-2f7b95687ae4

	measure '5040 - COGS - Psychiatric PTO' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "5040 - COGS - Psychiatric PTO" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\2.COGS
		lineageTag: 4294bb34-b87e-414e-877b-38a3c6c64cc6

	measure '5080 - COGS - Psychiatric Workers'' Compensation' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "5080 - COGS - Psychiatric Workers' Compensation" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\2.COGS
		lineageTag: ae204574-1c77-4544-8985-68504b8e1193

	measure '5120 - COGS - Therapy Contract Labor' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "5120 - COGS - Therapy Contract Labor" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\2.COGS
		lineageTag: d06a54c6-36b1-48e0-b9c2-8da4822f5cdf

	measure '5170 - COGS - Therapy Disability Insurance' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "5170 - COGS - Therapy Disability Insurance" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\2.COGS
		lineageTag: 2b7df037-3eec-4cbd-bf53-b0c2fc448e9a

	measure '5050 - COGS - Psychiatric 401(k) Employer Match' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "5050 - COGS - Psychiatric 401(k) Employer Match" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\2.COGS
		lineageTag: 901369c9-9f33-4b9a-bcaf-7b622acd679e

	measure '5065 - COGS - Psychiatric Dental/Vision Insurance' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "5065 - COGS - Psychiatric Dental/Vision Insurance" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\2.COGS
		lineageTag: b775ecc8-e0a4-4b63-a9f2-1817bd8d2efb

	measure '5091 - COGS - Psychiatric Hospital Benefit' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "5091 - COGS - Psychiatric Hospital Benefit" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\2.COGS
		lineageTag: 952caaf2-4eac-4d7e-a6e6-efd757149170

	measure '5094 - COGS - Psychiatric Adcident Benefit' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "5094 - COGS - Psychiatric Adcident Benefit" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\2.COGS
		lineageTag: 83ab05b0-94d4-466d-848f-8410a0e45b87

	measure '5130 - COGS - Therapy Payroll Taxes' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "5130 - COGS - Therapy Payroll Taxes" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\2.COGS
		lineageTag: 2d7544d0-9a38-4242-825e-1757bfbfad1c

	measure '5155 - COGS - Therapy HSA Employer Contribution' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "5155 - COGS - Therapy HSA Employer Contribution" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\2.COGS
		lineageTag: 76d9d230-97c3-4ef0-bab2-d52abee521cc

	measure '5175 - COGS - Therapy Life Insurance' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "5175 - COGS - Therapy Life Insurance" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\2.COGS
		lineageTag: 5bee5e58-e01f-4d6e-92f8-bb11378ac46f

	measure '5192 - COGS - Therapy Critical Illness Benefit' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "5192 - COGS - Therapy Critical Illness Benefit" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\2.COGS
		lineageTag: 6e321221-2388-40f7-9e5f-a577d626853a

	measure '5060 - COGS - Psychiatric Health Insurance' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "5060 - COGS - Psychiatric Health Insurance" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\2.COGS
		lineageTag: 436102e8-3f18-4a1a-9738-42a9c6f7b925

	measure '5070 - COGS - Psychiatric Disability Insurance' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "5070 - COGS - Psychiatric Disability Insurance" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\2.COGS
		lineageTag: 8b20a76a-8aba-4a0c-9c44-b10c5d8e27ee

	measure '5055 - COGS - Psychiatric HSA Employer Contribution' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "5055 - COGS - Psychiatric HSA Employer Contribution" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\2.COGS
		lineageTag: 849131d5-af02-44d8-a7cc-637dbf0cfbd9

	measure '5075 - COGS - Psychiatric Life Insurance' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "5075 - COGS - Psychiatric Life Insurance" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\2.COGS
		lineageTag: ed0f5a15-a50d-46ba-a31a-c3a17f463255

	measure '5093 - COGS - Psychiatric COBRA Benefit' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "5093 - COGS - Psychiatric COBRA Benefit" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\2.COGS
		lineageTag: 3b94510a-448b-43e8-bdbc-b2a33fbf3082

	measure '5100 - COGS - Therapy Salaries' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "5100 - COGS - Therapy Salaries" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\2.COGS
		lineageTag: 005ceafb-539d-4b7f-b3cd-cafc3ed72f49

	measure '5092 - COGS - Psychiatric Critical Illness Benefit' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "5092 - COGS - Psychiatric Critical Illness Benefit" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\2.COGS
		lineageTag: cdb60af2-fc95-4aba-a36d-7d0e4623a991

	measure '5110 - COGS - Therapy Bonus' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "5110 - COGS - Therapy Bonus"
			   
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\2.COGS
		lineageTag: 7819b48d-94bb-4a64-8355-31bd5d09ec3f

	measure '5150 - COGS - Therapy 401(k) Employer Match' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "5150 - COGS - Therapy 401(k) Employer Match" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\2.COGS
		lineageTag: 63278537-7e9d-486d-86e0-55b6c9625f46

	measure '5160 - COGS - Therapy Health Insurance' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "5160 - COGS - Therapy Health Insurance" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\2.COGS
		lineageTag: d9712685-644d-4849-9eb2-c2e753358fca

	measure '5140 - COGS - Therapy PTO' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "5140 - COGS - Therapy PTO" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\2.COGS
		lineageTag: 47e2a7aa-ed0b-4c1e-9ddc-48afa075950c

	measure '5165 - COGS - Therapy Dental/Vision Insurance' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "5165 - COGS - Therapy Dental/Vision Insurance" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\2.COGS
		lineageTag: 1aec8a2b-6d2c-46dc-8b61-8c223e9349c2

	measure '5191 - COGS - Therapy Hospital Benefit' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "5191 - COGS - Therapy Hospital Benefit" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\2.COGS
		lineageTag: aef6247e-72c5-4ae7-b429-133af6e0d14a

	measure '5193 - COGS - Therapy COBRA Benefit' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "5193 - COGS - Therapy COBRA Benefit" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\2.COGS
		lineageTag: 5619aa65-4dd2-4a23-9552-56c00f3640fd

	measure '5180 - COGS - Therapy Workers'' Compensation' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "5180 - COGS - Therapy Workers' Compensation" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\2.COGS
		lineageTag: f8054c3e-ce85-4fe6-a9e0-4532a20bdee4

	measure '5194 - COGS - Therapy Accident Benefit' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "5194 - COGS - Therapy Accident Benefit" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\2.COGS
		lineageTag: 89790833-2fa4-45d1-8c26-449b701b09fb

	measure '5195 - COGS - Therapy Other Benefits' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "5195 - COGS - Therapy Other Benefits" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\2.COGS
		lineageTag: 769b0f99-14b8-424a-b00a-2a6e6ae8fa70

	measure '5095 - COGS - Psychiatric Other Benefits' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "5095 - COGS - Psychiatric Other Benefits" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\2.COGS
		lineageTag: 783c5fba-ca02-402e-a245-4d10713cb6e3

	measure '# Checkin Visits' = ```
			
			CALCULATE (
			    COUNTROWS ('vwScheduleVisitDetails'),    
			    FILTER (  'vwScheduleVisitDetails', [VisitStatusID] in { 1 }  ),
			    NOT( vwScheduleVisitDetails[VisitTypeID] = 716 )
			    --,USERELATIONSHIP( vwScheduleVisitDetails[ResourceID], vwResourceDetails[ResourceId])
			    --,USERELATIONSHIP( vwScheduleVisitDetails[FacilityID], vwFacilitiesMaster[FacilityId])
			)
			```
		formatString: #,0
		displayFolder: _Ops One Page\_Complement measures
		lineageTag: 3a570c05-0a7d-4ef8-ad0f-9f2e302fe5f7

		changedProperty = FormatString

	measure '# Checkout Visits' =
			
			CALCULATE (
			    COUNTROWS ( 'vwScheduleVisitDetails' ),
			    FILTER ( 'vwScheduleVisitDetails', [VisitStatusID] IN { 2 } ),
			    NOT ( vwScheduleVisitDetails[VisitTypeID] = 716 )
			    --,USERELATIONSHIP ( vwScheduleVisitDetails[ResourceID], vwResourceDetails[ResourceId] )
			    --,USERELATIONSHIP ( vwScheduleVisitDetails[FacilityID], vwFacilitiesMaster[FacilityId] )
			)
		formatString: 0
		displayFolder: _Ops One Page\_Complement measures
		lineageTag: ed551a96-34ce-4670-8693-b4a2351b1c5c

		changedProperty = FormatString

	measure Hours =
			
			SUM(
			    vwSummaryUtilizationByResource[Hours])
		displayFolder: _Ops One Page\_Complement measures
		lineageTag: 67c7c5ce-2c1f-4d4f-93a3-d968f4b8f81e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Objective =
			
			SUM(
			    vwSummaryUtilizationByResource[Goal])
		displayFolder: _Ops One Page\_Complement measures
		lineageTag: 6ea800f5-c472-49c3-a14c-4d24b21f1687

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '# Completed Visits' = ```
			
			[# Checkout Visits] 
			+ 
			[# Checkin Visits]
			```
		formatString: #,0
		displayFolder: _Ops One Page
		lineageTag: 45705a78-e630-4efe-907c-5498a13e6018

		changedProperty = FormatString

	measure '% utilization' = [Hours] / [Objective]
		formatString: 0\ %;-0\ %;0\ %
		displayFolder: _Ops One Page
		lineageTag: 7573b3f1-bdbc-45a4-82c6-bec9136a3462

		changedProperty = FormatString

	measure Clinician_Selected = SELECTEDVALUE(vwResourceDetails[Full Name])
		displayFolder: _Ops One Page
		lineageTag: 255217de-d933-44f4-b301-d82c0d2dab1f

	measure 'Goal (Completed)' =
			
			CALCULATE (
			    SUM ( vwSummaryUtilSchdByResource[Goal] ),
			    vwSummaryUtilSchdByResource[VisitDate] <= TODAY ()
			)
		formatString: #,0.00
		displayFolder: _Ops One Page
		lineageTag: 4f8fb308-1de8-42f9-9445-6018eec1741f

	measure 'Goal (Scheduled)' =
			
			CALCULATE (
			    SUM ( vwSummaryUtilSchdByResource[Goal] ),
			    vwSummaryUtilSchdByResource[VisitDate] > ( TODAY () )
			)
		formatString: #,0.00
		displayFolder: _Ops One Page
		lineageTag: 4aef66e2-7b81-41f5-bf08-4d6a9ca35c36

	measure 'MaxScale Completed_Appointment_by_Loc' =
			
			CALCULATE(
			    MAXX(
			        VALUES(
			            '2_Date_Expander'[Name]
			        )
			        ,[# Completed Visits]
			    )
			    ,vwProviderCategory[ProviderCategory] <> "Psychiatric"
			    , ALLSELECTED(dimDate)
			) * 1.2
		displayFolder: _Ops One Page
		lineageTag: 7a53f0c3-aa58-415a-a95a-9778e9491fda

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MaxScale_Auto =
			
			CALCULATE(
			    MAXX(
			        VALUES(
			            '2_Date_Expander'[Name]
			        )
			        ,[Goal (Completed)]
			    )
			    ,vwSummaryUtilSchdByResource[ProviderCategory] <> "Psychiatric"
			    , ALLSELECTED(dimDate)
			) * 1.2
		displayFolder: _Ops One Page
		lineageTag: 3456f20c-7605-4f92-8237-7717df218384

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '4000 - Therapy Revenue' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "4000 - Therapy Revenue" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\1.Revenue
		lineageTag: 3798f031-99a0-41f2-b373-9ad87b285ba3

	measure '4100 - Psychiatric Revenue' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "4100 - Psychiatric Revenue" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\1.Revenue
		lineageTag: b6194beb-2e83-4aea-8434-91af5321604d

	measure '4800 - Psychiatric Contractuals Expense' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "4800 - Psychiatric Contractuals Expense" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\1.Revenue
		lineageTag: 253d6334-2c3c-4950-8757-169999d913b7

	measure '4900 - Therapy Contractuals Expense' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "4900 - Therapy Contractuals Expense" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\1.Revenue
		lineageTag: 90dcffa8-c03d-464c-b706-aed225ef5d8b

	measure '4940 - Therapy Patient Credit Refunds' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "4940 - Therapy Patient Credit Refunds" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\1.Revenue
		lineageTag: 2bd884dd-c3ce-42ab-a38b-003e131d4f29

	measure '4840 - Psychiatric Patient Credit Refunds' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "4840 - Psychiatric Patient Credit Refunds" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\1.Revenue
		lineageTag: 937ed241-7296-44e0-9192-63ec96ee3e19

	measure '6010 - Bonus' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6010 - Bonus" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: 3212a45f-c1d9-48ae-8678-31443a50cc2e

	measure Revenue_Total =
			
			CALCULATE(
			    SUM(vwAccountDetails[EndBalv2]),
			    cfgAccountingReport[PNL_BUDGET_ACTUAL_PARENT] = "Revenue"
			    )
		formatString: #,0
		displayFolder: _AccountDetails\1.Revenue
		lineageTag: 1365953a-b6f0-494e-9a34-92c6e8a70ae8

	measure Total_GrossProfit = [Revenue_Total] + [COGS]
		formatString: #,0
		displayFolder: _AccountDetails
		lineageTag: d6f9e334-f2a7-48d8-a007-e9102dc28fbe

	measure OperatingExpensesTotal =
			
			CALCULATE(
			    SUM(vwAccountDetails[EndBalv2]),
			    cfgAccountingReport[PNL_BUDGET_ACTUAL_PARENT] = "Operating Expenses"
			    )
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: cf25e4c1-86b3-4a67-849e-00f498fdf75f

	measure '6020 - Contract Labor' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6020 - Contract Labor" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: b82a880a-0712-4bfd-ba96-43f13d297e9d

	measure '6000 - Salaries' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6000 - Salaries" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: 0d40b0e2-c83b-445d-a878-3eb5c437733c

	measure '6040 - PTO' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6040 - PTO" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: bedae4f0-c8a8-4c3b-b926-2ca27a323bda

	measure '6810 - Bank Charges' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6810 - Bank Charges" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: 267d28ba-c752-4012-a8d1-ac30e0d2f655

	measure '6750 - Software Subscriptions' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6750 - Software Subscriptions" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: ba85cbe2-d2db-4816-9c54-1018b6ad14e5

	measure '6520 - Travel (non-airfare)' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6520 - Travel (non-airfare)" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: 32858f92-b2cd-478f-9f0c-deeca2800a8d

	measure '6300 - Accounting Support Fees' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6300 - Accounting Support Fees" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: dc3684c2-1fcc-4616-9ec9-e26854a2de94

	measure '6080 - Workers'' Compensation' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6080 - Workers' Compensation" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: 6b5fdb07-32ee-49ec-8816-c3df8863ee62

	measure '6060 - Health Insurance' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6060 - Health Insurance" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: 6987a62b-a278-456f-b1b5-6fbfcb03b9b5

	measure '6065 - Dental/Vision Insurance' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6065 - Dental/Vision Insurance" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: adb0a120-9787-4603-a96f-e6db22195658

	measure '6055 - HSA Employer Contribution' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6055 - HSA Employer Contribution" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: 5f7c31d9-469b-4a40-9c30-5d905bbb0497

	measure '6050 - 401(k) Employer Match' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6050 - 401(k) Employer Match" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: 3b4327aa-bf1f-4556-9199-54596aed97c5

	measure '6030 - Payroll Taxes' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6030 - Payroll Taxes" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: 145934a4-d68e-43e0-abbe-cd2460ac4dad

	measure '6920 - Repairs & Maintenance' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6920 - Repairs & Maintenance" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: c7720f7d-29da-41c9-acc8-845729cf20e5

	measure '6990 - Bad Debt Expense' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6990 - Bad Debt Expense" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: 83aec8ef-ce3b-4a57-b139-dd99b86f868b

	measure '6930 - Other Facilities Costs' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6930 - Other Facilities Costs" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: c6d0620e-7dec-478c-876f-3f864432a319

	measure '6915 - IT Subscriptions & Support' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6915 - IT Subscriptions & Support" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: 277a4431-eede-424b-a3c0-a2d338d21708

	measure '6900 - Utilities' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6900 - Utilities" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: b084d31d-3e10-4c8d-ae3d-45e3516883e9

	measure '6825 - Credit Card Fees' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6825 - Credit Card Fees" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: 79995582-3148-49dc-afee-4358f41e6432

	measure '6820 - Miscellaneous Expense' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6820 - Miscellaneous Expense" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: 36369c2e-3bb6-4813-b8ee-b52098e7c4cb

	measure '6815 - Finance Charges' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6815 - Finance Charges" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: 6751df9c-70e9-4b58-ab83-9ba47b1ce856

	measure '6800 - Business Licenses' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6800 - Business Licenses" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: f494b66d-681a-4a1a-b97b-1e3841cc7d8c

	measure '6795 - Employee Training Events' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6795 - Employee Training Events" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: e7d862f5-62f1-4846-b017-d1443d814087

	measure '6790 - Employee Conferences' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6790 - Employee Conferences" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: fb1b2a2c-01d1-4c2c-9f00-40936710be77

	measure '6785 - Employee Education/Training' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6785 - Employee Education/Training" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: 97985b1e-7fe8-4264-a87b-f2e44919b269

	measure '6780 - PRIVIA Fees' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6780 - PRIVIA Fees" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: 6f06c186-6c9d-4ffb-8d4a-88ad72bec0d5

	measure '6775 - Non-clinical Licenses and Prof. Fees' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6775 - Non-clinical Licenses and Prof. Fees" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: ce30b4a4-fc71-4b9f-b4e6-88f1e94b91e5

	measure '6770 - Minor fixed asset costs (<$1K)' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6770 - Minor fixed asset costs (<$1K)" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: 1f5451b7-d2d5-468e-8a87-8ff8b058d23d

	measure '6765 - Equipment Rental' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6765 - Equipment Rental" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: 93143d31-e101-4caf-af15-c6ca439bdfa8

	measure '6760 - Computer Rental' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6760 - Computer Rental" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: 08c80120-9766-42e0-b4e4-40c34903c442

	measure '6755 - Other Technology Expense' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6755 - Other Technology Expense" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: 61f751af-fa9b-4cac-a613-c7677bba81da

	measure '6745 - Gifts' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6745 - Gifts" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: a4bc5825-a9b1-4fa1-a7e6-779f23692f29

	measure '6735 - Dues & Subscriptions' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6735 - Dues & Subscriptions" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: e5e04515-a39c-42dc-b5d8-1749b0b9989e

	measure '6730 - Postage & Delivery' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6730 - Postage & Delivery" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: 3fb71cde-e1c1-4bdf-a718-c5e54728f4e2

	measure '6720 - Marketing Materials' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6720 - Marketing Materials" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: 7dc57ed3-870d-4f2c-a397-c5c9d6cf6356

	measure '6710 - Payroll Processing Fees' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6710 - Payroll Processing Fees" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: 00046c5b-522f-49bd-94e6-0bee9dcbe995

	measure '6705 - Clinical Licenses & Other Permits' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6705 - Clinical Licenses & Other Permits" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: a4831703-a278-4498-9a42-38ca10fca045

	measure '6700 - Continuing Education & Other Clinical Education' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6700 - Continuing Education & Other Clinical Education" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: d792ae5b-89da-4e9b-9673-d47807a77bd4

	measure '6600 - Office Supplies' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6600 - Office Supplies" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: a2d07733-30b6-4cad-876f-14a61866e360

	measure '6540 - Other Travel Expense' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6540 - Other Travel Expense" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: 4a2239a1-8678-450f-94cd-bde1f40f26cb

	measure '6530 - Meals & Entertainment' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6530 - Meals & Entertainment" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: c2533507-2ca0-481d-baef-f3652c4e8079

	measure '6510 - Lodging' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6510 - Lodging" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: 9269bb27-fefa-490c-b17a-e5d603add8ac

	measure '6500 - Airfare' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6500 - Airfare" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: b59d48a4-1549-4a49-86ff-4a2cbace1259

	measure '6450 - Recruitment Fees' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6450 - Recruitment Fees" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: 5efe8c22-d51d-4b93-932b-8fceae9777e2

	measure '6400 - Insurance' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6400 - Insurance" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: 424a4553-9a2b-41fc-8846-1140b393b006

	measure '6370 - Other Professional Fees' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6370 - Other Professional Fees" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: 4aef00e7-607f-4535-8843-1a2c04aab03e

	measure '6360 - Technology Consulting Fees' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6360 - Technology Consulting Fees" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: dbc7dd62-8239-4f7e-a0f9-c841c5e14241

	measure '6350 - IT Support Services' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6350 - IT Support Services" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: 91726a2b-d9d5-442a-bb41-94a662d5e055

	measure '6340 - Consulting Fees' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6340 - Consulting Fees" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: a7361857-d97a-440b-9e46-8f2359edcada

	measure '6330 - Legal Fees' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6330 - Legal Fees" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: 3b7ef26f-fb4f-4d33-a68a-62ab6f559b5b

	measure '6320 - Tax Prep Fees' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6320 - Tax Prep Fees" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: 551b19ea-1cc5-4efe-8535-0b537663bb19

	measure '6220 - Purchased Advertising' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6220 - Purchased Advertising" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: 14ff7d92-86b3-48cc-b7d9-4f460845ba91

	measure '6200 - Marketing Agency Service Fees' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6200 - Marketing Agency Service Fees" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: 3625c601-7290-4efb-94df-cdcf698b4ba8

	measure '6150 - Office Lease' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6150 - Office Lease" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: 159b072e-b7a6-489d-864d-c1dd4e5ea1c9

	measure '6120 - Electronic Health Record Fees' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6120 - Electronic Health Record Fees" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: e4f92595-4d3f-4d36-8f5a-a91c86c5d103

	measure '6100 - RCM Contract Fees' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6100 - RCM Contract Fees" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: 9e018742-d518-4803-a6c9-7c9d6a86bf20

	measure '6095 - Other Benefits' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6095 - Other Benefits" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: bc5e38d3-5815-4b07-a38f-f6eb005df8a3

	measure '6094 - Accident Benefit' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6094 - Accident Benefit" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: b3e2ca47-b14b-4897-a76f-ca93722e07d7

	measure '6093 - COBRA Benefit' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6093 - COBRA Benefit" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: de9b493a-69a1-4c2d-863f-abe871ccb792

	measure '6092 - Critical Illness Benefit' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6092 - Critical Illness Benefit" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: d7d89dbd-6873-4073-93a0-1d2617b45d7b

	measure '6091 - Hospital Benefit' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6091 - Hospital Benefit" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: 38c6a858-0227-4116-9ab9-781d93b195a0

	measure '6075 - Life Insurance' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6075 - Life Insurance" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: 0847a180-d6e0-4950-8e9e-b300008a83de

	measure '6070 - Disability Insurance' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "6070 - Disability Insurance" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\3.Operating Expenses
		lineageTag: 16ee715f-9737-4726-bb25-ade0731c0177

	measure '9010 - Depreciation Expense' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "9010 - Depreciation Expense" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\4.Other Income & Expense
		lineageTag: 5056467d-134a-4dc4-b954-faf175dad14b

	measure '9040 - Income Tax Expense' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "9040 - Income Tax Expense" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\4.Other Income & Expense
		lineageTag: 07629f3f-ad39-4070-b280-000652747d16

	measure '9050 - Other Expense' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "9050 - Other Expense" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\4.Other Income & Expense
		lineageTag: 9266f0b2-a794-4a59-afea-e4f4739eb2d9

	measure '9080 - Interest Income' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "9080 - Interest Income" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\4.Other Income & Expense
		lineageTag: 22c5245f-d1d8-45f9-ad02-c685dfc5b7fb

	measure '9090 - Other Income' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "9090 - Other Income" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\4.Other Income & Expense
		lineageTag: d66ae9e1-ef85-46ce-b62b-ea3236bba254

	measure '9030 - Interest Expense' = ```
			CALCULATE ( 
			    [Actual], 
			    'cfgAccountingReport'[AccountNbrTitle] = "9030 - Interest Expense" 
			    )
			```
		formatString: #,0
		displayFolder: _AccountDetails\4.Other Income & Expense
		lineageTag: eb71b9b1-e5eb-48d4-8074-8d52fc298279

	measure TotalOIE =
			
			CALCULATE(
			    SUM(vwAccountDetails[EndBalv2]),
			    cfgAccountingReport[PNL_BUDGET_ACTUAL_PARENT] = "Other Income & Expense"
			    )
		formatString: #,0
		displayFolder: _AccountDetails\4.Other Income & Expense
		lineageTag: 9f017bb1-7742-41dc-8cbb-b2fd77420041

	measure Total_GrossMargin = DIVIDE([Total_GrossProfit] , [Revenue_Total],"-")
		displayFolder: _AccountDetails
		lineageTag: c1cd134d-4594-40fb-99e4-e59c25443cbc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Total_NetIncome(Loss) = [Total_EBITDA]  + [TotalOIE]
		formatString: #,0
		displayFolder: _AccountDetails
		lineageTag: 2ca793b3-43cc-47be-943c-54ca7d8709bc

	measure Total_EBITDA = [Total_GrossProfit] + [OperatingExpensesTotal]
		formatString: #,0
		displayFolder: _AccountDetails
		lineageTag: cc181eb5-aef8-4782-a2ac-7a22d36cb6dc

	measure NotCompleted_Patients =
			
			CALCULATE(
			    COUNTROWS(vwMktgwithLTV),
			    vwMktgwithLTV[Completed] = "Not Completed"
			    )
		formatString: #,0
		displayFolder: _LifeTimeValue
		lineageTag: 40b7cb54-aa23-4182-9178-8096cce4c361

	measure Completed_Patients =
			
			CALCULATE(
			    COUNTROWS(vwMktgwithLTV),
			    vwMktgwithLTV[Completed] = "Completed"
			    )
		formatString: #,0
		displayFolder: _LifeTimeValue
		lineageTag: c41848a2-fc88-4d87-8842-57c5e1db7157

	measure '# Completed' =
			
			CALCULATE ( [# Leads], vwCollectiveLead[CompletionStatus] = "Completed" )
		formatString: #,0
		displayFolder: _Marketing\Inquiry
		lineageTag: 59c9168c-41dd-4f99-80f2-a4231f7d3ef5

	measure '% Completion' = [# Completed] / [# Leads]
		formatString: 0\ %;-0\ %;0\ %
		displayFolder: _Marketing\Inquiry
		lineageTag: 11918f08-3a9b-4e42-9f83-4eb845ccf73b

	measure '# Converted_Full' =
			
			calculate(
			    [# Leads],
			    vwCollectiveLead[Status] = "Converted"
			)
		formatString: 0
		displayFolder: _Marketing\Inquiry
		lineageTag: 7e21b69e-0f96-4d6a-8649-fdff54f4cefb

	measure 'Claim Visits' = COUNT(vwClaimAnalysisDtl[EncounterID])
		displayFolder: _ClaimAnalysis
		lineageTag: 452dda74-04b3-4561-a995-e4386d71f09e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Appt Intakes' =
			
			CALCULATE(
			    COUNTROWS(vwClaimAnalysisDtl),
			    vwClaimAnalysisDtl[visitType] = "Intake"
			    )
		displayFolder: _ClaimAnalysis
		lineageTag: a64104e2-3b3c-49bc-82b3-f9a3d42777a7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Appt Not Intakes' =
			
			CALCULATE(
			    COUNTROWS(vwClaimAnalysisDtl),
			    vwClaimAnalysisDtl[visitType] <> "Intake"
			    )
		displayFolder: _ClaimAnalysis
		lineageTag: 8aa0adcc-0e7b-4df6-a942-45d36d384f72

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Appt w AddOn' =
			
			CALCULATE(
			    COUNTROWS(vwClaimAnalysisAddOn),
			    vwClaimAnalysisAddOn[PsyAddOn] = 1
			    )
		formatString: #,0
		displayFolder: _ClaimAnalysis
		lineageTag: 6648a6a0-ea63-455b-9213-116978486c4d

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Appt wo AddOn' =
			
			CALCULATE(
			    COUNTROWS(vwClaimAnalysisAddOn),
			    vwClaimAnalysisAddOn[PsyAddOn] = 0
			    )
		formatString: #,0
		displayFolder: _ClaimAnalysis
		lineageTag: 075a2b2c-5a39-4c39-b624-1a88253366ca

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 90839 =
			
			CALCULATE([Claim Visits]
			        ,FILTER(vwClaimAnalysisDtl,[cpt]="90839")
			        )
		displayFolder: _CodingAnalysis
		lineageTag: 909bbc63-f953-4b05-8eee-064b036f7dbe

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 90832 =
			
			CALCULATE([Claim Visits]
			        ,FILTER(vwClaimAnalysisDtl,[cpt]="90832")
			        )
		displayFolder: _CodingAnalysis
		lineageTag: 51f1f3eb-278f-41fb-b321-c6e866aa0634

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 90834 =
			
			CALCULATE([Claim Visits]
			        ,FILTER(vwClaimAnalysisDtl,[cpt]="90834")
			        )
		displayFolder: _CodingAnalysis
		lineageTag: 78a27812-b547-4447-a160-0d9b3c42a47b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 90837 =
			
			CALCULATE([Claim Visits]
			        ,FILTER(vwClaimAnalysisDtl,[cpt]="90837")
			        )
		displayFolder: _CodingAnalysis
		lineageTag: edd55a42-0d2b-405b-bcc7-4bfd52913261

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 90791 =
			
			CALCULATE([Claim Visits]
			        ,FILTER(vwClaimAnalysisDtl,[cpt]="90791")
			        )
		formatString: 0
		displayFolder: _CodingAnalysis
		lineageTag: 93db6caa-6c87-4f92-96c1-0a5d00893b19

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Total Therapy CPT' = [90832] + [90834] + [90837] + [90839]
		displayFolder: _CodingAnalysis
		lineageTag: 621e7c77-dfca-4e36-bbd3-6c85cb6a2f8a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Therapy Expected Amount' = ```
			
			CALCULATE( 
			    SUM(vwClaimAnalysisDtl[ExpectedAmount])
			    ,FILTER(vwClaimAnalysisDtl, vwClaimAnalysisDtl[cpt] in {"90839","90832","90834","90837","90791"})
			    )
			```
		displayFolder: _CodingAnalysis
		lineageTag: c51843c2-83f5-4787-9d6b-cac85cec4c99

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 90833 =
			
			CALCULATE([Claim Visits]
			        ,FILTER(vwClaimAnalysisDtl,[cpt]="90833")
			        )
		displayFolder: _CodingAnalysis
		lineageTag: 03f932fa-b1f1-4cc8-be94-12e4f18d815e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 90836 =
			
			CALCULATE([Claim Visits]
			        ,FILTER(vwClaimAnalysisDtl,[cpt]="90836")
			        )
		displayFolder: _CodingAnalysis
		lineageTag: ff88ba5a-83db-49c4-a0d7-176d13c20f38

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 90838 =
			
			CALCULATE([Claim Visits]
			        ,FILTER(vwClaimAnalysisDtl,[cpt]="90838")
			        )
		displayFolder: _CodingAnalysis
		lineageTag: 28f98dec-abbf-4d16-8f65-3584420f1a15

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 99212 =
			
			CALCULATE([Claim Visits]
			        ,FILTER(vwClaimAnalysisDtl,[cpt]="99212")
			        )
		displayFolder: _CodingAnalysis
		lineageTag: 3c65116d-b040-495f-9e2d-bc6b3c8a76a6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 99213 =
			
			CALCULATE([Claim Visits]
			        ,FILTER(vwClaimAnalysisDtl,[cpt]="99213")
			        )
		displayFolder: _CodingAnalysis
		lineageTag: d7140a17-5959-4a4c-8485-c31057a9777b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 99214 =
			
			CALCULATE([Claim Visits]
			        ,FILTER(vwClaimAnalysisDtl,[cpt]="99214")
			        )
		displayFolder: _CodingAnalysis
		lineageTag: eabb8dee-0af7-4ed3-817b-7a7a1b17d648

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 99203 =
			
			CALCULATE([Claim Visits]
			        ,FILTER(vwClaimAnalysisDtl,[cpt]="99203")
			        )
		displayFolder: _CodingAnalysis
		lineageTag: 6adeff9d-28aa-4b19-bfd2-e04f9b5f3c5e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 99204 =
			
			CALCULATE([Claim Visits]
			        ,FILTER(vwClaimAnalysisDtl,[cpt]="99204")
			        )
		displayFolder: _CodingAnalysis
		lineageTag: 7b793b36-9064-4178-9519-b4914def62fb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 99205 =
			
			CALCULATE([Claim Visits]
			        ,FILTER(vwClaimAnalysisDtl,[cpt]="99205")
			        )
		displayFolder: _CodingAnalysis
		lineageTag: 8c5109b7-1d88-4808-8d2e-338672545810

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Psychiatry CPT' = [99212] + [99213] + [99214] + [99215]
		displayFolder: _CodingAnalysis
		lineageTag: 4653a1b8-aa66-45a2-b8c8-e9bc4eb7861c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 99215 =
			
			CALCULATE([Claim Visits]
			        ,FILTER(vwClaimAnalysisDtl,[cpt]="99215")
			        )
		displayFolder: _CodingAnalysis
		lineageTag: 4f9e65c7-9e2d-4ce8-a7fe-69f9243cfd51

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Psychiatry Expected Amount' = ```
			
			CALCULATE( 
			    SUM(vwClaimAnalysisDtl[ExpectedAmount])
			    ,FILTER(vwClaimAnalysisDtl, vwClaimAnalysisDtl[cpt] in {"90833","90836","90838","99212","99213","99214","99215","99203","99204","99205"})
			    )
			```
		displayFolder: _CodingAnalysis
		lineageTag: 67babcd1-9f28-48cd-87cc-ccf533c8be97

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Duration 30' =
			
			DIVIDE(
			(
			    CALCULATE([Claim Visits]
			        ,vwClaimAnalysisDtl[Duration]=30
			        ,vwClaimAnalysisDtl[cpt] in {"90839","90832","90834","90837"}
			        )
			),
			([90832]+[90834]+[90837]+[90839])
			)
		formatString: 0%;-0%;0%
		displayFolder: _CodingAnalysis
		lineageTag: c9580754-49be-4719-b824-132c53f497aa

	measure 'Duration 45' =
			
			DIVIDE(
			(
			    CALCULATE([Claim Visits]
			        ,vwClaimAnalysisDtl[Duration]=45
			        ,vwClaimAnalysisDtl[cpt] in {"90839","90832","90834","90837"}
			        )
			),
			([90832]+[90834]+[90837]+[90839])
			)
		formatString: 0%;-0%;0%
		displayFolder: _CodingAnalysis
		lineageTag: 57e91ada-e2e1-4f38-88ae-170c80307d10

	measure 'Duration 60' =
			
			DIVIDE(
			(
			    CALCULATE([Claim Visits]
			        ,vwClaimAnalysisDtl[Duration]=60
			        ,vwClaimAnalysisDtl[cpt] in {"90839","90832","90834","90837"}
			        )
			),
			([90832]+[90834]+[90837]+[90839])
			)
		formatString: 0%;-0%;0%
		displayFolder: _CodingAnalysis
		lineageTag: 1b0269cc-da62-436e-80d0-6b222f8e2afa

	measure 90792 =
			
			CALCULATE([Claim Visits]
			        ,FILTER(vwClaimAnalysisDtl,[cpt]="90792")
			        )
		displayFolder: _CodingAnalysis
		lineageTag: 2deac6ff-8606-4f18-9e41-ece2457c3e5f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 90785 =
			
			CALCULATE([Claim Visits]
			        ,FILTER(vwClaimAnalysisDtl,[cpt]="90785")
			        )
		displayFolder: _CodingAnalysis
		lineageTag: d003c512-6462-4b10-bc5c-a278dfa26917

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 99212% =
			
			DIVIDE(
			(
			    CALCULATE([Claim Visits]
			        ,vwClaimAnalysisDtl[cpt] = "99212"
			        )
			),
			([99212]+[99213]+[99214]+[99215])
			)
		formatString: 0%;-0%;0%
		displayFolder: _CodingAnalysis
		lineageTag: 53cb836a-f70d-41c0-ab50-74951ee64d1c

	measure 99213% =
			
			DIVIDE(
			(
			    CALCULATE([Claim Visits]
			        ,vwClaimAnalysisDtl[cpt] = "99213"
			        )
			),
			([99212]+[99213]+[99214]+[99215])
			)
		formatString: 0%;-0%;0%
		displayFolder: _CodingAnalysis
		lineageTag: ce6a4439-6b01-4aca-a9ea-391fa78583f0

	measure 99214% =
			
			DIVIDE(
			(
			    CALCULATE([Claim Visits]
			        ,vwClaimAnalysisDtl[cpt] = "99214"
			        )
			),
			([99212]+[99213]+[99214]+[99215])
			)
		formatString: 0%;-0%;0%
		displayFolder: _CodingAnalysis
		lineageTag: c9208156-fb19-418f-a32d-e64aca756d7a

	measure 99215% =
			
			DIVIDE(
			(
			    CALCULATE([Claim Visits]
			        ,vwClaimAnalysisDtl[cpt] = "99215"
			        )
			),
			([99212]+[99213]+[99214]+[99215])
			)
		formatString: 0%;-0%;0%
		displayFolder: _CodingAnalysis
		lineageTag: 7549861d-27f5-4762-890f-86b9d3cec481

	measure #_Patients = DISTINCTCOUNT( vwClinicalAnalytics[PatientId] )
		formatString: #,0
		displayFolder: _ClinicalAnalytics
		lineageTag: 7f46d9b3-127a-4041-8807-58be81f83fe0

	measure #_tot_visits = SUM(vwClinicalAnalytics[TotalVisits])
		formatString: #,0
		displayFolder: _ClinicalAnalytics
		lineageTag: d8a8457b-a688-43f3-add0-7043704e88cd

	measure avg_Visits = ```
			AVERAGE(vwClinicalAnalytics[TotalVisits]) 
			```
		displayFolder: _ClinicalAnalytics
		lineageTag: f3a48fad-f9b7-4113-b573-904c26d84e35

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure #_ThVisits = SUM(vwClinicalAnalytics[TherapyVisits])
		formatString: #,0
		displayFolder: _ClinicalAnalytics
		lineageTag: cff9de12-68b7-43e2-acbc-46001f5f00fe

	measure #_PsyVisits = SUM(vwClinicalAnalytics[PsychVisits])
		formatString: #,0
		displayFolder: _ClinicalAnalytics
		lineageTag: 31e05428-10d5-43b0-895f-65430ee7e044

	measure 'Actual 1 1' =
			
			CALCULATE(
			    SUM(vwAccountDetails[EndBalv2]),
			    cfgAccountingReport[PNL_BUDGET_ACTUAL_PARENT] <> "N/A"
			    )
		formatString: #,0
		displayFolder: _EMRSF
		lineageTag: 79dea192-cb81-48d2-9a56-5b14c6df8ca8

	measure 'Actual 1 2' =
			
			CALCULATE(
			    SUM(vwAccountDetails[EndBalv2]),
			    cfgAccountingReport[PNL_BUDGET_ACTUAL_PARENT] <> "N/A"
			    )
		formatString: #,0
		displayFolder: _EMRSF
		lineageTag: eb93fd26-b6e7-4d76-bb73-e85f2f14d860

	measure 'Patients Count' =
			
			COUNT(EmrSfMatch[emr_patientid])
		formatString: #,0
		displayFolder: _EMRSF
		lineageTag: 1d54b97a-1bf4-43d4-8eff-6dd5ed7666d6

	measure 'Patients Distinct Count' =
			
			DISTINCTCOUNT(EmrSfMatch[emr_patientid])
		formatString: #,0
		displayFolder: _EMRSF
		lineageTag: 3169cbaf-46f1-4060-a32b-2b82c9758f31

	measure 'Expected Amount 121-150' =
			
			var endDate = TODAY()-121
			var startDate = TODAY()-150
			
			return CALCULATE([Total Net A/R]
			                ,DATESBETWEEN(dimDate[Date],startDate,endDate)
			)
		displayFolder: _RCM
		lineageTag: 30cfc339-0625-475e-a738-2d254235c909

	measure 'Expected Amount 151-180' =
			
			var endDate = TODAY()-151
			var startDate = TODAY()-180
			
			return CALCULATE([Total Net A/R]
			                ,DATESBETWEEN(dimDate[Date],startDate,endDate)
			)
		displayFolder: _RCM
		lineageTag: 07a31523-6712-4051-aa16-b3fcc966ee0e

	measure 'Expected Amount 181-365' =
			
			var endDate = TODAY()-181
			var startDate = TODAY()-365
			
			return CALCULATE([Total Net A/R]
			                ,DATESBETWEEN(dimDate[Date],startDate,endDate)
			)
		displayFolder: _RCM
		lineageTag: 2cb0a7eb-9634-4fc1-a6dd-16af54c09efa

	measure 'Expected Amount 31-60' =
			
			var endDate = TODAY()-31
			var startDate = TODAY()-60
			
			return CALCULATE([Total Net A/R]
			                ,DATESBETWEEN(dimDate[Date],startDate,endDate)
			)
		displayFolder: _RCM
		lineageTag: 98e0c61a-64a1-4dbe-a449-2baaa192a431

	measure 'Expected Amount 365+' =
			
			var endDate = TODAY()-366
			var startDate = MIN(dimDate[Date])
			
			return CALCULATE([Total Net A/R]
			                ,DATESBETWEEN(dimDate[Date],startDate,endDate)
			)
		displayFolder: _RCM
		lineageTag: 930f0651-f9ed-4298-b76d-45c40f5b3305

	measure 'Expected Amount 61-90' =
			
			var endDate = TODAY()-61
			var startDate = TODAY()-90
			
			return CALCULATE([Total Net A/R]
			                ,DATESBETWEEN(dimDate[Date],startDate,endDate)
			)
		displayFolder: _RCM
		lineageTag: 019bb2f4-642b-43c0-9123-da7e91513a5a

	measure 'Expected Amount 91-120' =
			
			var endDate = TODAY()-91
			var startDate = TODAY()-120
			
			return CALCULATE([Total Net A/R]
			                ,DATESBETWEEN(dimDate[Date],startDate,endDate)
			)
		displayFolder: _RCM
		lineageTag: 3c76ef68-c285-4c83-8fdc-983e811e638c

	measure 'Expected Amount Current' =
			
			var endDate = TODAY()
			var startDate = TODAY()-30
			
			return CALCULATE([Total Net A/R]
			                ,DATESBETWEEN(dimDate[Date],startDate,endDate)
			)
		displayFolder: _RCM
		lineageTag: de79027a-bd7d-4cb6-b699-910cd69dfff9

	measure 'Gross Charges' = ```
			
			    SUM(vwSumPaymentDetailExtended[Charges])
			```
		displayFolder: _RCM
		lineageTag: a0aeb2d8-4855-48ee-9486-18ac78403408

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sum of Total Outstanding' = [Expected Amount Current] + [Expected Amount 31-60] + [Expected Amount 61-90] + [Expected Amount 91-120] + [Expected Amount 121-150] + [Expected Amount 151-180] + [Expected Amount 181-365] + [Expected Amount 365+]
		displayFolder: _RCM
		lineageTag: 062d503c-b606-49f1-b68a-6537dabc9cf9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Expected Contractual Reduction' = [Gross Charges] - [Expected Amount]
		displayFolder: _RCM
		lineageTag: b529b7ce-d047-40c3-83b1-5295bb8de2fc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross Collections - Posting' = [Patient Payments - Posting] + [Insurance Payments - Posting]
		displayFolder: _RCM
		lineageTag: 22bec8ee-06bc-4533-9bcd-cb94a1efec9d

	measure 'Insurance Payments - Posting' = ```
			
			    SUM(vwSumPaymentPosting[InsurancePayment])
			```
		displayFolder: _RCM
		lineageTag: a4a52e71-01bb-4da2-af6d-3ca14dc590b3

	measure 'Patient Payments - Posting' = ```
			
			    SUM(vwSumPaymentPosting[PatientPayment])
			```
		displayFolder: _RCM
		lineageTag: f83b49dd-517c-461b-a7e3-c96d7bf87d45

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Collections - 90 Days' = ```
			
			
			var endDate = TODAY()-1
			var startDate = TODAY()-91
			
			var result = 
			    CALCULATE([Gross Collections - Posting]
			                ,DATESBETWEEN(dimDate[Date],startDate,endDate)
			            )/90
			return result
			```
		displayFolder: _RCM
		lineageTag: 19ebf562-f349-437d-8d1e-15e73cc2ce21

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross Collections - 90 Days' = ```
			
			
			var endDate = TODAY()-1
			var startDate = TODAY()-91
			
			var result = 
			    CALCULATE([Gross Collections - Posting]
			                ,DATESBETWEEN(dimDate[Date],startDate,endDate)
			            )
			return result
			```
		displayFolder: _RCM
		lineageTag: 62e69e76-abfb-4b1f-88c0-c62e72af9a03

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% AddOn' = ```
			DIVIDE(
			    [Total AddOn],
			    [Total Psychiatry CPT]
			)
			
			```
		formatString: 0%;-0%;0%
		displayFolder: _CodingAnalysis
		lineageTag: 18d72c58-4b2a-41d3-ad0d-9e4b0effdf33

	measure '% AddOn LY' =
			Calculate(
			    [% AddOn],
			    SAMEPERIODLASTYEAR('dimDate'[Date])
			)
		formatString: 0%;-0%;0%
		displayFolder: _CodingAnalysis
		lineageTag: c1c55d14-dd2a-4091-9e93-b37058b5bfdb

	measure 'Total AddOn' = [90833] + [90836] + [90838]
		formatString: #,0
		displayFolder: _CodingAnalysis
		lineageTag: 73ea9cba-44b3-4d58-a9e1-314ce2cc3cf2

	measure 'Total Intakes' = [90792] + [99204] + [99205]
		formatString: #,0
		displayFolder: _CodingAnalysis
		lineageTag: 10b99d7c-62c3-45e9-bb2f-3ec9b901afa6

	measure 'Average Collections Gross - 90 Days' = ```
			
			
			var endDate = TODAY()-1
			var startDate = TODAY()-91
			
			var result = 
			    CALCULATE([Gross Collections]
			                ,DATESBETWEEN(dimDate[Date],startDate,endDate)
			            )/90
			return result
			```
		displayFolder: _RCM
		lineageTag: 8388ec4b-20a3-437d-81f7-26e152b50645

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DAP = ```
			
			
			var endDate = TODAY()-1
			var startDate = TODAY()-91
			
			var result = 
			    CALCULATE([Gross Collections - Posting]
			                ,DATESBETWEEN(dimDate[Date],startDate,endDate)
			            )/90
			return [Total Net A/R]/result
			```
		displayFolder: _RCM
		lineageTag: 144d0797-3315-4234-bbce-5844d6e5fd48

	measure 'Gross A/R 121-150' =
			
			var endDate = TODAY()-121
			var startDate = TODAY()-150
			
			return CALCULATE([Total Gross A/R]
			                ,DATESBETWEEN(dimDate[Date],startDate,endDate)
			)
		displayFolder: _RCM
		lineageTag: b7aab2b5-e679-455f-9f92-0e65365e920f

	measure 'Gross A/R 151-180' =
			
			var endDate = TODAY()-151
			var startDate = TODAY()-180
			
			return CALCULATE([Total Gross A/R]
			                ,DATESBETWEEN(dimDate[Date],startDate,endDate)
			)
		displayFolder: _RCM
		lineageTag: 3afe31a8-26e3-4dcf-ba71-677d0df046bf

	measure 'Gross A/R 181-365' =
			
			var endDate = TODAY()-181
			var startDate = TODAY()-365
			
			return CALCULATE([Total Gross A/R]
			                ,DATESBETWEEN(dimDate[Date],startDate,endDate)
			)
		displayFolder: _RCM
		lineageTag: 3cbc37e4-bc9e-488a-81ac-6c2cc2f619ff

	measure 'Gross A/R 31-60' =
			
			var endDate = TODAY()-31
			var startDate = TODAY()-60
			
			return CALCULATE([Total Gross A/R]
			                ,DATESBETWEEN(dimDate[Date],startDate,endDate)
			)
		displayFolder: _RCM
		lineageTag: 1e39b4c7-3f77-4db0-a43a-3bbf717b7c22

	measure 'Gross A/R 365+' =
			
			var endDate = TODAY()-366
			var startDate = MIN(dimDate[Date])
			
			return CALCULATE([Total Gross A/R]
			                ,DATESBETWEEN(dimDate[Date],startDate,endDate)
			)
		displayFolder: _RCM
		lineageTag: 9a519025-d798-4f93-a2af-b587a8ab03dd

	measure 'Gross A/R 61-90' =
			
			var endDate = TODAY()-61
			var startDate = TODAY()-90
			
			return CALCULATE([Total Gross A/R]
			                ,DATESBETWEEN(dimDate[Date],startDate,endDate)
			)
		displayFolder: _RCM
		lineageTag: 36c9d220-d9da-42d6-9334-ba1c788dead8

	measure 'Gross A/R 91-120' =
			
			var endDate = TODAY()-91
			var startDate = TODAY()-120
			
			return CALCULATE([Total Gross A/R]
			                ,DATESBETWEEN(dimDate[Date],startDate,endDate)
			)
		displayFolder: _RCM
		lineageTag: 00038d9f-3e24-40b0-b0a5-b45969c39965

	measure 'Gross A/R Current' =
			
			var endDate = TODAY()
			var startDate = TODAY()-30
			
			return CALCULATE([Total Gross A/R]
			                ,DATESBETWEEN(dimDate[Date],startDate,endDate)
			)
		displayFolder: _RCM
		lineageTag: b1797c11-c0d5-40a2-95de-bea1dd93cdee

	measure 'Sum of Total Gross Outstanding' = [Gross A/R Current] + [Gross A/R 31-60] + [Gross A/R 61-90] + [Gross A/R 91-120] + [Gross A/R 121-150] + [Gross A/R 151-180] + [Gross A/R 181-365] + [Gross A/R 365+]
		displayFolder: _RCM
		lineageTag: 385de4b0-1349-4f8a-97d9-e1973b1d4d73

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Gross A/R' = ```
			
			    SUM(vwSumPaymentDetailExtended[GrossTotalAR])
			```
		displayFolder: _RCM
		lineageTag: 9c6856c6-2f56-4fee-a8f1-cbe529b77060

	measure 'Total Net A/R' = ```
			
			    SUM(vwSumPaymentDetailExtended[GrandTotalAR])
			```
		displayFolder: _RCM
		lineageTag: b630f429-e74e-45d5-b4c1-0924825acc35

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '__Appts Completed' = ```
			
			CALCULATE(
			    SUM( vwReferralConversion[Completed] ), 
			    vwReferralConversion[ConversionFlag] = "Converted")
			```
		formatString: #,0
		displayFolder: _Referral Conversion
		lineageTag: 9a01ae21-6c95-4e96-9beb-605b2dba4e9d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Time to Conversion' = ```
			
			AVERAGE(
			    vwReferralConversion[DateDifference]
			)
			
			```
		formatString: #,0
		displayFolder: _Referral Conversion
		lineageTag: 227ac450-2139-40ee-867a-f5cf24fb352e

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Converted Referrals' =
			
			//Refarrals with at least one completed Appt
			CALCULATE(
			    COUNTROWS(vwReferralConversion),
			    vwReferralConversion[ConversionFlag] = "Converted"
			)
		formatString: #,0
		displayFolder: _Referral Conversion
		lineageTag: 63398b84-2183-4b96-9db4-08bde50a7475

	measure 'Not Converted Refs' =
			
			CALCULATE(
			    COUNTROWS(vwReferralConversion),
			    vwReferralConversion[ConversionFlag] = "Not Converted"
			)
		formatString: #,0
		displayFolder: _Referral Conversion
		lineageTag: d0128bc4-aac0-48e1-b419-82ec6a9aa3a7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Referrals Total' = ```
			
			COUNTROWS(vwReferralConversion)
			
			```
		formatString: #,0
		displayFolder: _Referral Conversion
		lineageTag: 3eb0688f-cf65-488a-be35-a8ca42b72deb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Allowable = ```
			
			    SUM(vwSumPaymentDetailExtended[ExpectedAmount])
			    --to be used in Nadia version as expected amount
			```
		displayFolder: _RCM
		lineageTag: 39fd1cf1-2a2c-44de-9ece-25d5eba52705

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Expected Contractual Reduction New' = [Gross Charges] - [Allowable]
		displayFolder: _RCM
		lineageTag: 3f321e9a-867f-4ada-93ae-c5ca04e8fa5e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '# Checkout Visits - Therapy - Comb' = ```
			
			[# Completed - Intake - Th - Comb] + 
			[# Completed - FU Patient - Th - Comb]
			```
		formatString: #,0
		displayFolder: _PnL\Completed Visits
		lineageTag: 10823971-fefb-44aa-a2f0-06bb73e870bb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '# Checkout Visits - Psychiatric - Comb' = ```
			
			[# Completed - Intake - Psy - Comb] + 
			[# Completed - FU Patient - Psy - Comb]
			
			```
		formatString: #,0
		displayFolder: _PnL\Completed Visits
		lineageTag: 8a067a0f-3726-4a60-b957-156a17e5de0c

		changedProperty = FormatString

	measure '# Checkout Visits - Total - Comb' = ```
			
			[# Checkout Visits - Psychiatric - Comb] 
			+
			[# Checkout Visits - Therapy - Comb]
			```
		displayFolder: _PnL\Completed Visits
		lineageTag: 7cc67f5c-c284-4307-814a-fdd3a771709f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '# Checkout Visits - FU - Comb' = ```
			
			[# Completed - FU Patient - Psy - Comb] + 
			[# Completed - FU Patient - Th - Comb]
			```
		formatString: #,0
		displayFolder: _PnL\Completed Visits
		lineageTag: 79686388-0c04-4a22-b144-7c15e74cee36

		changedProperty = FormatString

	measure '# Checkout Visits - Intake - Comb' = ```
			
			[# Completed - Intake - Psy - Comb] + 
			[# Completed - Intake - Th - Comb]
			```
		formatString: #,0
		displayFolder: _PnL\Completed Visits
		lineageTag: e943167f-c738-4970-8655-b087491dc849

		changedProperty = FormatString

	measure 'Revenue Visits - Psychiatric - Comb' =
			
			SUM(vwDailySalesCombined[PsyFupRev]) + SUM(vwDailySalesCombined[PsyIntRev])
		formatString: #,0
		displayFolder: _Finance\_Complement measures
		lineageTag: e78fbb45-9e4a-467d-bccc-df2ce1d6142a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Revenue Visits - Therapy - Comb' =
			
			SUM(vwDailySalesCombined[ThrFupRev]) + SUM(vwDailySalesCombined[ThrIntRev])
		formatString: #,0
		displayFolder: _Finance\_Complement measures
		lineageTag: fccdcdc9-8852-4a96-9061-86c6d34b8643

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Appts By Converted' =
			
			DIVIDE(
			    [__Appts Completed]
			    , [Converted Referrals]
			    , "-"
			)
		formatString: #,0
		displayFolder: _Referral Conversion
		lineageTag: 4c34f8b6-9486-44d1-b13d-eb80c17b75da

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Appts By Tot Refs' =
			
			DIVIDE(
			    [__Appts Completed]
			    , [Referrals Total]
			    , "-"
			)
		formatString: #,0
		displayFolder: _Referral Conversion
		lineageTag: cc24eba8-891c-4027-beb0-b36a0e85c152

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Monthly - Cumulative Revenue - Comb' = ```
			
			VAR BeginPeriod =
			    IF (
			        SELECTEDVALUE ( dimDate[Slicer Month] ) = "Current Month",
			        DATE( YEAR( TODAY() ), MONTH ( TODAY() ), "01"),
			        DATE( YEAR( SELECTEDVALUE ( dimDate[Slicer Month] ) ), MONTH( SELECTEDVALUE( dimDate[Slicer Month] ) ), "01" )
			    )
			VAR _resu =
			    CALCULATE (
			        [Revenue Visits - Total - Comb],
			        FILTER (
			            
			            ALL ( 'dimDate'[Date] ),
			            AND (
			                'dimDate'[Date] <= MAX ( 'dimDate'[Date] ),
			                'dimDate'[Date] >= BeginPeriod
			            )
			        )
			    )
			
			RETURN 
			    IF( [# Completed - Total - Comb] = BLANK(), BLANK(), _resu )
			```
		formatString: #,0
		displayFolder: _Finance
		lineageTag: 80155530-2f7d-4e11-91ae-09005182cc0f

		changedProperty = FormatString

	measure 'Monthly - Cumulative Budget - Comb' = ```
			
			VAR BeginPeriod =
			    IF (
			        SELECTEDVALUE ( dimDate[Slicer Month] ) = "Current Month",
			        DATE( YEAR( TODAY() ), MONTH ( TODAY() ), "01" ),
			        DATE( YEAR( SELECTEDVALUE ( dimDate[Slicer Month] ) ), MONTH( SELECTEDVALUE( dimDate[Slicer Month] ) ), "01" )
			    )
			VAR _resu = 
			    CALCULATE (
			        [Revenue Recast -Total],
			        FILTER (
			            ALL ( 'dimDate'[Date] ),
			            AND (
			                'dimDate'[Date] <= MAX ( 'dimDate'[Date] ),
			                'dimDate'[Date] >= BeginPeriod
			            )
			        )
			    )
			
			RETURN 
			    IF( [# Completed - Total - Comb] = BLANK(), BLANK(), _resu)
			```
		formatString: #,0
		displayFolder: _Finance
		lineageTag: 440d04c2-4c28-4cd1-8dad-7b71975e6f3e

		changedProperty = FormatString

	measure 'Projection - Comb' =
			
			[Monthly - Cumulative Revenue - Comb] / [Monthly - Cumulative Budget - Comb] *
			[Revenue - Recast Monthly For Table]
		formatString: #,0
		displayFolder: _Finance
		lineageTag: df468da6-1e74-4325-b39d-0e7a1a326aab

		changedProperty = FormatString

	measure 'Projection By Facility - Comb' =
			
			[Monthly - Cumulative Revenue - Comb] / [Revenue Recast Total - MTD] *
			[Revenue - Recast Monthly For Table]
		formatString: #,0
		displayFolder: _Finance
		lineageTag: dd5088fd-c9d2-4cfa-b822-12ae0882f207

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Cumulative Visits - Psy - FU - Comb' = ```
			
			CALCULATE (
			    [# Completed - FU Patient - Psy - Comb],
			    FILTER ( 
			        ALLSELECTED ( '2_Date_Expander' ), 
			        '2_Date_Expander'[Date] <= MAX ( '2_Date_Expander'[Date] ) 
			    )
			)
			```
		formatString: #,0
		displayFolder: _PnL\Cumulative Visits\Comb
		lineageTag: 715683a6-a710-44bd-9035-69d2a806f095

	measure 'Cumulative Visits - Psy - Intake - Comb' = ```
			
			CALCULATE (
			    [# Completed - Intake - Psy - Comb],
			    FILTER ( 
			        ALLSELECTED ( '2_Date_Expander' ), 
			        '2_Date_Expander'[Date] <= MAX ( '2_Date_Expander'[Date] ) 
			    )
			)
			```
		formatString: #,0
		displayFolder: _PnL\Cumulative Visits\Comb
		lineageTag: 68c051e3-1c21-4e48-8abb-c382d3d88bef

	measure 'Cumulative Visits - Therapy - FU - Comb' =
			
			CALCULATE (
			    [# Completed - FU Patient - Th - Comb],
			    FILTER (
			        ALLSELECTED ( '2_Date_Expander' ),
			        '2_Date_Expander'[Date] <= MAX ( '2_Date_Expander'[Date] )
			    )
			)
		formatString: #,0
		displayFolder: _PnL\Cumulative Visits\Comb
		lineageTag: cee22e55-009c-4abb-bd2b-9141d584c481

	measure 'Cumulative Visits - Therapy - Intake - Comb' = ```
			
			CALCULATE (
			    [# Completed - Intake - Th - Comb],
			    FILTER (
			        ALLSELECTED ( '2_Date_Expander' ),
			        '2_Date_Expander'[Date] <= MAX ( '2_Date_Expander'[Date] )
			    )
			)
			
			```
		formatString: #,0
		displayFolder: _PnL\Cumulative Visits\Comb
		lineageTag: 6862d896-09eb-4b30-9593-111f859d3cd8

	measure 'Cumulative Visits - Total - Comb' =
			[Cumulative Visits - Total - Psy]
			+
			[Cumulative Visits - Total - Therapy]
		formatString: #,0
		displayFolder: _PnL\Cumulative Visits\Comb
		lineageTag: afcb5c33-e535-4846-b687-ed4e5735f72c

		changedProperty = FormatString

	measure 'Cumulative Visits - Total - FU - Comb' = ```
			
			[Cumulative Visits - Psy - FU - Comb] + 
			[Cumulative Visits - Therapy - FU - Comb]
			
			```
		formatString: #,0
		displayFolder: _PnL\Cumulative Visits\Comb
		lineageTag: 6f2f3479-72c5-4a09-aaee-c0cf8e207d34

		changedProperty = FormatString

	measure 'Cumulative Visits - Total - Intake - Comb' = ```
			
			[Cumulative Visits - Therapy - Intake - Comb] + 
			[Cumulative Visits - Psy - Intake - Comb]
			```
		formatString: #,0
		displayFolder: _PnL\Cumulative Visits\Comb
		lineageTag: ee870858-f95b-4d32-b0e4-9dddc049839f

		changedProperty = FormatString

	measure 'Cumulative Visits - Total - Psy - Comb' =
			
			[Cumulative Visits - Psy - FU - Comb]
			+
			[Cumulative Visits - Psy - Intake - Comb]
		formatString: #,0
		displayFolder: _PnL\Cumulative Visits\Comb
		lineageTag: 7ece0bb9-980a-4b4f-8bae-aaad44673690

	measure 'Cumulative Visits - Total - Therapy - Comb' =
			[Cumulative Visits - Therapy - FU - Comb]
			+
			[Cumulative Visits - Therapy - Intake - Comb]
		formatString: #,0
		displayFolder: _PnL\Cumulative Visits\Comb
		lineageTag: ba2daf32-a061-40e9-b859-fb29179fc611

	measure 'CumulativeRevenue - Visits - Psy - Comb' =
			CALCULATE (
			    [Revenue Visits - Psychiatric - Comb],
			    FILTER (
			        ALLSELECTED ( '2_Date_Expander' ),
			        '2_Date_Expander'[Date] <= MAX ( '2_Date_Expander'[Date] )
			    )
			)
		formatString: #,0
		displayFolder: _PnL\Cumulative Revenue
		lineageTag: a93b47d2-2f15-4148-b773-787a00b3b2d1

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'CumulativeRevenue - Visits - Therapy - Comb' =
			CALCULATE (
			    [Revenue Visits - Therapy - Comb] ,
			    FILTER (
			        ALLSELECTED ( '2_Date_Expander' ),
			        '2_Date_Expander'[Date] <= MAX ( '2_Date_Expander'[Date] )
			    )
			)
		formatString: #,0
		displayFolder: _PnL\Cumulative Revenue
		lineageTag: c83f87a5-2787-4456-a482-5211d94bfadd

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'CumulativeRevenue - Visits - Total - Comb' =
			
			[CumulativeRevenue - Visits - Psy - Comb]
			+
			[CumulativeRevenue - Visits - Therapy - Comb]
		formatString: #,0
		displayFolder: _PnL\Cumulative Revenue
		lineageTag: 394a01d1-9ca4-49c9-9ec8-4a0007f85af3

		changedProperty = FormatString

	measure '__Referrals Converted' = ```
			
			CALCULATE(
			    COUNTROWS(vwReferralConversion), 
			    vwReferralConversion[ConversionFlag]  = "Converted"
			)
			```
		formatString: #,0
		displayFolder: _Referral Conversion
		lineageTag: 7ecaeb03-e45d-462f-b305-1f897b833d6c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '__Referrals Completed' = ```
			
			CALCULATE(
			    COUNTROWS(vwReferralConversion), 
			    vwReferralConversion[CompletedFlag]  = "Completed"
			)
			```
		formatString: #,0
		displayFolder: _Referral Conversion
		lineageTag: 262712c8-cb2f-4a25-8680-e44dce841c4c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '__Referrals Not Converted' = ```
			
			CALCULATE(
			    COUNTROWS(vwReferralConversion), 
			    vwReferralConversion[ConversionFlag]  <> "Converted"
			)
			```
		formatString: #,0
		displayFolder: _Referral Conversion
		lineageTag: 21e64e55-fd51-4b7d-9fa3-065efa1b15da

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Conversion Rate' = ```
			
			DIVIDE(
			    [__Referrals Converted],    
			    [Referrals Total], 
			    "-"
			)
			```
		formatString: 0%;-0%;0%
		displayFolder: _Referral Conversion
		lineageTag: 4c199b2e-af19-4002-8184-501e4ba4ef3b

	measure '% Completion Rate' = ```
			
			DIVIDE(
			    [__Referrals Completed],    
			    [Referrals Total], 
			    "-"
			)
			```
		formatString: 0%;-0%;0%
		displayFolder: _Referral Conversion
		lineageTag: 1799a1b0-6969-45de-aa64-cf76b6f87a48

	measure '__Appts NoShow' =
			
			SUM ( vwReferralConversion[NoShow] )
		formatString: #,0
		displayFolder: _Referral Conversion
		lineageTag: ea7e9c1d-e491-47bf-895f-e86f71681ac2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '__Appts Cancel' = ```
			
			 SUM(vwReferralConversion[Cancel])
			```
		formatString: #,0
		displayFolder: _Referral Conversion
		lineageTag: 816f1689-ba22-4514-8a39-e63694ca12b8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '__Appts Pending' = ```
			
			 SUM(vwReferralConversion[Pending])
			```
		formatString: #,0
		displayFolder: _Referral Conversion
		lineageTag: 1b1b44b0-6294-4086-9ef9-b7043ebf737d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '__Appts Not Completed' =
			
			[__Appts Cancel] + [__Appts NoShow] + [__Appts Pending]
		formatString: #,0
		displayFolder: _Referral Conversion
		lineageTag: cd174022-03c6-4abb-af65-fe0524188db5

	measure '# Appt In-Person' = SUM('vwCollectiveLead'[InPersonVisits])
		formatString: #,0
		displayFolder: _MtSinai
		lineageTag: 7ed5e8fe-ddc9-4ada-b117-3d00e051483e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '# Appt Telehealth' = SUM('vwCollectiveLead'[TeleVisits])
		formatString: #,0
		displayFolder: _MtSinai
		lineageTag: f5cb544c-7ab8-4cf8-96f9-c0263eb44c29

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '# BothVisits' =
			
			CALCULATE(
			        [# TotalVisits],
			        FILTER('vwCollectiveLead','vwCollectiveLead'[PatientCategory]="Both")
			        )
		formatString: #,0
		displayFolder: _MtSinai
		lineageTag: eb237782-1b4a-4dc6-b95d-499a88930848

	measure '# Patient' = COUNT('vwCollectiveLead'[PatientId])
		formatString: #,0
		displayFolder: _MtSinai
		lineageTag: a566b8be-17da-4d24-8a91-f6b5975f1ffe

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '# PsychiatricOnlyVisits' =
			
			CALCULATE(
			        [# PsychiatricVisits],
			        FILTER('vwCollectiveLead','vwCollectiveLead'[PatientCategory]="Psychiatry")
			        )
		formatString: #,0
		displayFolder: _MtSinai
		lineageTag: bbe44ff9-1b58-4f34-b300-61b97a80be00

	measure '# PsychiatricVisits' = SUM('vwCollectiveLead'[PsychVisits])
		formatString: #,0
		displayFolder: _MtSinai
		lineageTag: 9a88b08d-a2dc-4681-9146-8053ef0cb8b5

	measure '# TherapyOnlyVisits' =
			
			CALCULATE(
			        [# TherapyVisits],
			        FILTER('vwCollectiveLead','vwCollectiveLead'[PatientCategory]="Therapy")
			        )
		formatString: #,0
		displayFolder: _MtSinai
		lineageTag: a0667cab-388e-4e0f-a770-a4f3ff9c0532

	measure '# TherapyVisits' = SUM('vwCollectiveLead'[TherapyVisits])
		formatString: #,0
		displayFolder: _MtSinai
		lineageTag: 7168dbc6-b4ec-45f6-a6f1-3efd97d22d6a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '# TotalVisits' = SUM('vwCollectiveLead'[TotalCompVisits])
		formatString: #,0
		displayFolder: _MtSinai
		lineageTag: d6434446-3e25-4b1e-b67c-e8024c53c5a4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '#Leads - MtSinai' = ```
			
			    CALCULATE(  
			        COUNT(vwCollectiveLead[LeadStatus])
			        ,FILTER(
			            vwCollectiveLead
			            ,vwCollectiveLead[LeadSource]="Mt Sinai General"
			        )
			    )
			```
		formatString: #,0
		displayFolder: _MtSinai
		lineageTag: d3d2a09d-7ed8-4a61-9e62-cce5bd41c2be

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '#Leads - RAP Program' = ```
			
			    CALCULATE(  
			        COUNT(vwCollectiveLead[LeadStatus])
			        ,FILTER(
			            vwCollectiveLead
			            ,vwCollectiveLead[LeadSource]="Sinai RAP Program"
			        )
			    )
			```
		formatString: #,0
		displayFolder: _MtSinai
		lineageTag: 4c9eed73-b091-4261-a856-2eb8eed9bb18

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% BothVisits' = [# BothVisits] / [# TotalVisits]
		formatString: 0%;-0%;0%
		displayFolder: _MtSinai
		lineageTag: 44a59955-a821-4944-9e7c-f1589e27f161

	measure '% Completion_sinai' = DIVIDE( [# Completed], [Leads] )
		formatString: 0\ %;-0\ %;0\ %
		displayFolder: _MtSinai
		lineageTag: 483d1e57-9d9d-45d8-9efa-8d01afd55197

	measure '% Completion_sinai_InPerson' = DIVIDE( [# Appt In-Person], [# Appt In-Person]+[# Appt Telehealth] )
		formatString: 0%;-0%;0%
		displayFolder: _MtSinai
		lineageTag: 5a259193-04f7-4ad7-9ecc-c5ce45e0b3fe

	measure '% Completion_sinai_Telehealth' = DIVIDE( [# Appt Telehealth], [# Appt In-Person]+[# Appt Telehealth] )
		formatString: 0%;-0%;0%
		displayFolder: _MtSinai
		lineageTag: e0d2cdb2-f38f-4b77-821b-f01200bf55bd

	measure '% Conversion_sinai' = DIVIDE([# Converted_Full],  [Leads])
		formatString: 0\ %;-0\ %;0\ %
		displayFolder: _MtSinai
		lineageTag: aa23f053-1aae-4d6a-bf64-1915fd622acd

	measure '% PsychiatricOnlyVisits' = [# PsychiatricOnlyVisits] / [# TotalVisits]
		formatString: 0%;-0%;0%
		displayFolder: _MtSinai
		lineageTag: a5b36f3f-7438-4cf2-a3f3-f3d5113ed002

	measure '% PsychiatricVisits' = [# PsychiatricVisits] / [# TotalVisits]
		formatString: 0%;-0%;0%
		displayFolder: _MtSinai
		lineageTag: 0a607a70-a0a7-43da-b82e-fb3b14038a22

	measure '% TherapyOnlyVisits' = [# TherapyOnlyVisits] / [# TotalVisits]
		formatString: 0%;-0%;0%
		displayFolder: _MtSinai
		lineageTag: c479f049-cd00-4f60-bdd6-0a06eed3d7a3

	measure '% TherapyVisits' = [# TherapyVisits] / [# TotalVisits]
		formatString: 0%;-0%;0%
		displayFolder: _MtSinai
		lineageTag: 629dc06c-8c5b-4d17-9229-64e707c394a5

	measure 'Avg BothVisits' = [# BothVisits] / [# PatientBoth]
		displayFolder: _MtSinai
		lineageTag: f1729013-7cb3-4ab1-aacb-018c1c09e523

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg PsychiatricVisits' = [# PsychiatricOnlyVisits] / [# PatientPsychiatric]
		displayFolder: _MtSinai
		lineageTag: e1ccd1f8-9cbc-4ab2-9abc-7fb858760ce4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg TherapyVisits' = [# TherapyOnlyVisits] / [# PatientTherapy]
		displayFolder: _MtSinai
		lineageTag: 4d6f0def-9691-46f7-a4d3-da962894f52a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Leads = COUNT( 'vwCollectiveLead'[LeadStatus] )
		formatString: #,0
		displayFolder: _MtSinai
		lineageTag: bce14ce2-233b-4ca8-b430-9bb35e911e96

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'No Line' = BLANK()
		displayFolder: _MtSinai
		lineageTag: 94ddee58-59c4-4f4e-89c1-b55f626674cb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '# InPersonVisitsCancelNoShow' =
			
			CALCULATE(
			    SUM('vwCollectiveLead'[InPersonVisits]),
			    FILTER('vwCollectiveLead','vwCollectiveLead'[FirstVisitStatus] IN {"No Show", "Cancel"})
			)
		displayFolder: _MtSinai
		lineageTag: 2230333d-80ea-432c-b0e8-504c93e4ca9b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '# PatientBoth' =
			
			CALCULATE(
			        [# Patient],
			        FILTER('vwCollectiveLead','vwCollectiveLead'[PatientCategory]="Both")
			        )
		formatString: 0
		displayFolder: _MtSinai
		lineageTag: f8ba8bff-655d-46c0-8324-44ae4de601b5

	measure '# PatientPsychiatric' =
			
			CALCULATE(
			        [# Patient],
			        FILTER('vwCollectiveLead','vwCollectiveLead'[PatientCategory]="Psychiatry")
			        )
		formatString: 0
		displayFolder: _MtSinai
		lineageTag: 62a4fe81-061a-43c2-8907-f456f4b8b62c

	measure '# PatientTherapy' =
			
			CALCULATE(
			        [# Patient],
			        FILTER('vwCollectiveLead','vwCollectiveLead'[PatientCategory]="Therapy")
			        )
		formatString: 0
		displayFolder: _MtSinai
		lineageTag: 67d5a800-bfa4-4ff9-97c2-5842ce89f770

	measure '# PsychiatricVisitsBoth' =
			
			CALCULATE(
			        [# PsychiatricVisits],
			        FILTER('vwCollectiveLead','vwCollectiveLead'[PatientCategory]="Both")
			        )
		formatString: 0
		displayFolder: _MtSinai
		lineageTag: 54fe1643-8673-4254-93c9-71d6490acd06

	measure '# TelehealthVisitsCancelNoShow' =
			
			CALCULATE(
			    SUM('vwCollectiveLead'[TeleVisits]),
			    FILTER('vwCollectiveLead','vwCollectiveLead'[FirstVisitStatus] IN {"No Show", "Cancel"})
			)
		formatString: 0
		displayFolder: _MtSinai
		lineageTag: 92a7f191-b7b9-4ee3-92c7-3ccd6f67d9fd

	measure '# TherapyVisitsBoth' =
			
			CALCULATE(
			        [# TherapyVisits],
			        FILTER('vwCollectiveLead','vwCollectiveLead'[PatientCategory]="Both")
			        )
		formatString: 0
		displayFolder: _MtSinai
		lineageTag: 547af2e7-cd37-46d7-907e-84f5ab18f362

	measure '% InPerson Cancellation/No Show' = [# InPersonVisitsCancelNoShow] / [# Appt In-Person]
		formatString: 0%;-0%;0%
		displayFolder: _MtSinai
		lineageTag: 9858b874-18fe-4fff-aad9-9fe373d6f518

	measure '% Telehealth Cancellation/No Show' = [# TelehealthVisitsCancelNoShow] / [# Appt Telehealth]
		formatString: 0%;-0%;0%
		displayFolder: _MtSinai
		lineageTag: 3c6472a6-8dce-4c78-8821-64ef0ecc6622

	measure 'Avg BothPsychiatricVisits' = [# PsychiatricVisitsBoth] / [# PatientBoth]
		displayFolder: _MtSinai
		lineageTag: d937cf37-c86b-4115-a41a-006a7303a3c3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg BothTherapyVisits' = [# TherapyVisitsBoth] / [# PatientBoth]
		displayFolder: _MtSinai
		lineageTag: 29d17989-02d8-4f26-a3fe-4dc2ba31ff5c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure __Dates = MIN(cfgPayPeriodDetailed[Date]) & " - " & MAX(cfgPayPeriodDetailed[Date])
		displayFolder: _Payroll
		lineageTag: a66a9bfb-8697-4de8-8abd-ebdefe7578d9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '# ClaimDenials' = DISTINCTCOUNT(vwClaimDenials[ChargeID])
		formatString: 0
		displayFolder: _Daily Operations
		lineageTag: 9b77e84c-5368-4a5e-8117-7e9ae765460c

	measure '% Privia' = DIVIDE ( [Privia Referrals], [Total Leads-Referrals], "-" )
		formatString: 0%;-0%;0%
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: 86ae7c66-40f2-42a2-b3a5-d844c14ea066

	measure '% Non-Privia Leads_ MD' = DIVIDE ( [Non-Privia Leads_ MD], [Total Leads-Referrals_ MD], "-" )
		formatString: 0%;-0%;0%
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: 98b2fbb3-7d19-4cfc-8873-bd4ef3a10b8a

	measure BlankBlank = Blank()
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: ec33f6b9-d888-4a86-ba2e-1ca6a17f6a7c

	measure 'Total Leads-Referrals' = [Non-Privia Leads] + [Privia Referrals]
		formatString: #,0
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: 1a287adf-e960-4658-ac15-2fc5e72db716

	measure 'Non-Privia Leads' = [# Leads]
		formatString: #,0
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: 6493f922-5be3-4266-8a73-69c1ac42d91c

	measure 'Privia Referrals' = [Referrals Total]
		formatString: #,0
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: 608ce92c-42b8-4a4a-83e3-b72584e80bae

	measure 'Non-Privia Conversions' = ```
			    [# Converted]
			```
		formatString: #,0
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: 762f1272-d518-451e-b2bc-c2abb25cf01d

	measure 'Privia Conversion' = [__Referrals Converted]
		formatString: #,0
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: 01e0ef0c-d321-4eca-9b8d-68d79814747c

	measure '% Non-Privia Conversion' = DIVIDE ( [Non-Privia Conversions], [Non-Privia Leads], "-" )
		formatString: 0%;-0%;0%
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: 710c811e-9d55-40a6-be7f-4bc6573c0571

	measure '% Privia Conversion' = DIVIDE ( [Privia Conversion], [Privia Referrals], "-" )
		formatString: 0%;-0%;0%
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: 1ca9d091-9ea2-4d0a-abf3-70b38a5d5835

	measure 'Total Conversion' = [Non-Privia Conversions] + [Privia Conversion]
		formatString: #,0
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: d82cb116-ebcc-481d-a309-06602ea35f4b

	measure '% Total Conversion' = DIVIDE ( [Total Conversion] , [Total Leads-Referrals], "-" )
		formatString: 0%;-0%;0%
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: c5d11f52-efb0-492c-a348-78146916d19b

	measure 'Title_Referral Summary' = ```
			"Referral Summary" 
			```
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: 960468f5-4f43-462f-a016-58ca5a202536

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Title_Mid-Atlantic = "Mid-Atlantic"
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: 72f01801-8d7f-4070-890d-95ab289ba2fa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Title_Gulf Coast' = "Gulf Coast"
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: 83c78e56-0f47-41d9-8901-0c620e699ddc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Privia_Referrals_TX =
			
			CALCULATE(
			    [Privia Referrals],
			    vwReferralConversion[Receiving Prvdr State] = "TX")
		formatString: #,0
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: 1e43a9e2-7979-49d8-a5ce-38f5e5b66057

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Privia_Referrals_MD =
			
			CALCULATE(
			    [Privia Referrals],
			    vwReferralConversion[Receiving Prvdr State] = "MD")
		formatString: #,0
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: cbf1c0a8-331b-4f04-a53d-3343967f5b55

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Privia Conversion_ TX' =
			
			CALCULATE(
			    [__Referrals Converted],
			    vwReferralConversion[Receiving Prvdr State] = "TX"
			)
		formatString: #,0
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: d15ae623-e13d-409e-9b5f-1982c1b5c023

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Privia Conversion_ MD' =
			
			CALCULATE(
			    [__Referrals Converted],
			    vwReferralConversion[Receiving Prvdr State] = "MD"
			)
		formatString: #,0
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: f79c7e43-fdf3-4982-bf98-e8e1b0ac97f7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Conversion_ MD' = [Non-Privia Conversions_ MD] + [Privia Conversion_ MD]
		formatString: #,0
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: eb37b1fa-c7d1-4a57-b5c5-8c438fac076b

	measure 'Total Conversion_ TX' = [Non-Privia Conversions_ TX] + [Privia Conversion_ TX]
		formatString: #,0
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: 2a40abe5-3c47-4efa-aac0-48cba0814d5c

	measure 'Total Leads-Referrals_ MD' = [Non-Privia Leads_ MD] + [Privia_Referrals_MD]
		formatString: #,0
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: 42f463a1-1bc3-4d8f-8cbe-04f10edae14c

	measure 'Total Leads-Referrals_ TX' = [Non-Privia Leads_ TX] + [Privia_Referrals_TX]
		formatString: #,0
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: 0cc92d45-0fb5-43fb-b444-b92b50e32499

	measure 'Non-Privia Leads_ MD' =
			CALCULATE(
			    [# Leads],
			    vwCollectiveLead[Market] IN {"DC","MD","VA"},
			    vwCollectiveLead[LeadSource] <> "eFax"
			)
		formatString: #,0
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: abf354cd-ee22-4652-8ef5-03f073460979

	measure 'Non-Privia Leads_ TX' =
			CALCULATE(
			    [# Leads],
			    vwCollectiveLead[Market] IN {"TX"},
			    vwCollectiveLead[LeadSource] <> "eFax"
			)
		formatString: #,0
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: 46bb6c2d-4f37-4a06-a8b7-2284adf85170

	measure 'Non-Privia Conversions_ MD' =
			CALCULATE(
			    [# Converted],
			    vwCollectiveLead[Market] IN {"DC","MD","VA"}
			)
		formatString: #,0
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: a95f9c7f-c4df-4ad9-9728-0b3e04a0b379

	measure 'Non-Privia Conversions_ TX' =
			CALCULATE(
			    [# Converted],
			    vwCollectiveLead[Market] IN {"TX"}
			)
		formatString: #,0
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: 42d47393-6a67-403c-bf72-937c5a686b9b

	measure '% Non-Privia Leads_ TX' = DIVIDE ( [Non-Privia Leads_ TX], [Total Leads-Referrals_ TX], "-" )
		formatString: 0%;-0%;0%
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: a6485a07-6eda-412f-bc89-93c9ff66adbd

	measure '% Privia_ MD' = DIVIDE ( [Privia_Referrals_MD], [Total Leads-Referrals_ MD], "-" )
		formatString: 0%;-0%;0%
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: 359bb524-ce62-4e2f-a159-d7486c7563b0

	measure '% Privia_ TX' = DIVIDE ( [Privia_Referrals_TX], [Total Leads-Referrals_ TX], "-" )
		formatString: 0%;-0%;0%
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: 114be342-a3e5-4817-b12f-ed7db9dfc963

	measure 'Budget Intakes_ MD' =
			CALCULATE(
			    [DayVisComp - DailyBudget - Total - Intake],
			    cfgDailyBudget[Market] = "MD"
			)
		formatString: #,0
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: 3c6d23ba-b223-465f-85ba-62850e242e43

	measure 'Budget Intakes_ TX' =
			CALCULATE(
			    [DayVisComp - DailyBudget - Total - Intake],
			    cfgDailyBudget[Market] = "TX"
			)
		formatString: #,0
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: 4882aed0-608e-4001-9ddb-6c787c14e4d5

	measure '% Total Conversion_ MD' = DIVIDE ( [Total Conversion_ MD] , [Total Leads-Referrals_ MD], "-" )
		formatString: 0%;-0%;0%
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: dc2b3193-3825-4f8c-b29a-bc69b457ac84

	measure '% Total Conversion_ TX' = ```
			DIVIDE ( [Total Conversion_ TX] , [Total Leads-Referrals_ TX], "-" )
			
			```
		formatString: 0%;-0%;0%
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: 5791152d-7c4c-4197-af63-e7b0cc18435f

	measure '% Privia Conversion_ TX' = DIVIDE ( [Privia Conversion_ TX], [Privia_Referrals_TX], "-" )
		formatString: 0%;-0%;0%
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: 446d9847-b3ae-4d6a-9d27-379c7dc5b7c6

	measure '% Privia Conversion_ MD' = DIVIDE ( [Privia Conversion_ MD], [Privia_Referrals_MD], "-" )
		formatString: 0%;-0%;0%
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: bdd2d6da-fcb4-45e6-be12-d2b36035b21c

	measure '% Non-Privia Conversion_ MD' = DIVIDE ( [Non-Privia Conversions_ MD], [Non-Privia Leads_ MD], "-" )
		formatString: 0%;-0%;0%
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: 601b2b3f-f144-4db3-bfd9-3fe543cbaba2

	measure '% Non-Privia Conversion_ TX' = DIVIDE ( [Non-Privia Conversions_ TX], [Non-Privia Leads_ TX], "-" )
		formatString: 0%;-0%;0%
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: 5cc37a54-39bc-44cb-9c45-f6c382e2f98c

	measure Privia_Referrals_MD_YTD = ```
			
			TOTALYTD(
			    [Privia_Referrals_MD], 
			    dimDate[Date]
			)
			```
		formatString: 0
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: 82f1799a-d837-4b10-8549-7048842e95f4

	measure CardOnFile% = [CardOnFileTotal]/[OpsPerf-VisitTotal]
		formatString: 0%;-0%;0%
		displayFolder: _OperationsPerformance
		lineageTag: 2bde5179-c678-48fc-84c7-61ef2f3e4556

	measure CardOnFileTotal = sum(vwOperationsPerf[CardOnFile])
		displayFolder: _OperationsPerformance
		lineageTag: ae38ddc4-3e50-4319-89f1-dd5bcd76b903

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure CoPayCollected% = [CoPayCollectedTotal]/[OpsPerf-VisitTotal]
		formatString: 0%;-0%;0%
		displayFolder: _OperationsPerformance
		lineageTag: 67547ef3-6532-4396-a278-6e3b45e99d53

	measure CoPayCollectedTotal = sum(vwOperationsPerf[CopayCollected])
		displayFolder: _OperationsPerformance
		lineageTag: a21e2740-8bcb-4ba2-a965-54466e8ca344

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DaysToCloseGT2% = [DaysToCloseGT2Total]/[OpsPerf-VisitTotal]
		formatString: 0%;-0%;0%
		displayFolder: _OperationsPerformance
		lineageTag: 5c5594ab-39fc-4a9e-90c1-e0ff4b80f539

	measure DaysToCloseGT2Total = sum(vwOperationsPerf2[DaysToCloseGT2])
		displayFolder: _OperationsPerformance
		lineageTag: 70672d22-e055-4713-9aed-b64b4151d63d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DenialAmountTotal = sum(vwOperationsPerf3[DenialAmount])
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _OperationsPerformance
		lineageTag: c81dd7e2-094a-4411-854a-cbe72b2f050a

	measure Eligibility% = [EligibilityTotal]/[OpsPerf-VisitTotal]
		formatString: 0%;-0%;0%
		displayFolder: _OperationsPerformance
		lineageTag: 8076c863-6f23-49a5-b91a-d43a310f577c

	measure EligibilityTotal = sum(vwOperationsPerf[EligibilityChecked])
		displayFolder: _OperationsPerformance
		lineageTag: d450540c-59a6-4254-8961-05fd89fa7b03

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure OpsPerf-VisitTotal = sum(vwOperationsPerf[TotalVisits])
		displayFolder: _OperationsPerformance
		lineageTag: 43e9147d-2c41-47cd-b80c-a5fc70b6654d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Responsibility% = [ResponsibilityTotal]/[OpsPerf-VisitTotal]
		formatString: 0%;-0%;0%
		displayFolder: _OperationsPerformance
		lineageTag: 5070e85e-c23c-4362-8702-bd9add270dcd

	measure ResponsibilityTotal = sum(vwOperationsPerf[TotalResponsibility])
		displayFolder: _OperationsPerformance
		lineageTag: e35fdb0c-a8ac-4dc7-9781-5bebc29b80cd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure #PatientsFollowUp = COUNTROWS(vwPatientFollowUp)
		displayFolder: _Daily Operations
		lineageTag: 81b092bb-8053-4be4-9350-228d70c7fe61

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure CurrentOpenEncounters = sum(vwOperationsPerf2[TotalNotClosed])
		displayFolder: _OperationsPerformance
		lineageTag: ad8b8010-7ff5-495f-b6a3-6ddb1dde2016

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '# Days for First Appt Average' =
			
			CALCULATE(
			    AVERAGE(vwCollectiveLead[DaysToFirstVisit]),
			    FILTER('vwCollectiveLead',vwCollectiveLead[FirstVisitStatus]="Completed")
			)
		displayFolder: _MtSinai
		lineageTag: 9b45c78a-22da-4524-8154-2c8e202c1d76

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_Active Range Age' = SUM ( 'vwPanelAge'[ActiveRangeAge] )
		formatString: #,0
		displayFolder: _Panel\Age Distribution
		lineageTag: 522560ed-093b-46e9-935b-07a23966d729

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_Total Range Age' = ```
			SUM ( 'vwPanelAge'[TotalRangeAge] )
			
			```
		formatString: #,0
		displayFolder: _Panel\Age Distribution
		lineageTag: 281e5be3-ff1c-4c13-b3e1-9fd2197edd9a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_Active Condition' = ```
			SUM ( 'vwPanelDisorders'[ActiveDisorderCount] )
			
			```
		formatString: #,0
		displayFolder: _Panel\Condition Distribution
		lineageTag: d9f2667e-e583-4541-9721-66cc271b623f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_Total Condition' = ```
			SUM ( 'vwPanelDisorders'[TotalDisorderCount] )
			
			```
		formatString: #,0
		displayFolder: _Panel\Condition Distribution
		lineageTag: 5a78c256-304c-4269-a718-f769ba87d798

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_Active Gender Panel' = ```
			SUM ( 'vwPanelGender'[ActivePanel] )
			
			```
		formatString: #,0
		displayFolder: _Panel\Gender
		lineageTag: 2c8f106d-b97f-45bc-9155-56fc0c3461ea

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_Total Gender Panel' = ```
			SUM ( 'vwPanelGender'[TotalPanel] )
			
			```
		formatString: #,0
		displayFolder: _Panel\Gender
		lineageTag: 24e35b8c-f198-44a9-83c4-c521b7a17aaa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_Active Retention' = ```
			SUM ( 'vwPanelRetention'[ActiveCount] )
			
			```
		formatString: #,0
		displayFolder: _Panel\Patient Retention
		lineageTag: c8ba616f-eb37-47fe-a9d7-31a08aeeb9a6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_Total Retention' = SUM ( 'vwPanelRetention'[TotalCount] )
		formatString: #,0
		displayFolder: _Panel\Patient Retention
		lineageTag: 78d51e1a-5db9-4719-a0f1-078f3c95396e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_Active Top' = ```
			SUM ( 'vwPanelTotals'[ActivePanel] )
			
			```
		formatString: #,0
		displayFolder: _Panel\Top metrics
		lineageTag: 6f5f96f2-168e-46ef-825b-7d7e81287f4c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_Total Top' = ```
			SUM ( 'vwPanelTotals'[TotalPanel] )
			
			```
		formatString: #,0
		displayFolder: _Panel\Top metrics
		lineageTag: 288899d4-50d6-4965-a696-a7fa51a87d21

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_Active Mix' = SUM ( 'vwPanelVisitType'[ActiveVisits] )
		formatString: #,0
		displayFolder: _Panel\Virtual Mix
		lineageTag: bea3ab9d-6f7e-4ec9-a018-f1f116228306

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_Total Mix' = SUM ( 'vwPanelVisitType'[TotalVisits] )
		formatString: #,0
		displayFolder: _Panel\Virtual Mix
		lineageTag: c6d71b02-4251-4ca9-ac37-f98381c90168

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_Active Avg Visits' = ```
			DIVIDE(
			    SUM ( 'vwPanelAvgVisits'[ActiveVisits] ) , 
			    SUM ( 'vwPanelAvgVisits'[ActivePanel] )
			    )
			```
		formatString: #,0
		displayFolder: _Panel\Visits / Patients
		lineageTag: d33b190f-9c22-42c5-bba0-839129e28d7e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_Total Avg Visits' = ```
			
			DIVIDE(
			    SUM ( 'vwPanelAvgVisits'[TotalVisits] ) , 
			    SUM ( 'vwPanelAvgVisits'[TotalPanel] )
			    )
			```
		formatString: #,0
		displayFolder: _Panel\Visits / Patients
		lineageTag: 8a8ceea6-8c0d-48cd-b714-5211c8214a0d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '# Scheduled Appt - Psy' =
			
			CALCULATE (
			        DISTINCTCOUNT( vwScheduleVisitDetails[VisitID] ),
			        'vwScheduleVisitDetails'[VisitStatusID] in {1,2,3,7},
			        'vwResourceDetails'[ProviderCategoryID] in {2}
			)
		displayFolder: _Operations\FrontDesk
		lineageTag: 8220efab-979e-4289-8093-1668f189e6cd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '# Scheduled Appt - Th' =
			
			CALCULATE (
			        DISTINCTCOUNT( vwScheduleVisitDetails[VisitID] ),
			        'vwScheduleVisitDetails'[VisitStatusID] in {1,2,3,7},
			        'vwResourceDetails'[ProviderCategoryID] in {1,3}
			)
		displayFolder: _Operations\FrontDesk
		lineageTag: 526f906a-eedf-473a-9f61-cb55dd237297

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '# Scheduled Appt Total' = [# Scheduled Appt - Th] + [# Scheduled Appt - Psy]
		displayFolder: _Operations\FrontDesk
		lineageTag: bee7f6fa-86fa-4a99-a7d5-a5fbd9d6ac1a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FTE Ratio' = 40
		displayFolder: _Operations\FrontDesk
		lineageTag: 122c395d-1f7f-4acd-840f-4e307e83d54f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure FTE = [# Scheduled Appt Total] / [FTE Ratio]
		displayFolder: _Operations\FrontDesk
		lineageTag: 88d03a17-cd26-4a47-ade8-091794a1705f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FTE Total' =
			
			var SelectedWeek = IF (SELECTEDVALUE(dimDate[Slicer Current Week]) = "Current Week"
			                        ,TODAY () - WEEKDAY (TODAY (), 3) + 4
			                        ,SELECTEDVALUE(dimDate[Slicer Current Week])
			                        )
			
			var BusinessDays = CALCULATE(
			                        [#BusinessDays]
			                        ,cfgWeekDays[EndWeek] = CONVERT(SelectedWeek,DATETIME)
			                        )
			
			return [# Scheduled Appt Total]/([FTE Ratio]*BusinessDays)
		displayFolder: _Operations\FrontDesk
		lineageTag: 6027c645-fd9b-41f6-9080-d09e1e775789

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Complete =
			
			CALCULATE(
			    COUNT(vwEncounterPayrollReducedCombined[EncounterID]),
			    vwEncounterPayrollReducedCombined[FlagClosed] = 1,
			    vwEncounterPayrollReducedCombined[VisitStatus] = "Check Out"
			    )
		formatString: #,0
		displayFolder: _Panel\Second Page
		lineageTag: 23f7d674-fc60-490a-879b-232e585e9725

	measure Follow-ups =
			
			CALCULATE (
			    COUNTROWS ( 'vwEncounterPayrollReducedCombined' ),
			    FILTER ( 'vwEncounterPayrollReducedCombined', [VisitTypeGroup] = "FollowUp" )
			)
			--vwEncounterPayroll_PRV
		formatString: #,0
		displayFolder: _Panel\Second Page
		lineageTag: be18a48e-8148-44b2-ac71-447855c4d84d

	measure Intakes =
			
			CALCULATE (
			    COUNTROWS ( 'vwEncounterPayrollReducedCombined' ),
			    FILTER ( 'vwEncounterPayrollReducedCombined', [VisitTypeGroup] = "Intake" )
			)
		formatString: #,0
		displayFolder: _Panel\Second Page
		lineageTag: 4171ff7f-9610-420b-ba7a-8af3c928f688

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'No Shows' =
			
			CALCULATE (
			    COUNTROWS ( 'vwEncounterPayrollReducedCombined' ),
			    FILTER ( 'vwEncounterPayrollReducedCombined', [VisitTypeGroup] = "NoShow" )
			)
		formatString: #,0
		displayFolder: _Panel\Second Page
		lineageTag: 32b74cb0-cd8b-4e21-9935-4a2eddd5a315

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Outstanding =
			
			CALCULATE(
			    COUNT(vwEncounterPayrollReducedCombined[visitid]),
			    vwEncounterPayrollReducedCombined[FlagClosed] = 0,
			    vwEncounterPayrollReducedCombined[VisitStatus] = "Check Out"
			    )
		formatString: #,0
		displayFolder: _Panel\Second Page
		lineageTag: 3f8d6e4c-a847-4ecc-bf13-915c17b6c832

	measure 'Avg Last Score' = ```
			AVERAGE( 
			    'vwPanelSurveys'[AvgLatest]
			    )
			```
		displayFolder: _Panel\Surveys
		lineageTag: 34bc1ab3-bdef-442d-8d21-93e6e4b0ed2d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Starting Score' = ```
			AVERAGE( 
			    'vwPanelSurveys'[AvgStarting]
			    )
			```
		displayFolder: _Panel\Surveys
		lineageTag: 2fd62df7-0af4-4be2-b482-7d6e854b16af

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PatientBalance = sum(vwProviderPatientBalance[Total])
		displayFolder: _ProviderPatientBalance
		lineageTag: 226568e7-0c87-434b-9b6a-07049df87286

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '# 60FU' = sum(vwProviderUtilization[FollowUp60])
		formatString: 0
		displayFolder: _Operations\_Utilizationv2
		lineageTag: 5fa62a3d-ba0a-40dc-a0bf-4ebc2a404a07

	measure '# 60FU YTD' =
			
			TOTALYTD(
			    [# 60FU],
			    dimDate[Date]
			)
		formatString: 0
		displayFolder: _Operations\_Utilizationv2
		lineageTag: 651063ca-796f-4379-9dad-12bbcb801311

	measure '# Actuals' = sum(vwProviderUtilization[Actual])
		displayFolder: _Operations\_Utilizationv2
		lineageTag: b50be916-ff83-43f4-b083-a0579956d1ae

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '# Actuals YTD' =
			
			TOTALYTD(
			    [# Actuals],
			    dimDate[Date]
			)
		displayFolder: _Operations\_Utilizationv2
		lineageTag: f98ca51f-f064-42c7-891a-e1d1df5b6dbd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '# FU' = sum(vwProviderUtilization[FollowUp])
		displayFolder: _Operations\_Utilizationv2
		lineageTag: 47aa7a31-c66e-481e-b5c1-8d68b496ccc9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '# FU YTD' =
			
			TOTALYTD(
			    [# FU],
			    dimDate[Date]
			)
		displayFolder: _Operations\_Utilizationv2
		lineageTag: a42eacac-97f3-49a7-a4a4-abdf89ceb393

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '# PTO' = SUM(vwProviderUtilization[PTO])
		displayFolder: _Operations\_Utilizationv2
		lineageTag: 3684c79c-0881-4eba-a5e3-16345ba4b01d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '# PTO YTD' =
			
			TOTALYTD(
			    [# PTO],
			    dimDate[Date]
			)
		displayFolder: _Operations\_Utilizationv2
		lineageTag: 696b4115-439e-4087-ab8b-907eceaa4a21

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '# Target' = sum(vwProviderUtilization[Goal])
		displayFolder: _Operations\_Utilizationv2
		lineageTag: 7fcff348-d7f2-45b9-9b1e-87ef9af7ac57

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '# Target YTD' =
			
			TOTALYTD(
			    [# Target],
			    dimDate[Date]
			)
		displayFolder: _Operations\_Utilizationv2
		lineageTag: aa43fdb4-f90a-40f9-b977-b24635c94072

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '# Worked' = sum(vwProviderUtilization[Worked])
		displayFolder: _Operations\_Utilizationv2
		lineageTag: 51603c42-018d-4bef-9857-a68bd50ad299

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '# Worked YTD' = ```
			
			TOTALYTD(
			    [# Worked], 
			    dimDate[Date]
			)
			```
		displayFolder: _Operations\_Utilizationv2
		lineageTag: d5a5cef0-8716-4f21-a2b2-64a16913d6d6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% 60FU' = [# 60FU] / [# FU]
		displayFolder: _Operations\_Utilizationv2
		lineageTag: 75361268-1197-4e62-b77c-21168ab622bb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% 60FU YTD' = [# 60FU YTD] / [# FU YTD]
		displayFolder: _Operations\_Utilizationv2
		lineageTag: 45d45929-7418-4ae0-bd68-0b0bb2803464

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Utilization v2' = DIVIDE([# Actuals], [# Target])
		displayFolder: _Operations\_Utilizationv2
		lineageTag: 2dd57732-0de5-489d-8dc9-2904b523a109

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Utilization v2 YTD' = DIVIDE([# Actuals YTD], [# Target YTD])
		displayFolder: _Operations\_Utilizationv2
		lineageTag: bab732c1-2996-4e4b-ae48-62b2275891f9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'YTD Title Year' = CONCATENATE(VALUES(dimDate[Slicer Month Previous])," - YTD")
		displayFolder: _Operations\_Utilizationv2
		lineageTag: 67f23fe4-4ac7-4c47-875c-60339e448634

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_% Active Retention' = ```
			
			DIVIDE( 
			    [_Active Retention] ,
			    [_Active Top],
			    0
			)
			```
		formatString: 0%;-0%;0%
		displayFolder: _Panel\Patient Retention
		lineageTag: 6cc968d4-fe79-422e-9a27-781c285bc5cf

	measure '_% Total Retention' =
			
			DIVIDE (
			    [_Total Retention],
			    [_Total Top],
			    0
			)
		formatString: 0%;-0%;0%
		displayFolder: _Panel\Patient Retention
		lineageTag: 8db36d32-5fed-41aa-8a5a-e72fc5433982

	measure FTECustom =
			
			IF (
			    --HASONEVALUE('vwResourceDetails'[PreferredFacility]) && HASONEVALUE(vwResourceDetails[Market])&& HASONEVALUE(vwScheduleVisitDetails[VisitDate]) ,
			    HASONEVALUE(vwScheduleVisitDetails[VisitDate]) ,
			    [FTE],
			    [FTE Total]
			    )
		displayFolder: _Operations\FrontDesk
		lineageTag: 5a8204a1-71be-4b1c-86a9-f7ec936af241

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure AddOn = sum(vwProviderUtilization[AddOn])
		displayFolder: _Operations\_Utilizationv2
		lineageTag: e2078343-f46c-4890-9582-c8e2c043f0ef

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AddOn YTD' =
			
			TOTALYTD(
			    [AddOn],
			    dimDate[Date]
			)
		displayFolder: _Operations\_Utilizationv2
		lineageTag: adc0c0fc-a628-4d65-aa30-26d8f12b78d1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unique Patients' =
			
			SUM(vwProviderCaseLoad[UniquePats])
		formatString: #,0.00
		displayFolder: _Clinical
		lineageTag: 75cbdc7b-b61f-4cd9-b4c2-ce9877983983

	measure CadenceVisit = SUM(vwCadence[CadenceVisit])
		displayFolder: _Clinical
		lineageTag: 06b8ae89-c034-4306-8da1-f74e77b64f8a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure WeeksToToday = SUM(vwCadence[WeeksToToday])
		displayFolder: _Clinical
		lineageTag: 5cf6e601-64ca-47d3-b28d-d949bcee0ad1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Cadence = [WeeksToToday] / [CadenceVisit]
		formatString: 0.0
		displayFolder: _Clinical
		lineageTag: 2e0a1c70-8de4-467a-b476-c2319a772b1e

	measure TotalLeadsNoStatusFilter =
			CALCULATE (
			    [# Not Converted],
			    REMOVEFILTERS ( vwCollectiveLead[LeadStatus] )
			)
		formatString: #,0
		displayFolder: _ProviderPartnership
		lineageTag: 9ec78104-7e04-41c9-a756-5995e804af2a

	measure '# Not Converted for Label' = ```
			VAR _nc = [# Not Converted]
			VAR _monthtotal = [TotalLeadsNoStatusFilter]
			VAR _divi =
			    DIVIDE (
			        _nc,
			        _monthtotal,
			        0
			    )
			RETURN
			    _nc & " | " & FORMAT ( _divi, "0 %" ) 
			```
		displayFolder: _ProviderPartnership
		lineageTag: 4b4e9519-285b-46bb-b567-3a39fe0f2e49

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure #BusinessDays = SUM(cfgWeekDays[BusinessDays])
		displayFolder: _Operations\FrontDesk
		lineageTag: cc59dcf4-da04-412c-9923-49c9df0a0e5f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '# LeadsByPriviaProvider' = ```
			
			 COUNT(
			     'vwLeadsByPriviaProvider'[LeadStatus]
			    )
			```
		formatString: 0
		displayFolder: _LeadsByPriviaProvider
		lineageTag: e7f574d6-4d84-4933-ab42-556b2834e9ea

	measure '# StaleByPriviaProvider' =
			
			calculate(
			    [# LeadsByPriviaProvider],
			    vwLeadsByPriviaProvider[LeadStatus] = "Stale"
			)
		formatString: 0
		displayFolder: _LeadsByPriviaProvider
		lineageTag: 928f5026-d3e2-4b7a-8ff2-7ada8693258d

	measure '# ConvertedByPriviaProvider' =
			
			calculate(
			    [# LeadsByPriviaProvider],
			    vwLeadsByPriviaProvider[LeadStatus] = "Converted"
			)
		formatString: 0
		displayFolder: _LeadsByPriviaProvider
		lineageTag: 3151381e-cfe3-4a64-84ac-7d19a52970ae

	measure '# NeedsFollowUpByPriviaProvider' =
			
			calculate(
			    [# LeadsByPriviaProvider],
			    vwLeadsByPriviaProvider[LeadStatus] = "Needs Follow Up"
			)
		formatString: 0
		displayFolder: _LeadsByPriviaProvider
		lineageTag: c5a1e1a4-414c-4eb4-a198-d38842f2ea0d

	measure '# InsuranceNotAcceptedByPriviaProvider' =
			
			calculate(
			    [# LeadsByPriviaProvider],
			    vwLeadsByPriviaProvider[LeadStatus] = "Insurance Not Accepted"
			)
		formatString: 0
		displayFolder: _LeadsByPriviaProvider
		lineageTag: 73b1276b-3246-4422-ac73-8fb3fe12c7b3

	measure '# FinancialConstraintsByPriviaProvider' =
			
			calculate(
			    [# LeadsByPriviaProvider],
			    vwLeadsByPriviaProvider[LeadStatus] = "Financial Constraints"
			)
		formatString: 0
		displayFolder: _LeadsByPriviaProvider
		lineageTag: 1d3d5a73-e4f3-4a92-954f-339aa7d620e2

	measure '# WaitListByPriviaProvider' =
			
			calculate(
			    [# LeadsByPriviaProvider],
			    vwLeadsByPriviaProvider[LeadStatus] = "Wait List"
			)
		formatString: 0
		displayFolder: _LeadsByPriviaProvider
		lineageTag: 1b68a29d-500d-4ac8-8d07-9384c4e7f628

	measure '# ServicesNotOfferedByPriviaProvider' =
			
			calculate(
			    [# LeadsByPriviaProvider],
			    vwLeadsByPriviaProvider[LeadStatus] = "Services Not Offered"
			)
		formatString: 0
		displayFolder: _LeadsByPriviaProvider
		lineageTag: 59198b45-f8fc-49cd-a243-85c2109654e6

	measure '# NewByPriviaProvider' =
			
			calculate(
			    [# LeadsByPriviaProvider],
			    vwLeadsByPriviaProvider[LeadStatus] = "New"
			)
		formatString: 0
		displayFolder: _LeadsByPriviaProvider
		lineageTag: 23157881-6f39-4f62-b4e4-d6bf16047df9

	measure '# TotalLeadsByPriviaProvider' = [# ConvertedByPriviaProvider] + [# FinancialConstraintsByPriviaProvider] + [# InsuranceNotAcceptedByPriviaProvider] + [# NeedsFollowUpByPriviaProvider] + [# NewByPriviaProvider] + [# ServicesNotOfferedByPriviaProvider] + [# StaleByPriviaProvider] + [# WaitListByPriviaProvider]
		formatString: 0
		displayFolder: _LeadsByPriviaProvider
		lineageTag: 2f40f370-7966-4c93-8f95-fc95e98a7df4

	measure '# Completed - Intake - Psy - Comb - ByProv' = ```
			
			    SUM(vwDailySalesCombinedByProvider[PsyIntVis])
			```
		displayFolder: _Finance\_DailySalesByProv
		lineageTag: c1f4ca26-cbf4-4b16-adfe-817f68017db7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '# Completed - Intake - Th - Comb - ByProv' = ```
			
			    SUM(vwDailySalesCombinedByProvider[ThrIntVis])
			```
		displayFolder: _Finance\_DailySalesByProv
		lineageTag: 7b84f9dd-3ac2-47cb-88bf-f1e652462e41

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '# Completed - FU Patient - Psy - Comb - ByProv' = ```
			
			    SUM(vwDailySalesCombinedByProvider[PsyFupVis])
			```
		displayFolder: _Finance\_DailySalesByProv
		lineageTag: d22e4358-5de9-49ce-b2eb-05b42a3f36aa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '# Completed - FU Patient - Th - Comb - ByProv' = ```
			
			    SUM(vwDailySalesCombinedByProvider[ThrFupVis])
			```
		displayFolder: _Finance\_DailySalesByProv
		lineageTag: 96c762ff-95a9-4278-96d0-9ac26c3ded5a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '# Completed - Total - Comb - ByProd' =
			[# Completed - FU Patient - Psy - Comb - ByProv] +
			[# Completed - FU Patient - Th - Comb - ByProv] +
			[# Completed - Intake - Psy - Comb - ByProv] +
			[# Completed - Intake - Th - Comb - ByProv]
		displayFolder: _Finance\_DailySalesByProv
		lineageTag: ddea9807-633b-4774-a441-60844a978b77

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Revenue Visits - Total - Comb - ByProv' = ```
			
			    SUM(vwDailySalesCombinedByProvider[PsyFupRev]) + SUM(vwDailySalesCombinedByProvider[PsyIntRev]) + SUM(vwDailySalesCombinedByProvider[ThrFupRev]) + SUM(vwDailySalesCombinedByProvider[ThrIntRev])
			```
		displayFolder: _Finance\_DailySalesByProv
		lineageTag: 0f27728b-87b9-4832-9358-f41acfbd2ffa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '# No Show Visits - Comb - ByProv' = ```
			
			    SUM(vwDailySalesCombinedByProvider[NoShowVis])
			```
		displayFolder: _Finance\_DailySalesByProv
		lineageTag: 6a20eee5-4f87-41c5-98c0-f60e4a70c12e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Revenue NoShow - Total - Comb - ByProv' = ```
			
			    SUM(vwDailySalesCombinedByProvider[NoShowRev])
			```
		displayFolder: _Finance\_DailySalesByProv
		lineageTag: 1647cece-aa98-4487-a0e8-7c0cb4b7f39a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure CadenceMedian = MEDIAN(vwCadence[CadenceCol])
		formatString: 0.0
		displayFolder: _Clinical
		lineageTag: c3e0e716-faef-49fe-8c31-77e8b4f81ea4

	measure CadenceMode = ```
			
			
			VAR FilteredData = 
			        FILTER(
			        vwCadence,
			        vwCadence[LastCompletedVisit] >= MIN('dimDate'[Date]) &&
			        vwCadence[LastCompletedVisit] <= MAX('dimDate'[Date])
			                )
			
			VAR FrequencyTable = 
			        SUMMARIZE(
			            FilteredData,
			            vwCadence[CadenceCol],
			            "Frequency", COUNTA(vwCadence[CadenceCol]) 
			                )
			                
			VAR MaxFrequency = MAXX(FrequencyTable, [Frequency])
			
			VAR ModeRows = FILTER(FrequencyTable, [Frequency] = MaxFrequency)
			
			RETURN MAXX(ModeRows, [CadenceCol])
			```
		formatString: 0.0
		displayFolder: _Clinical
		lineageTag: 0ffcf79d-4c92-4513-8922-62aa8a81bc16

	measure CadenceMean = AVERAGE(vwCadence[CadenceCol])
		formatString: 0.0
		displayFolder: _Clinical
		lineageTag: 8ddab209-c421-4444-8cbf-e6cb19423004

	measure '__ Answer Rate' = ```
			
			 DIVIDE(
			    [__ Calls Inbound],
			    [__ Calls Total],
			    0
			 )
			```
		formatString: 0%;-0%;0%
		displayFolder: _TalkDesk
		lineageTag: 5806c0d1-acc9-4cd7-958f-a5a19eb10d63

	measure '__ Calls' = ```
			DISTINCTCOUNT(vwTalkDesk[Interaction_ID]) 
			```
		formatString: #,0
		displayFolder: _TalkDesk
		lineageTag: d8cb7761-13da-4464-9beb-5ea7e33e77cc

	measure '__ Calls Abandoned' = ```
			
			 CALCULATE(
			    [__ Calls],
			    vwTalkDesk[Call_Type] = "abandoned"
			 )
			```
		formatString: #,0
		displayFolder: _TalkDesk
		lineageTag: 08663e97-8bcf-4d07-bf75-3f11df3c0f83

	measure '__ Calls Inbound' = ```
			
			 CALCULATE(
			    [__ Calls],
			    vwTalkDesk[Call_Type] = "inbound"
			 )
			```
		formatString: #,0
		displayFolder: _TalkDesk
		lineageTag: 01269b5f-abf9-4463-aa88-d89aa99b6336

	measure '__ Calls Missed' = ```
			
			 CALCULATE(
			    [__ Calls],
			    vwTalkDesk[Call_Type] = "missed"
			 )
			```
		formatString: #,0
		displayFolder: _TalkDesk
		lineageTag: 91e1f160-06e4-46ec-bb2b-ae39c0f63203

	measure '__ Calls Total' = [__ Calls Abandoned] + [__ Calls Inbound] + [__ Calls Missed] + [__ Calls Voicemail]
		formatString: #,0
		displayFolder: _TalkDesk
		lineageTag: 815ba97c-cfab-488d-8ca3-340364660e54

	measure '__ Calls Voicemail' = ```
			
			 CALCULATE(
			    [__ Calls],
			    vwTalkDesk[Call_Type] = "voicemail"
			 )
			```
		formatString: #,0
		displayFolder: _TalkDesk
		lineageTag: a9691810-506e-45ed-8474-d167639147d0

	measure '__ Talk Time Minutes' = ```
			
			DIVIDE(
			    [__ Talk Time Seconds]
			    , 60 
			    ,0
			)
			```
		formatString: #,0.00
		displayFolder: _TalkDesk
		lineageTag: 1b1cba01-d824-4e3b-81e1-8f56381820c3

	measure '__ Talk Time Seconds' = ```
			
			SUM( vwTalkDesk[Talk_Time_Seconds] ) 
			```
		formatString: #,0.00
		displayFolder: _TalkDesk
		lineageTag: 6a5b76d7-76fd-4530-bb79-387e4a61033f

	measure '# Completed 1' =
			
			CALCULATE ( [# Leads 1], 'vwCollectiveLead - DQ'[CompletionStatus] = "Completed" )
		displayFolder: _Marketing\Inquiry - DQ
		lineageTag: 20c18a46-6875-4788-b6ee-1c0542f9eabd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '# Converted 1' =
			
			calculate(
			    [# Leads 1],
			    'vwCollectiveLead - DQ'[CompletionStatus] = "Converted"
			)
		displayFolder: _Marketing\Inquiry - DQ
		lineageTag: 1f8e9e28-9433-4a88-9bc1-649344851536

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Completion 1' = [# Completed 1] / [# Leads 1]
		displayFolder: _Marketing\Inquiry - DQ
		lineageTag: 3bbe3415-5998-4423-b468-d0cc4848290d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Non-Privia Completed_ MD' =
			CALCULATE(
			    [# Completed],
			    vwCollectiveLead[Market] IN {"DC","MD","VA"}
			)
		formatString: 0
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: a68787c6-c88e-4c5a-9450-a879b46ad152

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Privia Completed_MD' =
			
			CALCULATE(
			    [__Referrals Completed],
			    vwReferralConversion[Receiving Prvdr State] = "MD"
			)
		formatString: 0
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: 8a66715d-4682-4faa-a4a8-89b32c382bdb

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Total Completed_ MD' = [Non-Privia Completed_ MD] + [Privia Completed_MD]
		formatString: 0
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: 32aceb0f-9f8d-488e-a8ec-1584089b4f08

	measure '% Privia Completed_ MD' = DIVIDE ( [Privia Completed_MD], [Privia_Referrals_MD], "-" )
		formatString: 0%;-0%;0%
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: ae437266-f1f2-4008-859d-1051a7996de5

	measure '% Non-Privia Completed_MD' = DIVIDE ( [Non-Privia Completed_ MD], [Non-Privia Leads_ MD], "-" )
		formatString: 0%;-0%;0%
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: 9d4340e4-12fd-411e-b4c2-cc0567a0e423

	measure '% Total Completed_MD' = DIVIDE ( [Total Completed_ MD] , [Total Leads-Referrals_ MD], "-" )
		formatString: 0%;-0%;0%
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: cbd85407-17fd-434d-a8e1-fc8df12f9e96

	measure 'Privia Completed_TX' =
			
			CALCULATE(
			    [__Referrals Completed],
			    vwReferralConversion[Receiving Prvdr State] = "TX"
			)
		formatString: 0
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: ab8df650-4018-4461-9153-de6bb9b94095

	measure 'Non-Privia Completed_ TX' =
			CALCULATE(
			    [# Completed],
			    vwCollectiveLead[Market] IN {"TX"}
			)
		formatString: 0
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: bc50e83b-5e6b-40cc-87d7-024976029257

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Total Completed_TX' = [Non-Privia Completed_ TX] + [Privia Completed_TX]
		formatString: 0
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: 1f81c1b1-b6a5-4b1f-9715-143c91951fd0

	measure '% Privia Completed_ TX' = DIVIDE ( [Privia Completed_TX], [Privia_Referrals_TX], "-" )
		formatString: 0%;-0%;0%
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: 9d672c29-a74f-4352-aa51-0eae65ee206b

	measure '% Non-Privia Completed_TX' = DIVIDE ( [Non-Privia Completed_ TX], [Non-Privia Leads_ TX], "-" )
		formatString: 0%;-0%;0%
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: 0a304f3e-06ad-4b89-a2c7-d85413a9ad9d

	measure '% Total Completed_TX' = DIVIDE ( [Total Completed_TX] , [Total Leads-Referrals_ TX], "-" )
		formatString: 0%;-0%;0%
		displayFolder: _Marketing\Privia vs Non-Privia
		lineageTag: d4425b0b-2453-4023-ac4e-2ba6a15661aa

	measure DaysToFirstVisit = SUM(vwConvNotCplt[DaysToFirstVisit])
		formatString: 0
		displayFolder: _Marketing
		lineageTag: 7db28036-000a-48b2-995e-4d0a1114357f

	measure #Visits = SUM(vwSumProviderTrend[Visits])
		displayFolder: _ClinicalAnalytics
		lineageTag: cfdd5788-5d27-4896-8d56-836b6e7e3eba

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure #Weeks = Count(vwSumProviderTrend[EncounterWeek])
		displayFolder: _ClinicalAnalytics
		lineageTag: f6a1a81b-cfa2-4a5e-82a7-c9e378e907e1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Visits Per Week' = [#Visits] / [#Weeks]
		displayFolder: _ClinicalAnalytics
		lineageTag: d4affc7a-8b2a-43d2-92f1-26b2a070ea32

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '__ Visits Not Closed + Closed Future Period' = ```
			
			 [__Visits Closed Diff Period] + [All time notes not closed]
			```
		displayFolder: _Payroll
		lineageTag: 1901d1cb-53b3-4dd2-b708-7e5d1c9ce8c3

	measure '__Closed Visits in Period' =
			
			VAR _period =
			    SELECTEDVALUE ( cfgPayPeriodDetailed[Period] )
			VAR _Calc =
			    CALCULATE (
			        COUNT ( vwEncounterPayroll[EncounterID] ),
			        FILTER ( ALLEXCEPT( vwEncounterPayroll, vwEncounterPayroll[Market]  ), _period = vwEncounterPayroll[NCDPeriod] )
			    )
			RETURN
			    _Calc
		displayFolder: _Payroll
		lineageTag: 79b76bb0-8be5-4c03-8546-da54bdd14677

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '__Closed Visits in Period _ ALLEXCEPT' = ```
			
			VAR _period = SELECTEDVALUE(cfgPayPeriodDetailed[Period])
			VAR _Calc =
			    CALCULATE( 
			        COUNT(vwEncounterPayroll[EncounterID])
			        , FILTER( ALLEXCEPT(vwEncounterPayroll, vwEncounterPayroll[Market],cfgPayPeriodDetailed[Period]), _period = vwEncounterPayroll[NCDPeriod] )
			    )
			    
			RETURN
			_Calc
			```
		displayFolder: _Payroll
		lineageTag: 67f0a586-2596-4d17-bfe8-697ff4813d52

	measure '__Closed Visits in Period _ ALLSELECTED' =
			
			VAR _period =
			    SELECTEDVALUE ( cfgPayPeriodDetailed[Period] )
			VAR _Calc =
			    CALCULATE (
			        COUNT ( vwEncounterPayroll[EncounterID] ),
			        ALLSELECTED ( vwEncounterPayroll ),
			        vwEncounterPayroll[NCDPeriod] = _period
			    )
			RETURN
			    _Calc
		displayFolder: _Payroll
		lineageTag: 45110c26-d706-4abb-9d9c-ff0d72e0fe99

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '__Closed Visits in Period _ Modified' =
			
			VAR _period =
			    SELECTEDVALUE ( cfgPayPeriodDetailed[Period] )
			VAR _Calc =
			    CALCULATE (
			        COUNT ( vwEncounterPayroll[EncounterID] ),
			        REMOVEFILTERS ( cfgPayPeriodDetailed[Period] ),
			        // Esto elimina los filtros de la columna [Period] en la tabla cfgPayPeriodDetailed
			        ALLSELECTED ( vwEncounterPayroll ),
			        // Esto conserva los filtros seleccionados en otras columnas de vwEncounterPayroll
			        vwEncounterPayroll[NCDPeriod] = _period // Esto aplica el filtro de periodo seleccionado
			    )
			RETURN
			    _Calc
		displayFolder: _Payroll
		lineageTag: 74fa1082-089e-4caa-84dd-ffccd0093d5e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '__Closed Visits in Period _ Modified v2' =
			
			--VAR _period = VALUE(LEFT(SELECTEDVALUE(cfgPayPeriodDetailed[Min Date by Period])))
			VAR _period = SELECTEDVALUE(cfgPayPeriodDetailed[Period])
			RETURN
			CALCULATE(
			    COUNt(vwEncounterPayroll[EncounterID]),
			    ALLEXCEPT(
			        vwEncounterPayroll,
			        vwEncounterPayroll[Clinician],
			        vwEncounterPayroll[Market],
			        vwResourceDetails[PreferredFacility],
			        vwEncounterPayroll[EncounterType],
			        vwEncounterPayroll[VisitStatus],
			        vwResourceDetails[MatureCategory],
			        vwResourceDetails[Status],
			        vwResourceDetails[ProviderCategory],
			        vwProviderCategory[ProviderCategory],
			        vwEncounterPayroll[CPTCode],
			        vwResourceDetails[Full Name]
			    ),
			    vwEncounterPayroll[NCDPeriod] = _period
			)
		displayFolder: _Payroll
		lineageTag: 1fb48d77-c348-40ba-9969-f94f448cf92b

	measure '__CPT % 90837' =
			VAR _main =
			    CALCULATE (
			        COUNTROWS ( 'vwEncounterPayroll' ),
			        FILTER ( 'vwEncounterPayroll', [CPTCode] IN { "90837" } )
			    )
			VAR _other =
			    CALCULATE (
			        COUNTROWS ( 'vwEncounterPayroll' ),
			        FILTER ( 'vwEncounterPayroll', [EncounterType] IN { "(TH) Individual Therapy", "Individual Therapy"} )
			    )
			VAR _result =
			    DIVIDE ( _main, _other, "-" )
			RETURN
			    _result
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: _Payroll
		lineageTag: 0d4a07e8-2678-4bc0-9a44-c2e019beb0b3

	measure '__Total Closed Notes' = [__Visits Closed] + [__Visits Closed Past Periods]
		formatString: 0
		displayFolder: _Payroll
		lineageTag: bae071f6-a5df-4d31-a98b-b7403c864715

	measure '__Visits Closed' =
			
			CALCULATE (
			    COUNT ( vwEncounterPayroll[EncounterID] ),
			    vwEncounterPayroll[NCDFlag] = "Same"
			)
		displayFolder: _Payroll
		lineageTag: 37b5fb45-a309-4052-abbd-28af87825563

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '__Visits Closed Diff Period' =
			
			-- closed in the future
			CALCULATE (
			    COUNT ( vwEncounterPayroll[EncounterID] ),
			    vwEncounterPayroll[NCDFlag] = "Different"
			)
		displayFolder: _Payroll
		lineageTag: aa1dbab1-caaa-425c-ab3c-8fd98a5d2644

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '__Visits Closed Past' = ```
			[__Closed Visits in Period _ Modified v2] - [__Visits Closed] 
			```
		displayFolder: _Payroll
		lineageTag: 642378c3-8cab-47af-a96c-42b53168fed5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '__Visits Closed Past Periods' =
			
			CALCULATE (
			    COUNT ( vwEncounterPayroll[EncounterID] ),
			    vwEncounterPayroll[NCDFlag] = "Different"
			)
		displayFolder: _Payroll
		lineageTag: 42aad1d0-49ff-4e1f-9bb4-325d7e072aa9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '__Visits Count' =
			
			CALCULATE(
			    COUNT ( vwEncounterPayroll[EncounterID] )
			    ,USERELATIONSHIP(vwEncounterPayroll[VisitDate],cfgPayPeriodDetailed[Date]))
		displayFolder: _Payroll
		lineageTag: c561e683-8f42-4069-8b7e-e1088cc2cec4

	measure 'All time notes not closed' = ```
			
			    
			
			CALCULATE(
			    [__Visits Not Closed],
			    ALLEXCEPT(
			        vwEncounterPayroll,
			        vwEncounterPayroll[Clinician],
			        vwEncounterPayroll[Market],
			        vwResourceDetails[PreferredFacility],
			        vwEncounterPayroll[EncounterType],
			        vwEncounterPayroll[VisitStatus],
			        vwResourceDetails[MatureCategory],
			        vwResourceDetails[Status],
			        vwResourceDetails[ProviderCategory],
			        vwProviderCategory[ProviderCategory],
			        vwResourceDetails[Full Name]
			    )
			)
			```
		displayFolder: _Payroll
		lineageTag: 0564122b-d894-4f9a-b959-3ecb58767b9a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '__Visits Not Closed' =
			
			
			CALCULATE (
			    COUNT ( vwEncounterPayroll[EncounterID] ),
			    vwEncounterPayroll[NCDFlag] = "NotClosed",
			    USERELATIONSHIP(vwEncounterPayroll[VisitDate],cfgPayPeriodDetailed[Date])
			)
		displayFolder: _Payroll
		lineageTag: 16003428-d4e2-4eb2-9141-77608ae2708e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '__ Visits Not Closed + Closed Future Period - PRV' = ```
			
			 [__Visits Closed Diff Period - PRV] + [All time notes not closed - PRV]
			```
		displayFolder: _Payroll - PRV
		lineageTag: 0942f768-51ba-4a68-8a30-478d7c8e7276

	measure '__Closed Visits in Period - PRV' =
			
			VAR _period =
			    SELECTEDVALUE ( cfgPayPeriodDetailed[Period] )
			VAR _Calc =
			    CALCULATE (
			        COUNT ( 'vwEncounterPayroll - PRV'[EncounterID] ),
			        FILTER ( ALLEXCEPT( 'vwEncounterPayroll - PRV', 'vwEncounterPayroll - PRV'[Market]  ), _period = 'vwEncounterPayroll - PRV'[NCDPeriod] )
			    )
			RETURN
			    _Calc
		displayFolder: _Payroll - PRV
		lineageTag: 92d41e7c-fba3-401f-9a13-89f105df9c42

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '__Closed Visits in Period _ ALLEXCEPT - PRV' = ```
			
			VAR _period = SELECTEDVALUE(cfgPayPeriodDetailed[Period])
			VAR _Calc =
			    CALCULATE( 
			        COUNT('vwEncounterPayroll - PRV'[EncounterID])
			        , FILTER( ALLEXCEPT('vwEncounterPayroll - PRV', 'vwEncounterPayroll - PRV'[Market],cfgPayPeriodDetailed[Period]), _period = 'vwEncounterPayroll - PRV'[NCDPeriod] )
			    )
			    
			RETURN
			_Calc
			```
		displayFolder: _Payroll - PRV
		lineageTag: 2c0ed98e-d420-41b8-af8d-757704fe7fda

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '__Closed Visits in Period _ ALLSELECTED - PRV' =
			
			VAR _period =
			    SELECTEDVALUE ( cfgPayPeriodDetailed[Period] )
			VAR _Calc =
			    CALCULATE (
			        COUNT ( 'vwEncounterPayroll - PRV'[EncounterID] ),
			        ALLSELECTED ( 'vwEncounterPayroll - PRV' ),
			        'vwEncounterPayroll - PRV'[NCDPeriod] = _period
			    )
			RETURN
			    _Calc
		displayFolder: _Payroll - PRV
		lineageTag: 4fe27fee-8037-42b3-8bb1-401cc8acd355

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '__Closed Visits in Period _ Modified - PRV' =
			
			VAR _period =
			    SELECTEDVALUE ( cfgPayPeriodDetailed[Period] )
			VAR _Calc =
			    CALCULATE (
			        COUNT ( 'vwEncounterPayroll - PRV'[EncounterID] ),
			        REMOVEFILTERS ( cfgPayPeriodDetailed[Period] ),
			        // Esto elimina los filtros de la columna [Period] en la tabla cfgPayPeriodDetailed
			        ALLSELECTED ( 'vwEncounterPayroll - PRV' ),
			        // Esto conserva los filtros seleccionados en otras columnas de vwEncounterPayroll
			        'vwEncounterPayroll - PRV'[NCDPeriod] = _period // Esto aplica el filtro de periodo seleccionado
			    )
			RETURN
			    _Calc
		displayFolder: _Payroll - PRV
		lineageTag: 7bdf2139-88c2-420e-8d52-a70df3b55e31

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '__Closed Visits in Period _ Modified v2 - PRV' =
			
			--VAR _period = VALUE(LEFT(SELECTEDVALUE(cfgPayPeriodDetailed[Min Date by Period])))
			VAR _period = SELECTEDVALUE(cfgPayPeriodDetailed[Period])
			RETURN
			CALCULATE(
			    COUNt('vwEncounterPayroll - PRV'[EncounterID]),
			    ALLEXCEPT(
			        'vwEncounterPayroll - PRV',
			        'vwEncounterPayroll - PRV'[Clinician],
			        'vwEncounterPayroll - PRV'[Market],
			        vwResourceDetails[PreferredFacility],
			        'vwEncounterPayroll - PRV'[EncounterType],
			        'vwEncounterPayroll - PRV'[VisitStatus],
			        vwResourceDetails[MatureCategory],
			        vwResourceDetails[Status],
			        vwResourceDetails[ProviderCategory],
			        vwProviderCategory[ProviderCategory],
			        'vwEncounterPayroll - PRV'[CPTCode],
			        vwResourceDetails[Full Name]
			    ),
			    'vwEncounterPayroll - PRV'[NCDPeriod] = _period
			)
		displayFolder: _Payroll - PRV
		lineageTag: e5b8daf9-f42f-415f-a53d-3cdc2b6b571c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '__CPT % 90837 - PRV' =
			VAR _main =
			    CALCULATE (
			        COUNTROWS ( 'vwEncounterPayroll - PRV' ),
			        FILTER ( 'vwEncounterPayroll - PRV', [CPTCode] IN { "90837" } )
			    )
			VAR _other =
			    CALCULATE (
			        COUNTROWS ( 'vwEncounterPayroll - PRV' ),
			        FILTER ( 'vwEncounterPayroll - PRV', [EncounterType] IN { "(TH) Individual Therapy", "Individual Therapy"} )
			    )
			VAR _result =
			    DIVIDE ( _main, _other, "-" )
			RETURN
			    _result
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: _Payroll - PRV
		lineageTag: e19b58c5-0bde-419f-bf3a-997ae20eccd1

	measure '__Dates - PRV' = MIN(cfgPayPeriodDetailed[Date]) & " - " & MAX(cfgPayPeriodDetailed[Date])
		displayFolder: _Payroll - PRV
		lineageTag: e8002c80-06fe-4943-a0c5-8e3ba779516c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '__Total Closed Notes - PRV' = [__Visits Closed - PRV] + [__Visits Closed Past Periods - PRV]
		formatString: 0
		displayFolder: _Payroll - PRV
		lineageTag: 1faa87ab-295e-4073-924f-f64eefdf1623

	measure '__Visits Closed - PRV' =
			
			CALCULATE (
			    COUNT ( 'vwEncounterPayroll - PRV'[EncounterID] ),
			    'vwEncounterPayroll - PRV'[NCDFlag] = "Same"
			)
		displayFolder: _Payroll - PRV
		lineageTag: fb20c257-e4b7-4a3f-9c24-542d43ce4887

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '__Visits Closed Diff Period - PRV' =
			
			-- closed in the future
			CALCULATE (
			    COUNT ( 'vwEncounterPayroll - PRV'[EncounterID] ),
			    'vwEncounterPayroll - PRV'[NCDFlag] = "Different"
			)
		displayFolder: _Payroll - PRV
		lineageTag: 082626ba-0089-4cd4-bdf3-aa6c206d4589

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '__Visits Closed Past - PRV' = ```
			[__Closed Visits in Period _ Modified v2 - PRV] - [__Visits Closed - PRV] 
			```
		displayFolder: _Payroll - PRV
		lineageTag: fa365e52-a91c-42d9-b775-0aa93fcc8b74

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '__Visits Closed Past Periods - PRV' =
			
			CALCULATE (
			    COUNT ( 'vwEncounterPayroll - PRV'[EncounterID] ),
			    'vwEncounterPayroll - PRV'[NCDFlag] = "Different"
			)
		displayFolder: _Payroll - PRV
		lineageTag: b4781488-8d5d-452e-8ccc-262f1721a0e6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '__Visits Count - PRV' =
			
			CALCULATE(
			    COUNT ( 'vwEncounterPayroll - PRV'[EncounterID] )
			    ,USERELATIONSHIP('vwEncounterPayroll - PRV'[VisitDate],cfgPayPeriodDetailed[Date]))
		displayFolder: _Payroll - PRV
		lineageTag: 24885c75-e91d-4e78-8090-782e77af9c37

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '__Visits Not Closed - PRV' =
			
			
			CALCULATE (
			    COUNT ( 'vwEncounterPayroll - PRV'[EncounterID] ),
			    'vwEncounterPayroll - PRV'[NCDFlag] = "NotClosed",
			    USERELATIONSHIP('vwEncounterPayroll - PRV'[VisitDate],cfgPayPeriodDetailed[Date])
			)
		displayFolder: _Payroll - PRV
		lineageTag: a699f2fd-1f74-4331-ba8d-43481ce0e18f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'All time notes not closed - PRV' = ```
			
			    
			
			CALCULATE(
			    [__Visits Not Closed - PRV],
			    ALLEXCEPT(
			        'vwEncounterPayroll - PRV',
			        'vwEncounterPayroll - PRV'[Clinician],
			        'vwEncounterPayroll - PRV'[Market],
			        vwResourceDetails[PreferredFacility],
			        'vwEncounterPayroll - PRV'[EncounterType],
			        'vwEncounterPayroll - PRV'[VisitStatus],
			        vwResourceDetails[MatureCategory],
			        vwResourceDetails[Status],
			        vwResourceDetails[ProviderCategory],
			        vwProviderCategory[ProviderCategory],
			        vwResourceDetails[Full Name]
			    )
			)
			```
		displayFolder: _Payroll - PRV
		lineageTag: f2c7047d-f9dc-4cb7-9de0-9ded61dd5cec

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cumulative Visits' = ```
			
			VAR BeginPeriod =
			    IF (
			        SELECTEDVALUE ( dimDate[Slicer Month] ) = "Current Month",
			        DATE( YEAR( TODAY() ), MONTH ( TODAY() ), "01" ),
			        DATE( YEAR( SELECTEDVALUE ( dimDate[Slicer Month] ) ), MONTH( SELECTEDVALUE( dimDate[Slicer Month] ) ), "01" )
			    )
			VAR _resu = 
			    CALCULATE (
			        [# Completed - Total - Comb],
			        FILTER (
			            ALL ( 'dimDate'[Date] ),
			            AND (
			                'dimDate'[Date] <= MAX ( 'dimDate'[Date] ),
			                'dimDate'[Date] >= BeginPeriod
			            )
			        )
			    )
			
			RETURN _resu
			```
		formatString: 0
		displayFolder: _Finance
		lineageTag: de699380-74f4-4367-a71a-8d7911d6fa3b

	measure 'Cumulative Visits Budget' = ```
			
			VAR BeginPeriod =
			    IF (
			        SELECTEDVALUE ( dimDate[Slicer Month] ) = "Current Month",
			        DATE( YEAR( TODAY() ), MONTH ( TODAY() ), "01" ),
			        DATE( YEAR( SELECTEDVALUE ( dimDate[Slicer Month] ) ), MONTH( SELECTEDVALUE( dimDate[Slicer Month] ) ), "01" )
			    )
			VAR _resu = 
			    CALCULATE (
			        [Budget],
			        FILTER (
			            ALL ( 'dimDate'[Date] ),
			            AND (
			                'dimDate'[Date] <= MAX ( 'dimDate'[Date] ),
			                'dimDate'[Date] >= BeginPeriod
			            )
			        )
			    )
			
			RETURN _resu
			```
		formatString: 0
		displayFolder: _Finance
		lineageTag: 56300aec-1038-4331-b54f-3e9dc26be685

	measure 'Cumulative Visits Budget Var' = ```
			
			VAR BeginPeriod =
			    IF (
			        SELECTEDVALUE ( dimDate[Slicer Month] ) = "Current Month",
			        DATE( YEAR( TODAY() ), MONTH ( TODAY() ), "01" ),
			        DATE( YEAR( SELECTEDVALUE ( dimDate[Slicer Month] ) ), MONTH( SELECTEDVALUE( dimDate[Slicer Month] ) ), "01" )
			    )
			VAR _resu = 
			    CALCULATE (
			        [Var - Visit vs Budget - Comb],
			        FILTER (
			            ALL ( 'dimDate'[Date] ),
			            AND (
			                'dimDate'[Date] <= MAX ( 'dimDate'[Date] ),
			                'dimDate'[Date] >= BeginPeriod
			            )
			        )
			    )
			
			RETURN _resu
			```
		formatString: 0
		displayFolder: _Finance
		lineageTag: 07de8341-4835-4a37-b1b2-f037521f0f68

	measure 'Budget - Recast Monthly - Completed' =
			
			VAR CurrentMonth =
			    IF (
			        SELECTEDVALUE ( dimDate[Slicer Month] ) = "Current Month",
			        FORMAT ( EOMONTH ( TODAY (), 0 ), "YYYY-MM-DD" ),
			        FORMAT ( EOMONTH ( SELECTEDVALUE ( dimDate[Slicer Month] ), 0 ), "YYYY-MM-DD" )
			    )
			RETURN
			    CALCULATE (
			        SUM ( cfgDailyBudget[MtdVisComp] ),
			        FILTER (
			            'cfgDailyBudget',
			            cfgDailyBudget[MonthDate] = DATEVALUE ( CurrentMonth )
			        ),
			        cfgDailyBudget[BudgetType] = "V",
			        cfgDailyBudget[FacilityName] <> "All Locations",
			        cfgDailyBudget[ProviderCategory] = "Total",
			        cfgDailyBudget[VisitType] = "Total"
			    )
		formatString: #,0
		displayFolder: _Finance
		lineageTag: f3aed91d-2f4e-454d-abf2-c50cad012166

	measure 'Budget - Recast Monthly - NoShow' =
			
			VAR CurrentMonth =
			    IF (
			        SELECTEDVALUE ( dimDate[Slicer Month] ) = "Current Month",
			        FORMAT ( EOMONTH ( TODAY (), 0 ), "YYYY-MM-DD" ),
			        FORMAT ( EOMONTH ( SELECTEDVALUE ( dimDate[Slicer Month] ), 0 ), "YYYY-MM-DD" )
			    )
			RETURN
			    CALCULATE (
			        SUM ( cfgDailyBudget[MtdVisNoShow] ),
			        FILTER (
			            'cfgDailyBudget',
			            cfgDailyBudget[MonthDate] = DATEVALUE ( CurrentMonth )
			        ),
			        cfgDailyBudget[BudgetType] = "V",
			        cfgDailyBudget[FacilityName] <> "All Locations",
			        cfgDailyBudget[ProviderCategory] = "Total",
			        cfgDailyBudget[VisitType] = "Total"
			    )
		formatString: #,0
		displayFolder: _Finance
		lineageTag: 3a7eb37e-2a7f-45b6-806c-e424205a1680

	measure 'Total Issues Closed' = -1 * SUM(vwClaimIssuesDaySummary[TotalIssuesClosed])
		formatString: 0
		displayFolder: _Daily Operations
		lineageTag: 609ee71e-8b1a-4c21-9f5b-fdd41475c206

	measure 'Total Issues Created' = SUM(vwClaimIssuesDaySummary[TotalIssuesCreated])
		formatString: 0
		displayFolder: _Daily Operations
		lineageTag: 738307c6-bd58-4979-aa40-0bb7c7538ffe

	measure 'Total Issues Difference' = SUM(vwClaimIssuesDaySummary[CreatedClosedDiff])
		formatString: 0
		displayFolder: _Daily Operations
		lineageTag: b91b206d-40c6-4a4d-a37a-fec7d18dbd9d

	measure NY_MKT_AttributablePatient = SUM(vwCollectiveLead[MKT_AttributablePatient])
		displayFolder: _Marketing\NY Referral Leads by Category
		lineageTag: 4a3e6294-5b03-4dac-837b-a8f1e9dc00af

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure NY_MKT_PhysicianLead = SUM(vwCollectiveLead[MKT_PhysicianLead])
		displayFolder: _Marketing\NY Referral Leads by Category
		lineageTag: 382c384b-428f-4117-af16-1e7df527311f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure NY_MKT_UnattributablePatient = SUM(vwCollectiveLead[MKT_UnattributablePatient])
		displayFolder: _Marketing\NY Referral Leads by Category
		lineageTag: 951553bf-05fe-46a2-a1ec-990b242eed80

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Cancel =
			
			CALCULATE(
			    COUNT(vwEncounterPayrollReducedCombined[EncounterID]),
			    vwEncounterPayrollReducedCombined[VisitStatus] = "Cancel"
			    )
		displayFolder: _Panel\Second Page
		lineageTag: 87bcf682-ba91-44f5-82d4-13a515a92692

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Complete% = [Complete] / ([Complete] + [Outstanding])
		formatString: 0%;-0%;0%
		displayFolder: _Panel\Second Page
		lineageTag: bdb5952a-de4c-4b48-9bfd-fab71d8bffe1

	measure CompleteListOfPeers =
			
			VAR SelectedClinician =  VALUES(vwResourceDetails[Full Name])
			VAR SelectedMarket = LOOKUPVALUE(vwEncounterPayrollReducedCombined[Market], vwResourceDetails[Full Name], SelectedClinician)
			VAR SelectedProviderCategory = LOOKUPVALUE(vwResourceDetails[ProviderCategory], vwResourceDetails[Full Name], SelectedClinician)
			
			RETURN
			CALCULATE(
			    [Complete],
			    FILTER(
			        ALL(vwResourceDetails[Full Name]),
			        NOT vwResourceDetails[Full Name] IN SelectedClinician),
			        vwEncounterPayrollReducedCombined[Market] = SelectedMarket,
			        vwResourceDetails[ProviderCategory] = SelectedProviderCategory
			        --vwResourceDetails[MatureCategory] = "Mature"
			    )
		displayFolder: _Panel\Second Page
		lineageTag: bcf25791-2d1e-4fc1-9c87-7aa734f4c956

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure CompleteListOfPeers% = [CompleteListOfPeers] / ([CompleteListOfPeers] + [OutstandingListOfPeers])
		formatString: 0%;-0%;0%
		displayFolder: _Panel\Second Page
		lineageTag: f112c707-cae6-4e0e-b3c6-0f772c4360d4

	measure CompleteNotSelected =
			
			
			VAR SelectedClinicians= VALUES(vwResourceDetails[Full Name])
			RETURN
			CALCULATE(
			    [Complete],
			    FILTER(
			        ALL(vwResourceDetails[Full Name]),
			        NOT vwResourceDetails[Full Name] IN SelectedClinicians
			    )
			)
		displayFolder: _Panel\Second Page
		lineageTag: c992d445-3473-4853-baaf-7dac82f0eacd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure CompleteNotSelected% = [CompleteNotSelected] / ([CompleteNotSelected] + [OutstandingNotSelected])
		displayFolder: _Panel\Second Page
		lineageTag: 82fa118f-eb0d-491d-85de-3647ea96bd6a

	measure NoShowNotSelected =
			
			
			VAR SelectedClinicians= VALUES(vwResourceDetails[Full Name])
			RETURN
			CALCULATE(
			    [No Shows],
			    FILTER(
			        ALL(vwResourceDetails[Full Name]),
			        NOT vwResourceDetails[Full Name] IN SelectedClinicians
			    )
			)
		displayFolder: _Panel\Second Page
		lineageTag: cf746002-bf39-46ea-a512-6760217599ba

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure OutstandingListOfPeers =
			
			VAR SelectedClinician =  VALUES(vwResourceDetails[Full Name])
			VAR SelectedMarket = LOOKUPVALUE(vwEncounterPayrollReducedCombined[Market], vwResourceDetails[Full Name], SelectedClinician)
			VAR SelectedProviderCategory = LOOKUPVALUE(vwResourceDetails[ProviderCategory], vwResourceDetails[Full Name], SelectedClinician)
			
			RETURN
			CALCULATE(
			    [Outstanding],
			    FILTER(
			        ALL(vwResourceDetails[Full Name]),
			        NOT vwResourceDetails[Full Name] IN SelectedClinician),
			        vwEncounterPayrollReducedCombined[Market] = SelectedMarket,
			        vwResourceDetails[ProviderCategory] = SelectedProviderCategory,
			        vwResourceDetails[MatureCategory] = "Mature"
			    )
		displayFolder: _Panel\Second Page
		lineageTag: 02e8fbb9-348c-46dd-8c6c-c0d38e0be7bf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure OutstandingNotSelected =
			
			
			VAR SelectedClinicians= VALUES(vwResourceDetails[Full Name])
			RETURN
			CALCULATE(
			    [Outstanding],
			    FILTER(
			        ALL(vwResourceDetails[Full Name]),
			        NOT vwResourceDetails[Full Name] IN SelectedClinicians
			    )
			)
		displayFolder: _Panel\Second Page
		lineageTag: d2b4eb06-68a5-4c12-aca6-cdc93a6812a4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Kept = [Complete] + [Outstanding]
		displayFolder: _Panel\Second Page
		lineageTag: 4809e193-9d57-4983-8b2a-33d171ab9580

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure NoKept = [Cancel] + [No Shows]
		displayFolder: _Panel\Second Page
		lineageTag: 36902853-10df-4874-a7e1-275265f3a778

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure VisitBreakdownCount = SUM(SumVisitBreakDown[VisitCount])
		displayFolder: _Panel\Second Page
		lineageTag: 6c959354-5ddc-4fd8-9130-35d4f88eb1a8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure NY_MKt_Total = SUM(vwCollectiveLead[MKT_AttributablePatient]) + SUM(vwCollectiveLead[MKT_PhysicianLead]) + SUM(vwCollectiveLead[MKT_UnattributablePatient])
		displayFolder: _Marketing\NY Referral Leads by Category
		lineageTag: 8aca443f-c47e-4583-8c33-98ea7de59f05

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Measures - model-6828cd39-fe04-4f8a-952d-066e08c111a7' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Exception

