table 'PRV vwEncounterPayrollReduced'
	lineageTag: ad1d3d3e-aefb-4a1a-b7a4-525a16bff698

	column EncounterID
		dataType: int64
		formatString: 0
		lineageTag: d6ea770c-4d6e-4869-98bb-4950e1569af4
		summarizeBy: count
		sourceColumn: EncounterID

		annotation SummarizationSetBy = Automatic

	column visitid
		dataType: int64
		formatString: 0
		lineageTag: c5ba1c24-d897-46c9-b889-5add688c9848
		summarizeBy: sum
		sourceColumn: visitid

		annotation SummarizationSetBy = Automatic

	column ResourceID
		dataType: int64
		formatString: 0
		lineageTag: 821dd050-7d68-4a24-8d12-58185123a568
		summarizeBy: count
		sourceColumn: ResourceID

		annotation SummarizationSetBy = Automatic

	column FlagClosed
		dataType: int64
		formatString: 0
		lineageTag: 9af1d6ef-4b91-4731-8792-bfcad6822df0
		summarizeBy: sum
		sourceColumn: FlagClosed

		annotation SummarizationSetBy = Automatic

	column VisitTypeGroup
		dataType: string
		lineageTag: aab6d5d3-8b36-4975-8eef-cb36b24a5c34
		summarizeBy: none
		sourceColumn: VisitTypeGroup

		annotation SummarizationSetBy = Automatic

	column VisitDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0786ea1d-6306-4adc-a81d-ecb46fa4ab3c
		summarizeBy: none
		sourceColumn: VisitDate

		variation Variation
			isDefault
			relationship: d9941920-098a-4c97-b1b3-3c30200dd3ca
			defaultHierarchy: LocalDateTable_f87de4f9-1229-44af-92a4-cfa1eb8b6945.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column VisitType
		dataType: string
		lineageTag: dde4668c-54ce-4e43-bb67-c9737aa6b736
		summarizeBy: none
		sourceColumn: VisitType

		annotation SummarizationSetBy = Automatic

	column VisitStatus
		dataType: string
		lineageTag: 4b3708af-70d8-44d1-b5c4-9d3abe62d754
		summarizeBy: none
		sourceColumn: VisitStatus

		annotation SummarizationSetBy = Automatic

	column NoteClosedDateTime
		dataType: dateTime
		formatString: Long Date
		lineageTag: 370c6e5a-54d0-4ece-88a0-6d7a90acc18d
		summarizeBy: none
		sourceColumn: NoteClosedDateTime

		variation Variation
			isDefault
			relationship: 18870164-3d67-45f7-87e5-5897f95b9f2d
			defaultHierarchy: LocalDateTable_eab38046-955e-4828-b4e4-ebbe128f353c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Market
		dataType: string
		lineageTag: 5dd09bca-9c78-40fa-9f42-97d7a9d158d8
		summarizeBy: none
		sourceColumn: Market

		annotation SummarizationSetBy = Automatic

	column PatientFullName
		dataType: string
		lineageTag: d8ff253b-eb51-44a2-9d9c-6ca0ab71de1a
		summarizeBy: none
		sourceColumn: PatientFullName

		annotation SummarizationSetBy = Automatic

	partition 'PRV vwEncounterPayrollReduced' = m
		mode: import
		queryGroup: FACT\Payroll
		source =
				let
				    Source = Sql.Database(ServerName, DBName),
				    PRV_vwEncounterPayrollReduced = Source{[Schema="PRV",Item="vwEncounterPayrollReduced"]}[Data],
				    #"Merged Columns" = Table.CombineColumns(PRV_vwEncounterPayrollReduced,{"LastName", "FirstName"},Combiner.CombineTextByDelimiter(", ", QuoteStyle.None),"PatientFullName")
				in
				    #"Merged Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

