table vwAccountDetails
	lineageTag: 4b2a922a-670e-4979-ba5e-840dd0ae55e4

	column ACCOUNTNO
		dataType: int64
		formatString: 0
		lineageTag: 2f66a488-3574-4f6e-8e85-62549a479587
		summarizeBy: none
		sourceColumn: ACCOUNTNO

		annotation SummarizationSetBy = Automatic

	column ACCOUNTTITLE
		dataType: string
		lineageTag: 719d1ca5-4184-4cc7-a0f9-0a03d5abff53
		summarizeBy: none
		sourceColumn: ACCOUNTTITLE

		annotation SummarizationSetBy = Automatic

	column PERIOD_NAME
		dataType: string
		lineageTag: 41a90706-f780-4010-a515-e16ca95865a6
		summarizeBy: none
		sourceColumn: PERIOD_NAME

		annotation SummarizationSetBy = Automatic

	column PeriodStart
		dataType: dateTime
		formatString: Short Date
		lineageTag: b066c257-e594-46f7-9e54-fdf0ed5ec5af
		summarizeBy: none
		sourceColumn: PeriodStart

		variation Variation
			isDefault
			relationship: 8b83a422-fe19-44a2-aa28-6e3d1a09463d
			defaultHierarchy: LocalDateTable_33eba6bf-6b9e-4ed9-a6a4-ab04067fd01c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column PeriodEnd
		dataType: dateTime
		formatString: Short Date
		lineageTag: e8d6245b-0cc9-46bc-ad88-9c7477c6a7ea
		summarizeBy: none
		sourceColumn: PeriodEnd

		variation Variation
			isDefault
			relationship: b7cc0b63-44d9-40fd-a07a-72c3db9d7d51
			defaultHierarchy: LocalDateTable_686ed358-3375-433c-ab3e-b60e863b79b7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ACCOUNTTYPE
		dataType: string
		lineageTag: c3b3d7a3-0c33-448a-b75b-17fd7e0f1a56
		summarizeBy: none
		sourceColumn: ACCOUNTTYPE

		annotation SummarizationSetBy = Automatic

	column NORMALBALANCE
		dataType: string
		lineageTag: d4a30146-b1f6-49d9-a63a-c70e8928eba1
		summarizeBy: none
		sourceColumn: NORMALBALANCE

		annotation SummarizationSetBy = Automatic

	column CLOSINGTYPE
		dataType: string
		lineageTag: fdf7b490-2631-41fe-8759-af87cf0f037a
		summarizeBy: none
		sourceColumn: CLOSINGTYPE

		annotation SummarizationSetBy = Automatic

	column OpenBal
		dataType: int64
		lineageTag: 02851247-f495-4ca9-85aa-d10fb54df739
		summarizeBy: sum
		sourceColumn: OpenBal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TotalDebit
		dataType: int64
		lineageTag: 87b07616-d657-4d7d-ad8c-de185db6020a
		summarizeBy: sum
		sourceColumn: TotalDebit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TotalCredit
		dataType: int64
		lineageTag: 1f0ad3ec-1f47-4a6e-b75f-ad9201c0ac5d
		summarizeBy: sum
		sourceColumn: TotalCredit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TotalAdjDebit
		dataType: int64
		lineageTag: 7cd0672c-58ef-41a0-a854-ce20d3e5f680
		summarizeBy: sum
		sourceColumn: TotalAdjDebit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TotalAdjCredit
		dataType: int64
		lineageTag: c5d6f744-0e1c-4231-bccb-a452582597dc
		summarizeBy: sum
		sourceColumn: TotalAdjCredit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ForBal
		dataType: int64
		lineageTag: 6d0818e4-66e1-4773-9de9-cea6eeef3098
		summarizeBy: sum
		sourceColumn: ForBal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EndBal
		dataType: int64
		lineageTag: 8671bc46-e517-44b9-b0ee-d4c8b1360e32
		summarizeBy: sum
		sourceColumn: EndBal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EndBalv2
		dataType: int64
		formatString: 0
		lineageTag: a4e3de18-f611-4409-a52a-9fe67a59f0bf
		summarizeBy: sum
		sourceColumn: EndBalv2

		annotation SummarizationSetBy = Automatic

	column DEPARTMENTID
		dataType: string
		lineageTag: d06cc460-cd44-48db-a3b5-e4f8da8e51d4
		summarizeBy: none
		sourceColumn: DEPARTMENTID

		annotation SummarizationSetBy = Automatic

	column LOCATIONID
		dataType: string
		lineageTag: a2763a53-cdd6-4a92-9a4b-71ccccde83be
		summarizeBy: none
		sourceColumn: LOCATIONID

		annotation SummarizationSetBy = Automatic

	column CLASSID
		dataType: string
		lineageTag: a7a3b70e-c1ac-436b-9c24-a174f346fb10
		summarizeBy: none
		sourceColumn: CLASSID

		annotation SummarizationSetBy = Automatic

	partition vwAccountDetails = m
		mode: import
		queryGroup: 'FACT\Account Details'
		source =
				let
				    Source = Sql.Database("azr-cbh-use1-sql-server01.database.windows.net", "CollectiveBH"),
				    SAG_vwAccountDetails = Source{[Schema="SAG",Item="vwAccountDetails"]}[Data],
				    #"Added Custom" = Table.AddColumn(SAG_vwAccountDetails, "EndBalv2", each [EndBal]*(-1)),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom",{{"OpenBal", Int64.Type}, {"TotalDebit", Int64.Type}, {"TotalCredit", Int64.Type}, {"ForBal", Int64.Type}, {"EndBal", Int64.Type}, {"EndBalv2", Int64.Type}, {"TotalAdjDebit", Int64.Type}, {"TotalAdjCredit", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Exception

