table vwDailySalesCombinedByProvider
	lineageTag: 14d845e8-bf56-41a2-a5d5-b319306c5c39

	column Market
		dataType: string
		lineageTag: 926c7530-743f-4171-ab82-7272a7386fe2
		summarizeBy: none
		sourceColumn: Market

		annotation SummarizationSetBy = Automatic

	column FacilityName
		dataType: string
		lineageTag: bd20a99c-798e-4715-a6b4-c290fc877cde
		summarizeBy: none
		sourceColumn: FacilityName

		annotation SummarizationSetBy = Automatic

	column FacilityID
		dataType: int64
		formatString: 0
		lineageTag: 2d1f62ed-8946-463b-a8f8-a1bf15ee5004
		summarizeBy: count
		sourceColumn: FacilityID

		annotation SummarizationSetBy = Automatic

	column ClinicianFullName
		dataType: string
		lineageTag: c86192a1-1957-4685-a182-2f11c55eb2a3
		summarizeBy: none
		sourceColumn: ClinicianFullName

		annotation SummarizationSetBy = Automatic

	column VisitDate
		dataType: dateTime
		formatString: mm/dd/yyyy
		lineageTag: 23862f15-19d4-465f-862d-cc9079b45cac
		summarizeBy: none
		sourceColumn: VisitDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column ThrIntVis
		dataType: int64
		formatString: 0
		lineageTag: 64a73b41-d054-4490-ace0-495d30833391
		summarizeBy: sum
		sourceColumn: ThrIntVis

		annotation SummarizationSetBy = Automatic

	column ThrFupVis
		dataType: int64
		formatString: 0
		lineageTag: b3de98af-baf5-41a5-89f0-05c0b6a40f2f
		summarizeBy: sum
		sourceColumn: ThrFupVis

		annotation SummarizationSetBy = Automatic

	column PsyIntVis
		dataType: int64
		formatString: 0
		lineageTag: 87f9d6f3-ed25-4891-abb1-5b92a29f7bd8
		summarizeBy: sum
		sourceColumn: PsyIntVis

		annotation SummarizationSetBy = Automatic

	column PsyFupVis
		dataType: int64
		formatString: 0
		lineageTag: 8449adaa-31db-4b3a-99ac-c1420d53104a
		summarizeBy: sum
		sourceColumn: PsyFupVis

		annotation SummarizationSetBy = Automatic

	column ThrIntRev
		dataType: int64
		formatString: 0
		lineageTag: 63a2e725-9e3f-4771-a8c0-f9ba4fd22805
		summarizeBy: sum
		sourceColumn: ThrIntRev

		annotation SummarizationSetBy = Automatic

	column ThrFupRev
		dataType: int64
		formatString: 0
		lineageTag: 7eed185a-fa16-453c-8d29-cb12c210ddf8
		summarizeBy: sum
		sourceColumn: ThrFupRev

		annotation SummarizationSetBy = Automatic

	column PsyIntRev
		dataType: int64
		formatString: 0
		lineageTag: 5fb163af-7d7d-4386-90e6-d06dc24fa879
		summarizeBy: sum
		sourceColumn: PsyIntRev

		annotation SummarizationSetBy = Automatic

	column PsyFupRev
		dataType: int64
		formatString: 0
		lineageTag: 1a331e5e-417d-4d9f-912c-0c7df26c7542
		summarizeBy: sum
		sourceColumn: PsyFupRev

		annotation SummarizationSetBy = Automatic

	column NoShowVis
		dataType: int64
		formatString: 0
		lineageTag: bedd9b52-480b-4801-9140-24e38d386fca
		summarizeBy: sum
		sourceColumn: NoShowVis

		annotation SummarizationSetBy = Automatic

	column CancelVis
		dataType: int64
		formatString: 0
		lineageTag: af4a8d38-4d9f-4245-88b3-bbe7dde35655
		summarizeBy: sum
		sourceColumn: CancelVis

		annotation SummarizationSetBy = Automatic

	column NoShowRev
		dataType: int64
		formatString: 0
		lineageTag: 98da108d-231d-4551-8b8f-ec1d8084a87e
		summarizeBy: sum
		sourceColumn: NoShowRev

		annotation SummarizationSetBy = Automatic

	partition vwDailySalesCombinedByProvider = m
		mode: import
		queryGroup: Settings
		source =
				let
				    Source = Sql.Database(ServerName, DBName),
				    dbo_vwDailySalesCombinedByProvider = Source{[Schema="dbo",Item="vwDailySalesCombinedByProvider"]}[Data],
				    #"Merged Columns" = Table.CombineColumns(dbo_vwDailySalesCombinedByProvider,{"LastName", "FirstName"},Combiner.CombineTextByDelimiter(", ", QuoteStyle.None),"ClinicianFullName")
				in
				    #"Merged Columns"

	annotation PBI_ResultType = Table

