table vwEncounterPayrollReduced
	lineageTag: 8e5bc43b-3f52-4df6-a0e7-89f5eab9155a

	column EncounterID
		dataType: int64
		formatString: 0
		lineageTag: c5b6a7a7-771e-4702-8358-b166cc5dd450
		summarizeBy: count
		sourceColumn: EncounterID

		annotation SummarizationSetBy = Automatic

	column visitid
		dataType: int64
		formatString: 0
		lineageTag: 22bc92b3-ee53-4f26-aa2b-69333535edb4
		summarizeBy: sum
		sourceColumn: visitid

		annotation SummarizationSetBy = Automatic

	column ResourceID
		dataType: int64
		formatString: 0
		lineageTag: f2aac49a-37bc-47c6-a306-29ae4f1b72e6
		summarizeBy: count
		sourceColumn: ResourceID

		annotation SummarizationSetBy = Automatic

	column FlagClosed
		dataType: int64
		formatString: 0
		lineageTag: 230a644b-63c4-44b2-96de-b0c9c52b301a
		summarizeBy: sum
		sourceColumn: FlagClosed

		annotation SummarizationSetBy = Automatic

	column VisitTypeGroup
		dataType: string
		lineageTag: bd3de2aa-f1e2-43db-b99a-d1f9a0d20dfe
		summarizeBy: none
		sourceColumn: VisitTypeGroup

		annotation SummarizationSetBy = Automatic

	column VisitDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 67855961-1523-463d-a81c-6d23d262019e
		summarizeBy: none
		sourceColumn: VisitDate

		variation Variation
			isDefault
			relationship: c7c2552d-090c-4032-88e3-373fcabb24d8
			defaultHierarchy: LocalDateTable_49f97600-bcd3-4e5f-96e7-53e3ab5719c7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column VisitType
		dataType: string
		lineageTag: 33997b2e-b8d1-48e1-bc01-7e9cc1c2fc8b
		summarizeBy: none
		sourceColumn: VisitType

		annotation SummarizationSetBy = Automatic

	column NoteClosedDateTime
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7c57db30-4b9e-4bf9-9927-54ae5355426c
		summarizeBy: none
		sourceColumn: NoteClosedDateTime

		variation Variation
			isDefault
			relationship: cb1b8c62-a4d6-42e4-af0b-9f9fb6e09106
			defaultHierarchy: LocalDateTable_c62ea07b-97ec-4bc0-a1af-bd675d5e7d63.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Market
		dataType: string
		lineageTag: d346cea8-cada-4767-9a31-f94700504345
		summarizeBy: none
		sourceColumn: Market

		annotation SummarizationSetBy = Automatic

	column VisitStatus
		dataType: string
		lineageTag: 8237388c-f228-4cca-a471-b7aff482c87b
		summarizeBy: none
		sourceColumn: VisitStatus

		annotation SummarizationSetBy = Automatic

	column PatientFullName
		dataType: string
		lineageTag: 33a37992-a91b-4b0c-b81a-1a11ced257eb
		summarizeBy: none
		sourceColumn: PatientFullName

		annotation SummarizationSetBy = Automatic

	partition vwEncounterPayrollReduced = m
		mode: import
		queryGroup: FACT\Payroll
		source =
				let
				    Source = Sql.Database(ServerName, DBName),
				    dbo_vwEncounterPayrollReduced = Source{[Schema="dbo",Item="vwEncounterPayrollReduced"]}[Data],
				    #"Merged Columns" = Table.CombineColumns(dbo_vwEncounterPayrollReduced,{"LastName", "FirstName"},Combiner.CombineTextByDelimiter(", ", QuoteStyle.None),"PatientFullName")
				in
				    #"Merged Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

