table vwLeadsByPriviaProvider
	lineageTag: e7160c95-10ef-474b-b8f6-fca227f5676c

	column ParentPractice
		dataType: string
		lineageTag: f077b909-a00c-48e7-95bb-41e9da111cec
		summarizeBy: none
		sourceColumn: ParentPractice

		annotation SummarizationSetBy = Automatic

	column Practice
		dataType: string
		lineageTag: 3422b47b-04be-4888-8cc9-8218dd00d411
		summarizeBy: none
		sourceColumn: Practice

		annotation SummarizationSetBy = Automatic

	column ContactFullName
		dataType: string
		lineageTag: da507c48-5f2f-4a20-8559-70a279840253
		summarizeBy: none
		sourceColumn: ContactFullName

		annotation SummarizationSetBy = Automatic

	column LeadStatus
		dataType: string
		lineageTag: 83003419-f7b9-43f0-b686-ae05c40f023c
		summarizeBy: none
		sourceColumn: LeadStatus

		annotation SummarizationSetBy = Automatic

	column InquiryDate
		dataType: dateTime
		formatString: mm/dd/yyyy
		lineageTag: 14c74b7c-2d11-4272-bf4c-4d18aea46b3b
		summarizeBy: none
		sourceColumn: InquiryDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	partition vwLeadsByPriviaProvider = m
		mode: import
		queryGroup: Settings
		source =
				let
				    Source = Sql.Database(ServerName, DBName),
				    SFO_vwLeadsByPriviaProvider = Source{[Schema="SFO",Item="vwLeadsByPriviaProvider"]}[Data],
				    #"Merged Columns" = Table.CombineColumns(SFO_vwLeadsByPriviaProvider,{"ContactLastName", "ContactFirstName"},Combiner.CombineTextByDelimiter(", ", QuoteStyle.None),"ContactFullName"),
				    #"Replaced Value" = Table.ReplaceValue(#"Merged Columns",", ","N/A",Replacer.ReplaceValue,{"ContactFullName"})
				in
				    #"Replaced Value"

	annotation PBI_ResultType = Table

