table 'vwLeadActivity - FirstActivityDate'
	lineageTag: f56cd1ef-0bcb-482f-b2bc-2e2c4ba6ea98

	measure Leads_FA = DISTINCTCOUNT( 'vwLeadActivity - FirstActivityDate'[recordId])
		formatString: #,0
		lineageTag: 68ecf0a8-643a-4fce-bbe8-5453d58fac61

	column recordId
		dataType: string
		lineageTag: f8900712-ad2d-474a-910e-8257fc055d4d
		summarizeBy: none
		sourceColumn: recordId

		annotation SummarizationSetBy = Automatic

	column FullName
		dataType: string
		lineageTag: 7e8c0431-d2cc-4cc0-94ee-f3a1a9229a2f
		summarizeBy: none
		sourceColumn: FullName

		annotation SummarizationSetBy = Automatic

	column referralType
		dataType: string
		lineageTag: f9b7d4e5-ef4b-4a72-b15f-4a2a807d7e6f
		summarizeBy: none
		sourceColumn: referralType

		annotation SummarizationSetBy = Automatic

	column LeadStatus
		dataType: string
		lineageTag: 7e5c4fd0-dc2b-494e-b387-ba96ed1cc1f6
		summarizeBy: none
		sourceColumn: LeadStatus

		annotation SummarizationSetBy = Automatic

	column MinLeadDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 31f9d3ff-ea1a-45b4-a212-cfb840d37d8e
		summarizeBy: none
		sourceColumn: MinLeadDate

		variation Variation
			isDefault
			relationship: f469465a-6d76-41d8-9c29-9b67fbdf98fa
			defaultHierarchy: LocalDateTable_68ca62f3-fa6b-4cc2-a0ed-4b760461f6bc.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column MinActivityDate
		dataType: dateTime
		formatString: General Date
		lineageTag: f78d2e5d-b010-4b1b-a545-464ab8395907
		summarizeBy: none
		sourceColumn: MinActivityDate

		variation Variation
			isDefault
			relationship: 35e6ed8c-267a-427c-99c9-d007cb148d77
			defaultHierarchy: LocalDateTable_7dd9fa8d-e6ab-4fd0-b486-f215b89fc943.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Duration_Minutes
		dataType: int64
		formatString: 0
		lineageTag: 37fc8cfc-06a7-4f7f-906b-c87fc31d2a99
		summarizeBy: sum
		sourceColumn: Duration_Minutes

		annotation SummarizationSetBy = Automatic

	column Duration_Hours
		dataType: int64
		formatString: 0
		lineageTag: 25523682-3b5c-421c-a969-a4d7bff15527
		summarizeBy: sum
		sourceColumn: Duration_Hours

		annotation SummarizationSetBy = Automatic

	column Duration_Days
		dataType: int64
		formatString: 0
		lineageTag: 2b213677-e822-46cd-a9da-b73e1b615fa3
		summarizeBy: sum
		sourceColumn: Duration_Days

		annotation SummarizationSetBy = Automatic

	column GroupDays = ```
			
			VAR Duracion = 'vwLeadActivity - FirstActivityDate'[Duration_Days]  
			RETURN
			    IF(Duracion <= 7, REPT(UNICHAR(8203),5) & "0-7",
			    IF(Duracion <= 15,REPT(UNICHAR(8203),4) & "8-15",
			    IF(Duracion <= 30,REPT(UNICHAR(8203),3) & "16-30",
			    IF(Duracion <= 60, REPT(UNICHAR(8203),2) & "31-60",
			    REPT(UNICHAR(8203),1) & "60+"))))
			```
		lineageTag: d0ac866d-d9f8-4615-a9c5-9a92afeabb3e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Cohort
		dataType: string
		lineageTag: 79b76a53-0cfa-4442-b72f-1e1a27c25f96
		summarizeBy: none
		sourceColumn: Cohort
		sortByColumn: 'Cohort Sort'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Cohort Sort'
		dataType: int64
		formatString: 0
		lineageTag: 1d33d028-8d40-40b9-a136-39d38ec7ad12
		summarizeBy: sum
		sourceColumn: Cohort Sort

		annotation SummarizationSetBy = Automatic

	partition 'vwLeadActivity - FirstActivityDate' = m
		mode: import
		queryGroup: Exploration
		source =
				let
				    Source = vwLeadActivity,
				    #"Grouped Rows" = Table.Group(Source, {"recordId", "FullName", "referralType", "LeadStatus"}, {{"MinLeadDate", each List.Min([Lead Date Time]), type datetime}, {"MinActivityDate", each List.Min([ActivityDatetime]), type nullable datetime}}),
				    #"Added Custom" = Table.AddColumn(#"Grouped Rows", "Duration_Minutes", each Duration.TotalMinutes([MinActivityDate] - [MinLeadDate])),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Duration_Hours", each [Duration_Minutes] / 60),
				    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "Duration_Days", each [Duration_Hours] / 24),
				    #"Sorted Rows" = Table.Sort(#"Added Custom2",{{"recordId", Order.Ascending}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Sorted Rows",{{"Duration_Hours", Int64.Type}, {"Duration_Minutes", Int64.Type}, {"Duration_Days", Int64.Type}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each ([MinActivityDate] <> null)),
				    #"Filtered Rows1" = Table.SelectRows(#"Filtered Rows", each [Duration_Days] >= 0),
				    #"Inserted Year" = Table.AddColumn(#"Filtered Rows1", "Year", each Date.Year([MinLeadDate]), Int64.Type),
				    #"Inserted Month" = Table.AddColumn(#"Inserted Year", "Month", each Date.Month([MinLeadDate]), Int64.Type),
				    #"Merged Columns" = Table.CombineColumns(Table.TransformColumnTypes(#"Inserted Month", {{"Year", type text}, {"Month", type text}}, "es-AR"),{"Year", "Month"},Combiner.CombineTextByDelimiter("-", QuoteStyle.None),"Cohort"),
				    #"Merged Queries" = Table.NestedJoin(#"Merged Columns", {"Cohort"}, #"vwLeadActivity - Cohort sort", {"Cohort ID"}, "vwLeadActivity - Cohort sort", JoinKind.LeftOuter),
				    #"Expanded vwLeadActivity - Cohort sort" = Table.ExpandTableColumn(#"Merged Queries", "vwLeadActivity - Cohort sort", {"Cohort Sort"}, {"Cohort Sort"})
				in
				    #"Expanded vwLeadActivity - Cohort sort"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

