table vwLifetimeValue
	lineageTag: 53d3343e-47d9-4c6b-8663-5dc381d36314

	column Market
		dataType: string
		lineageTag: 541e8727-ce60-4986-87b2-377d0749c041
		summarizeBy: none
		sourceColumn: Market

		annotation SummarizationSetBy = Automatic

	column PatientId
		dataType: int64
		formatString: 0
		lineageTag: d580456d-bb92-47ec-a2ef-71ec6f6ab9d5
		summarizeBy: none
		sourceColumn: PatientId

		annotation SummarizationSetBy = User

	column MRNNumber
		dataType: string
		lineageTag: d916602a-23b5-4413-83e9-b6a7aab5cc57
		summarizeBy: none
		sourceColumn: MRNNumber

		annotation SummarizationSetBy = Automatic

	column TherapyIntakeDate
		dataType: dateTime
		formatString: mm/dd/yyyy
		lineageTag: 7e450028-d93d-4b29-8b6e-c7b7a93a664c
		summarizeBy: none
		sourceColumn: TherapyIntakeDate

		variation Variation
			isDefault
			relationship: 328d2de4-c75f-4e16-9af2-7b40b8d24bdb
			defaultHierarchy: LocalDateTable_1407ea7a-c7b3-4394-bf0f-9e1b549ad59e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column PsychIntakeDate
		dataType: dateTime
		formatString: mm/dd/yyyy
		lineageTag: 53a37198-61e8-4e9f-9b71-21607342a66b
		summarizeBy: none
		sourceColumn: PsychIntakeDate

		variation Variation
			isDefault
			relationship: 009565b2-e052-42a5-9b11-1a9bfe77362f
			defaultHierarchy: LocalDateTable_3aad88fb-cdde-4f72-803e-c9d227766630.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column LastCompletedVisitDate
		dataType: dateTime
		formatString: mm/dd/yyyy
		lineageTag: c6da6974-38ea-4dc8-9687-8f3e8ea1eca8
		summarizeBy: none
		sourceColumn: LastCompletedVisitDate

		variation Variation
			isDefault
			relationship: 0b3a6535-39f3-4150-b45e-3229605ea2b9
			defaultHierarchy: LocalDateTable_8899c7db-e4a7-46fd-bc7d-f470c1937f61.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column NextSchedVisitDate
		dataType: dateTime
		formatString: mm/dd/yyyy
		lineageTag: ad501b53-3b46-47c4-894c-fcabdd546034
		summarizeBy: none
		sourceColumn: NextSchedVisitDate

		variation Variation
			isDefault
			relationship: 9c7d53a7-bd0c-4585-9968-9a9212bea1ec
			defaultHierarchy: LocalDateTable_a09d4043-6db8-4543-8ce8-95c3e3063054.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column TherapyVisits
		dataType: int64
		formatString: 0
		lineageTag: 5d05a959-c5ce-4f2b-8ae6-c1d9fab9bd2f
		summarizeBy: sum
		sourceColumn: TherapyVisits

		annotation SummarizationSetBy = Automatic

	column PsychVisits
		dataType: int64
		formatString: 0
		lineageTag: de6da8b7-c18c-4bfd-9a1e-3944f0f7aec2
		summarizeBy: sum
		sourceColumn: PsychVisits

		annotation SummarizationSetBy = Automatic

	column NoShowVisits
		dataType: int64
		formatString: 0
		lineageTag: bb50b068-20f4-40c7-8594-260cca6ced28
		summarizeBy: sum
		sourceColumn: NoShowVisits

		annotation SummarizationSetBy = Automatic

	column CancelVisits
		dataType: int64
		formatString: 0
		lineageTag: d4409780-4459-496b-975b-994f3a9acb35
		summarizeBy: sum
		sourceColumn: CancelVisits

		annotation SummarizationSetBy = Automatic

	column TotalRevenue
		dataType: int64
		formatString: 0
		lineageTag: 3c7db4d0-8e4e-4e0c-9a85-1d853f5f8fb3
		summarizeBy: sum
		sourceColumn: TotalRevenue

		annotation SummarizationSetBy = Automatic

	column FirstIntakeDate
		dataType: string
		lineageTag: 5197e9d2-a1cf-471e-8f32-23a7515645f6
		summarizeBy: none
		sourceColumn: FirstIntakeDate

		annotation SummarizationSetBy = Automatic

	column FirstCompletedVisitDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3e18b735-fc8a-4553-9a6a-ecafd0819be1
		summarizeBy: none
		sourceColumn: FirstCompletedVisitDate

		variation Variation
			isDefault
			relationship: 08ac7272-e2f8-4024-8177-f9b78ab67f0b
			defaultHierarchy: LocalDateTable_edbdfeb9-a79a-417f-9a73-de07dda495ae.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FirstAnyVisitStatusAndDate
		dataType: string
		lineageTag: c2461e07-0df4-41ed-91a0-857a594bf21a
		summarizeBy: none
		sourceColumn: FirstAnyVisitStatusAndDate

		annotation SummarizationSetBy = Automatic

	column Completed
		dataType: string
		lineageTag: 8c9c43b4-b3ce-4f0f-bd7f-fcd7e6b1a70f
		summarizeBy: none
		sourceColumn: Completed

		annotation SummarizationSetBy = Automatic

	column FacilityName
		dataType: string
		lineageTag: 9160cf34-cecc-47fc-8dc9-99d24aa3f8ac
		summarizeBy: none
		sourceColumn: FacilityName

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		lineageTag: 83c50770-55f4-4919-a158-48e77c1621ab
		summarizeBy: none
		sourceColumn: FirstName

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: 8ee9a0cc-57c0-4705-a8bc-5f95357bf6ee
		summarizeBy: none
		sourceColumn: LastName

		annotation SummarizationSetBy = Automatic

	column TeleVisits
		dataType: int64
		formatString: 0
		lineageTag: 80fa00cc-b95f-46bf-a933-a64d1e7bdeae
		summarizeBy: sum
		sourceColumn: TeleVisits

		annotation SummarizationSetBy = Automatic

	column InPersonVisits
		dataType: int64
		formatString: 0
		lineageTag: 0e4223e0-e19a-4a02-9508-c124425d9a24
		summarizeBy: sum
		sourceColumn: InPersonVisits

		annotation SummarizationSetBy = Automatic

	column PayerName
		dataType: string
		lineageTag: 70baae0d-48b9-42dc-94c8-244b56fd19ca
		summarizeBy: none
		sourceColumn: PayerName

		annotation SummarizationSetBy = Automatic

	column CategoryDesc
		dataType: string
		lineageTag: e424d017-3856-4245-8c5a-dcc8a028e506
		summarizeBy: none
		sourceColumn: CategoryDesc

		annotation SummarizationSetBy = Automatic

	partition vwLifetimeValue-a0032ae9-2774-46ad-8094-7152a89cfee0 = m
		mode: import
		queryGroup: FACT\LifeTimeValue
		source =
				let
				    Source = Sql.Database("azr-cbh-use1-sql-server01.database.windows.net", "CollectiveBH"),
				    dbo_vwLifeTimeValue = Source{[Schema="dbo",Item="vwLifeTimeValue"]}[Data],
				    #"Removed Duplicates" = Table.Distinct(dbo_vwLifeTimeValue, {"PatientId"}),
				    #"Added Conditional Column" = Table.AddColumn(#"Removed Duplicates", "Completed", each if [FirstCompletedVisitDate] <> null then "Completed" else "Not Completed")
				in
				    #"Added Conditional Column"

	annotation PBI_ResultType = Exception

