table vwPanelGender
	lineageTag: 3658efc1-0da4-431b-8d24-c2ed40ac26a5

	column ResourceId
		dataType: int64
		formatString: 0
		lineageTag: acaa98ca-9d4c-45d9-b860-f853f06b311b
		summarizeBy: none
		sourceColumn: ResourceId

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: a98160b9-0f37-4238-b449-eaceb92c43ea
		summarizeBy: none
		sourceColumn: LastName

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		lineageTag: a7e23fba-3974-4280-8618-210bb3e744b7
		summarizeBy: none
		sourceColumn: FirstName

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 9dca4d0e-ba0b-44d5-b6fc-dfafdb402ae5
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column TotalPanel
		dataType: int64
		formatString: 0
		lineageTag: 9314d03a-3a0b-49c2-bd6c-b43ad0d8702b
		summarizeBy: sum
		sourceColumn: TotalPanel

		annotation SummarizationSetBy = Automatic

	column ActivePanel
		dataType: int64
		formatString: 0
		lineageTag: 5e43fb5c-b004-48a7-8324-92a7ebda5f93
		summarizeBy: sum
		sourceColumn: ActivePanel

		annotation SummarizationSetBy = Automatic

	partition vwPanelGender = m
		mode: import
		queryGroup: FACT\Panel
		source =
				let
				    Source = Source,
				    #"Filtered Rows" = Table.SelectRows(Source, each Text.Contains([Name], "Panel") and Text.Contains([Name], "Combined")),
				    dbo_vwSumClinicianPanelGender = #"Filtered Rows"{[Schema="dbo",Item="vwSumClinicianPanelGenderCombined"]}[Data]
				in
				    dbo_vwSumClinicianPanelGender

	annotation PBI_ResultType = Exception

