table vwPatientFollowUp
	lineageTag: 0247988c-278a-483a-b8da-c4a556fd9348

	column Market
		dataType: string
		lineageTag: aec2f444-e4d0-4b2d-a7cb-cf7c96d05ae0
		summarizeBy: none
		sourceColumn: Market

		annotation SummarizationSetBy = Automatic

	column FacilityName
		dataType: string
		lineageTag: 8e96c55d-688a-4e44-83f2-b203d063845d
		summarizeBy: none
		sourceColumn: FacilityName

		annotation SummarizationSetBy = Automatic

	column PatientId
		dataType: int64
		formatString: 0
		lineageTag: b36e551a-15ed-4ad5-bd18-9ee887642286
		summarizeBy: count
		sourceColumn: PatientId

		annotation SummarizationSetBy = Automatic

	column MRNNumber
		dataType: string
		lineageTag: de2670d9-ffef-47c1-8fef-dc5e6cb9e33c
		summarizeBy: none
		sourceColumn: MRNNumber

		annotation SummarizationSetBy = Automatic

	column PayerName
		dataType: string
		lineageTag: 05b7931a-4320-4d83-bfb8-573ddceeccdc
		summarizeBy: none
		sourceColumn: PayerName

		annotation SummarizationSetBy = Automatic

	column FirstCompletedVisitDate
		dataType: dateTime
		formatString: mm/dd/yyyy
		lineageTag: 869cd705-2b11-4740-a082-cc8222604eb5
		summarizeBy: none
		sourceColumn: FirstCompletedVisitDate

		variation Variation
			isDefault
			relationship: 1d6212eb-84a7-4fe1-be35-251f4327316f
			defaultHierarchy: LocalDateTable_08d5342f-d308-4892-9856-f7f584d58157.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column LastCompletedVisitDate
		dataType: dateTime
		formatString: mm/dd/yyyy
		lineageTag: dbbf6cf3-4c9b-4a81-94bd-a9b7aedfbe3a
		summarizeBy: none
		sourceColumn: LastCompletedVisitDate

		variation Variation
			isDefault
			relationship: c14f17c3-c3a6-4868-9ec3-d1483c420ec7
			defaultHierarchy: LocalDateTable_9e968f9b-6bd0-4f34-8255-2140b44d33f2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column ProviderCategory
		dataType: string
		lineageTag: e90deb65-fd3d-4d97-b17a-ef80f91d5a6e
		summarizeBy: none
		sourceColumn: ProviderCategory

		annotation SummarizationSetBy = Automatic

	column InsuranceBal
		dataType: double
		formatString: 0
		lineageTag: db80c66f-cb96-439b-a495-23e6b96596d9
		summarizeBy: sum
		sourceColumn: InsuranceBal

		annotation SummarizationSetBy = Automatic

	column CopayBal
		dataType: double
		formatString: 0
		lineageTag: 25503d9f-5419-44ee-8823-ff569f1f0b28
		summarizeBy: sum
		sourceColumn: CopayBal

		annotation SummarizationSetBy = Automatic

	column PatientBal
		dataType: double
		formatString: 0
		lineageTag: 0c230a7f-4fba-4c18-a4d3-94c5c54357b6
		summarizeBy: sum
		sourceColumn: PatientBal

		annotation SummarizationSetBy = Automatic

	column PatientFullName
		dataType: string
		lineageTag: e2e34696-6268-4bf0-9551-779635bbee94
		summarizeBy: none
		sourceColumn: PatientFullName

		annotation SummarizationSetBy = Automatic

	column ClinicianFullName
		dataType: string
		lineageTag: fc2b70f2-8c13-41d9-9123-906cd3e641e6
		summarizeBy: none
		sourceColumn: ClinicianFullName

		annotation SummarizationSetBy = Automatic

	partition vwPatientFollowUp = m
		mode: import
		queryGroup: Settings
		source =
				let
				    Source = Sql.Database(ServerName, DBName),
				    dbo_vwPatientFollowUp = Source{[Schema="dbo",Item="vwPatientFollowUp"]}[Data],
				    #"Merged Columns" = Table.CombineColumns(dbo_vwPatientFollowUp,{"PatientLastName", "PatientFirstName"},Combiner.CombineTextByDelimiter(", ", QuoteStyle.None),"PatientFullName"),
				    #"Merged Columns1" = Table.CombineColumns(#"Merged Columns",{"ProviderLastName", "ProviderFirstName"},Combiner.CombineTextByDelimiter(", ", QuoteStyle.None),"ClinicianFullName")
				in
				    #"Merged Columns1"

	annotation PBI_ResultType = Exception

