table vwPanelAvgVisits
	lineageTag: 0d4ae430-7672-4cb8-9fb0-7f9a82f53106

	column ResourceId
		dataType: int64
		formatString: 0
		lineageTag: 8785432a-1769-41e3-afed-a5095aad8b32
		summarizeBy: none
		sourceColumn: ResourceId

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: 047bf666-1954-4476-afeb-3d5e6e13e77c
		summarizeBy: none
		sourceColumn: LastName

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		lineageTag: d26e93a1-96c4-4153-91b5-2fa092a7dd1e
		summarizeBy: none
		sourceColumn: FirstName

		annotation SummarizationSetBy = Automatic

	column TotalPanel
		dataType: int64
		formatString: 0
		lineageTag: b92bdd8e-b42e-435d-a089-b9f01e2505d1
		summarizeBy: sum
		sourceColumn: TotalPanel

		annotation SummarizationSetBy = Automatic

	column ActivePanel
		dataType: int64
		formatString: 0
		lineageTag: 3caf8b29-3479-4318-bef5-ec780383de89
		summarizeBy: sum
		sourceColumn: ActivePanel

		annotation SummarizationSetBy = Automatic

	column TotalVisits
		dataType: int64
		formatString: 0
		lineageTag: bacad6db-bfc0-4288-bbda-2b37a54f18bf
		summarizeBy: sum
		sourceColumn: TotalVisits

		annotation SummarizationSetBy = Automatic

	column ActiveVisits
		dataType: int64
		formatString: 0
		lineageTag: 67d60803-ceb4-4045-845c-189b447f3478
		summarizeBy: sum
		sourceColumn: ActiveVisits

		annotation SummarizationSetBy = Automatic

	partition vwPanelAvgVisits = m
		mode: import
		queryGroup: FACT\Panel
		source =
				let
				    Source = Source,
				    #"Filtered Rows" = Table.SelectRows(Source, each Text.Contains([Name], "Panel") and Text.Contains([Name], "Combined")),
				    dbo_vwSumClinicianPanelAvgVisits = #"Filtered Rows"{[Schema="dbo",Item="vwSumClinicianPanelAvgVisitsCombined"]}[Data]
				in
				    dbo_vwSumClinicianPanelAvgVisits

	annotation PBI_ResultType = Exception

