table vwPatientDisorders
	lineageTag: 25673286-607f-4e33-8e37-c2f80a574c1d

	column PatientId
		dataType: int64
		formatString: 0
		lineageTag: ace85387-3f32-485d-b754-58e4d5bd5d78
		summarizeBy: none
		sourceColumn: PatientId

		annotation SummarizationSetBy = Automatic

	column Attribute
		dataType: string
		lineageTag: 8623833d-0e18-44d8-9772-2cc9e92aca27
		summarizeBy: none
		sourceColumn: Attribute

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: int64
		formatString: 0
		lineageTag: 55b8ec31-f908-42f0-b5be-02d60c4c90af
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	column IsAnxiety
		dataType: int64
		formatString: 0
		lineageTag: 8bea14ec-66d8-4ef3-8f22-fc0185740242
		summarizeBy: sum
		sourceColumn: IsAnxiety

		annotation SummarizationSetBy = Automatic

	column IsDepressive
		dataType: int64
		formatString: 0
		lineageTag: 5646ce78-9a44-4f0d-9a1d-f6159755a778
		summarizeBy: sum
		sourceColumn: IsDepressive

		annotation SummarizationSetBy = Automatic

	partition vwPatientDisorders = m
		mode: import
		queryGroup: 'FACT\Clinical Analytics'
		source =
				let
				    Source = Sql.Database("azr-cbh-use1-sql-server01.database.windows.net", "CollectiveBH"),
				    dbo_vwPatientDisorders = Source{[Schema="dbo",Item="vwPatientDisorders"]}[Data],
				    #"Unpivoted Only Selected Columns" = Table.Unpivot(dbo_vwPatientDisorders, {"Attention-Deficit Disorders","Anxiety Disorders", "Bipolar-spectrum Disorders", "Depressive Disorders", "Feeding/Eating Disorders", "Neurocognitive Disorders", "Obsessive/compulsive Disorders", "Personality Disorder", "Psychotic Disorders", "Sleep-wake Disorders", "Substance Use Disorders", "Trauma-related Disorders"}, "Attribute", "Value"),
				    #"Filtered Rows" = Table.SelectRows(#"Unpivoted Only Selected Columns", each ([Value] = 1))
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Exception

