table vwPanelDisorders
	lineageTag: 34e9f9d0-f493-4a9a-a496-0d04339aa183

	column ResourceId
		dataType: int64
		formatString: 0
		lineageTag: e7ab9715-9891-4d32-9c5b-6786f925b219
		summarizeBy: none
		sourceColumn: ResourceId

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: 4378c3cc-c4cc-4c58-8706-40d7d894056f
		summarizeBy: none
		sourceColumn: LastName

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		lineageTag: 4cd98572-2472-448d-870c-a4970aa92b7e
		summarizeBy: none
		sourceColumn: FirstName

		annotation SummarizationSetBy = Automatic

	column DisorderType
		dataType: string
		lineageTag: 1b73bed9-73c8-4dc5-add4-b1c071a3f67e
		summarizeBy: none
		sourceColumn: DisorderType

		annotation SummarizationSetBy = Automatic

	column TotalDisorderCount
		dataType: int64
		formatString: 0
		lineageTag: 257cfbbc-2053-446c-9014-15b168ac69bd
		summarizeBy: sum
		sourceColumn: TotalDisorderCount

		annotation SummarizationSetBy = Automatic

	column ActiveDisorderCount
		dataType: int64
		formatString: 0
		lineageTag: 8a1787f8-ee6d-4c02-b518-fd3de0dff2ff
		summarizeBy: sum
		sourceColumn: ActiveDisorderCount

		annotation SummarizationSetBy = Automatic

	partition vwPanelDisorders = m
		mode: import
		queryGroup: FACT\Panel
		source =
				let
				    Source = Source,
				    #"Filtered Rows" = Table.SelectRows(Source, each Text.Contains([Name], "Panel") and Text.Contains([Name], "Combined")),
				    dbo_vwSumClinicianPanelDisorders = #"Filtered Rows"{[Schema="dbo",Item="vwSumClinicianPanelDisordersCombined"]}[Data]
				in
				    dbo_vwSumClinicianPanelDisorders

	annotation PBI_ResultType = Exception

