table vwScheduleVisitDetails
	lineageTag: 4447be4f-aed7-4a7a-8adb-fb202463d490

	column VisitID
		dataType: int64
		formatString: 0
		lineageTag: 9b02c7d0-8b44-4b60-8d38-0380ee3b7c72
		summarizeBy: count
		sourceColumn: VisitID

		annotation SummarizationSetBy = Automatic

	column ScheduleID
		dataType: int64
		formatString: 0
		lineageTag: a22ebdf1-9945-4221-8bc6-3af3e9381ef3
		summarizeBy: none
		sourceColumn: ScheduleID

		annotation SummarizationSetBy = User

	column PatientID
		dataType: int64
		formatString: 0
		lineageTag: 391c8514-f5b8-4960-a925-0d2824664610
		summarizeBy: none
		sourceColumn: PatientID

		annotation SummarizationSetBy = User

	column PracticeID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 80a7fba1-0c54-48a2-aded-6cd1aed83329
		summarizeBy: none
		sourceColumn: PracticeID

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column FacilityID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 70743fc8-245d-4c55-b168-82b483baeca5
		summarizeBy: none
		sourceColumn: FacilityID

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column ResourceTypeID
		dataType: int64
		formatString: 0
		lineageTag: 88156d78-95f5-4d38-9088-9a30cad91b95
		summarizeBy: none
		sourceColumn: ResourceTypeID

		annotation SummarizationSetBy = User

	column ResourceID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 6a740247-b11e-4646-a628-877a942430fa
		summarizeBy: none
		sourceColumn: ResourceID

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column VisitDate
		dataType: dateTime
		formatString: mm/dd/yyyy
		lineageTag: e0fb30ab-d501-457d-8bcd-372afcd7d590
		summarizeBy: none
		sourceColumn: VisitDate

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column VisitStatusID
		dataType: int64
		formatString: 0
		lineageTag: 9d8a970c-369b-4843-a275-7ed01a1e93de
		summarizeBy: none
		sourceColumn: VisitStatusID

		annotation SummarizationSetBy = Automatic

	column NextAppt
		dataType: dateTime
		formatString: mm/dd/yyyy
		lineageTag: 2e749474-9015-4fd5-86f7-59e4d951655f
		summarizeBy: none
		sourceColumn: NextAppt

		variation Variation
			isDefault
			relationship: cc86c029-8a5e-4428-b502-0c83ac74fc01
			defaultHierarchy: LocalDateTable_8c5ca60d-1872-4e95-97ab-d39d2ed8d530.'Date Hierarchy'

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column PrevAppt
		dataType: dateTime
		formatString: mm/dd/yyyy
		lineageTag: 2dad58a2-b04b-459d-8ff8-7ccc6bb7823f
		summarizeBy: none
		sourceColumn: PrevAppt

		variation Variation
			isDefault
			relationship: ce6f58f4-9024-4ae5-9e8a-426c0dd049b6
			defaultHierarchy: LocalDateTable_3b0168d4-bd1e-4736-b7c9-f3f92be9c971.'Date Hierarchy'

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column MRNNumber
		dataType: string
		lineageTag: d105c946-4be6-4db6-81ce-482955c07314
		summarizeBy: none
		sourceColumn: MRNNumber

		annotation SummarizationSetBy = Automatic

	column VisitTypeID
		dataType: int64
		formatString: 0
		lineageTag: 02ebf7b9-1de9-4441-9c61-d48961d01405
		summarizeBy: none
		sourceColumn: VisitTypeID

		annotation SummarizationSetBy = Automatic

	column 'Difference Between Dates' = DATEDIFF(vwScheduleVisitDetails[VisitDate], vwScheduleVisitDetails[NextAppt], DAY)
		formatString: 0
		lineageTag: 0fe71383-1c84-4719-9c65-d696f810744b
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Duration
		dataType: int64
		formatString: 0
		lineageTag: 78920df2-cbda-48b2-86d4-b1000194d1ac
		summarizeBy: sum
		sourceColumn: Duration

		annotation SummarizationSetBy = Automatic

	column 'MRN - Visit Date'
		dataType: string
		lineageTag: 208717e3-3808-490c-b887-46cdefd568ee
		summarizeBy: none
		sourceColumn: MRN - Visit Date

		annotation SummarizationSetBy = Automatic

	column StartTime
		dataType: dateTime
		formatString: General Date
		lineageTag: f20f1348-2f22-4a4d-83bc-2bc2613ffade
		summarizeBy: none
		sourceColumn: StartTime

		variation Variation
			isDefault
			relationship: df416ba9-4764-45e0-9e37-20a256407521
			defaultHierarchy: LocalDateTable_bb857195-c4ac-4c95-97dc-20ee7b964c3c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column EndTime
		dataType: dateTime
		formatString: General Date
		lineageTag: 2076b78e-a2ea-4f3d-b0d4-e8e58523166c
		summarizeBy: none
		sourceColumn: EndTime

		variation Variation
			isDefault
			relationship: 4a14e0d6-209f-4116-98a5-25e2670dd660
			defaultHierarchy: LocalDateTable_b86f3cd3-84b3-46cb-9bad-2451e3aa1b7a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: c8f6ed78-e71a-40b3-bf3f-f42c542115d7
		summarizeBy: none
		sourceColumn: LastName

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		lineageTag: b30884f3-3312-4187-8378-6617ee1de0c5
		summarizeBy: none
		sourceColumn: FirstName

		annotation SummarizationSetBy = Automatic

	partition vwScheduleVisitDetails-b118f584-0caa-4d84-b5ff-f84c763d5da1 = m
		mode: import
		queryGroup: FACT
		source =
				let
				    Source = Sql.Database(ServerName, DBName),
				    dbo_vwScheduleVisitDetails = Source{[Schema="dbo",Item="vwScheduleVisitDetails"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(dbo_vwScheduleVisitDetails,{{"VisitID", Int64.Type}, {"ScheduleID", Int64.Type}, {"PatientID", Int64.Type}, {"PracticeID", Int64.Type}, {"FacilityID", Int64.Type}, {"ResourceTypeID", Int64.Type}, {"ResourceID", Int64.Type}, {"VisitDate", type date}, {"VisitStatusID", Int64.Type}, {"NextAppt", type date}, {"PrevAppt", type date}, {"VisitTypeID", Int64.Type}, {"MRNNumber", type text}, {"Duration", Int64.Type}}),
				    #"Inserted Merged Column" = Table.AddColumn(#"Changed Type", "MRN - Visit Date", each Text.Combine({[MRNNumber], Text.From([VisitDate], "en-US")}, " - "), type text)
				in
				    #"Inserted Merged Column"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

