table vwSummaryUtilizationByResource
	lineageTag: 4aebdbe9-1644-4af1-b346-b237f4ec478e

	column ResourceId
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b732a8ed-e95a-44f6-b572-c67d0119686f
		summarizeBy: none
		sourceColumn: ResourceId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		isHidden
		lineageTag: e8e4d4dc-71b8-46e9-870e-800149845569
		summarizeBy: none
		sourceColumn: LastName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		isHidden
		lineageTag: 4b2d73ef-f0f0-4587-8736-4d9d1d8be6b1
		summarizeBy: none
		sourceColumn: FirstName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ProviderCategory
		dataType: string
		lineageTag: da57c20b-6a1a-42c6-86e1-cc23229fb9a1
		summarizeBy: none
		sourceColumn: ProviderCategory

		annotation SummarizationSetBy = Automatic

	column FacilityName
		dataType: string
		lineageTag: faaab765-6313-43d4-91a4-f1bd564a54ea
		summarizeBy: none
		sourceColumn: FacilityName

		annotation SummarizationSetBy = Automatic

	column VisitDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 25664eb9-7159-48ba-9654-15c080a20b86
		summarizeBy: none
		sourceColumn: VisitDate

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column WeekName
		dataType: string
		lineageTag: 4ef22d00-5e2f-4eb5-b051-c0b43603e075
		summarizeBy: none
		sourceColumn: WeekName

		annotation SummarizationSetBy = Automatic

	column Hours
		dataType: double
		lineageTag: 9ad1db60-4c65-4411-8b9a-5f719b5fc12f
		summarizeBy: sum
		sourceColumn: Hours

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Goal
		dataType: double
		lineageTag: f279fa7f-003b-4583-9be1-275ef98196e7
		summarizeBy: sum
		sourceColumn: Goal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column numVisits
		dataType: int64
		formatString: 0
		lineageTag: 88ae0b0f-1b58-4e6a-bbcf-51692abea67f
		summarizeBy: sum
		sourceColumn: numVisits

		annotation SummarizationSetBy = Automatic

	column 'Full name'
		dataType: string
		lineageTag: e9d988a7-b67c-4795-910e-4400c66bbd04
		summarizeBy: none
		sourceColumn: Full name

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: 7693fdbf-e35e-441e-9ae7-23b43a5ed502
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column StartWeek
		dataType: dateTime
		formatString: Short Date
		lineageTag: 62286a6c-74c5-4947-9cb1-b42fc58341e4
		summarizeBy: none
		sourceColumn: StartWeek

		variation Variation
			isDefault
			relationship: 5dda96c7-a890-408f-8b01-a613247bf573
			defaultHierarchy: LocalDateTable_bf0329ad-b435-46b2-a9f8-de0bef56de3f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column EndWeek
		dataType: dateTime
		formatString: Short Date
		lineageTag: 6fa57eae-9291-4bf1-b321-f4c5d39f0a55
		summarizeBy: none
		sourceColumn: EndWeek

		variation Variation
			isDefault
			relationship: 5fe3d497-7b88-47b9-9f89-92cafa412279
			defaultHierarchy: LocalDateTable_200cebd6-6d5a-4345-abbf-eafa221567c2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column WeekNew
		dataType: string
		lineageTag: ffc86cda-d30e-4899-935d-c5cd40b3a05c
		summarizeBy: none
		sourceColumn: WeekNew

		annotation SummarizationSetBy = Automatic

	partition vwSummaryUtilizationByResource-5399f84e-5138-48cc-9554-ee13eb368e52 = m
		mode: import
		queryGroup: FACT
		source =
				let
				    Source = Sql.Database(ServerName, DBName),
				    dbo_vwSummaryUtilizationByResource = Source{[Schema="dbo",Item="vwSummaryUtilizationByResource"]}[Data],
				    #"Inserted Merged Column" = Table.AddColumn(dbo_vwSummaryUtilizationByResource, "Full name", each Text.Combine({[LastName], [FirstName]}, ", "), type text),
				    #"Added Custom" = Table.AddColumn(#"Inserted Merged Column", "startweektxt", each Date.ToText([StartWeek],"yy-MM-dd")),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "EndWeekText", each Date.ToText([EndWeek],"yy-MM-dd")),
				    #"Merged Columns" = Table.CombineColumns(#"Added Custom1",{"startweektxt", "EndWeekText"},Combiner.CombineTextByDelimiter(" - ", QuoteStyle.None),"WeekNew"),
				    #"Changed Type" = Table.TransformColumnTypes(#"Merged Columns",{{"VisitDate", type date}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Exception

