table vwSumPaymentClaim
	lineageTag: 782b1f23-96b4-4b18-a9e9-61140889cf85

	column ChargeID
		dataType: int64
		formatString: 0
		lineageTag: 206663c5-4e32-4d66-af23-16aafc08ca9b
		summarizeBy: count
		sourceColumn: ChargeID

		annotation SummarizationSetBy = Automatic

	column EncounterID
		dataType: int64
		formatString: 0
		lineageTag: 7f1a1766-9da9-481c-a8a9-57db68a7a7dd
		summarizeBy: none
		sourceColumn: EncounterID

		annotation SummarizationSetBy = User

	column PatientID
		dataType: int64
		formatString: 0
		lineageTag: 31fdeaa7-26ed-4c25-942c-d6e56bfaef1b
		summarizeBy: none
		sourceColumn: PatientID

		annotation SummarizationSetBy = User

	column MRNNumber
		dataType: string
		lineageTag: 98a45d7b-efce-46e9-b3c8-43452fb10fd3
		summarizeBy: none
		sourceColumn: MRNNumber

		annotation SummarizationSetBy = Automatic

	column FacilityID
		dataType: int64
		formatString: 0
		lineageTag: e34f007c-37a2-4e01-9c3b-44ef296e047d
		summarizeBy: none
		sourceColumn: FacilityID

		annotation SummarizationSetBy = Automatic

	column ProviderID
		dataType: int64
		formatString: 0
		lineageTag: a7b1908e-a4f6-4314-be2d-4e396378d581
		summarizeBy: none
		sourceColumn: ProviderID

		annotation SummarizationSetBy = User

	column VisitDate
		dataType: dateTime
		formatString: mm/dd/yyyy
		lineageTag: fb93d831-0afb-4a38-827d-f61d9facf992
		summarizeBy: none
		sourceColumn: VisitDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Charges
		dataType: double
		lineageTag: 7f914224-2b1b-48f8-a711-7b36a4d66ed9
		summarizeBy: sum
		sourceColumn: Charges

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PayerName
		dataType: string
		lineageTag: cf8bbe64-614b-411a-929a-fe37e49c5bb6
		summarizeBy: none
		sourceColumn: PayerName

		annotation SummarizationSetBy = Automatic

	column CoPayment
		dataType: double
		lineageTag: 81bdb8ea-a450-4911-a9b7-187db7320c45
		summarizeBy: sum
		sourceColumn: CoPayment

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CoInsuranceValue
		dataType: double
		lineageTag: aa1d41f5-6b9e-4623-87b5-81d8e22fa7f3
		summarizeBy: sum
		sourceColumn: CoInsuranceValue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Deductible
		dataType: double
		lineageTag: a541e47e-f40b-49ac-af4e-5e015a7c1166
		summarizeBy: sum
		sourceColumn: Deductible

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PayerFee
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: baf8360a-7957-480a-875f-7826ae6850b0
		summarizeBy: sum
		sourceColumn: PayerFee

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column InsurancePayment
		dataType: double
		lineageTag: a7af8a2c-ea23-450b-b18d-8d2fc3f965c4
		summarizeBy: sum
		sourceColumn: InsurancePayment

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PatientPayment
		dataType: double
		lineageTag: e08bb504-df90-42f1-adf2-379d956911ab
		summarizeBy: sum
		sourceColumn: PatientPayment

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CreditAdJustment
		dataType: double
		lineageTag: 3162788a-fb93-4569-9395-9864caf628c2
		summarizeBy: sum
		sourceColumn: CreditAdJustment

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DebitAdjustment
		dataType: double
		lineageTag: 84b453bb-9e61-4134-b869-695fe0914b39
		summarizeBy: sum
		sourceColumn: DebitAdjustment

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Writeoff
		dataType: double
		lineageTag: bba1584b-25bd-4408-bba4-fd90f71ef648
		summarizeBy: sum
		sourceColumn: Writeoff

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Denial
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 4849f262-cd9c-4d94-acd6-4678ab572efc
		summarizeBy: sum
		sourceColumn: Denial

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Transfer
		dataType: double
		lineageTag: 0b95c8ae-1f2b-475f-ad5e-f81227b726dd
		summarizeBy: sum
		sourceColumn: Transfer

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Void
		dataType: double
		lineageTag: 59c62e2a-27db-4b53-97f4-393b1b1326b5
		summarizeBy: sum
		sourceColumn: Void

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Refund
		dataType: double
		lineageTag: 3c31ebb3-5691-46c8-abdd-1589dd6d5f7f
		summarizeBy: sum
		sourceColumn: Refund

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GrandTotalAR
		dataType: double
		lineageTag: 4a819f65-9ee5-4a68-a183-e74bf7fdecc5
		summarizeBy: sum
		sourceColumn: GrandTotalAR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Copay Difference'
		dataType: string
		lineageTag: 61073aff-a09f-465e-9f5f-585e75aff78c
		summarizeBy: none
		sourceColumn: Copay Difference

		annotation SummarizationSetBy = Automatic

	column CopayExceptions
		dataType: string
		lineageTag: 8c52fecf-29a1-4a93-9500-b6f1312af8f7
		summarizeBy: none
		sourceColumn: CopayExceptions

		annotation SummarizationSetBy = Automatic

	partition vwSumPaymentClaim = m
		mode: import
		queryGroup: Settings
		source =
				let
				    Source = Sql.Database(ServerName, DBName),
				    dbo_vwSumPaymentClaim = Source{[Schema="dbo",Item="vwSumPaymentClaim"]}[Data],
				    #"Added Custom" = Table.AddColumn(dbo_vwSumPaymentClaim, "Copay Difference", each [PatientPayment]-[CoPayment]),
				    #"Added Conditional Column" = Table.AddColumn(#"Added Custom", "CopayExceptions", each if [Copay Difference] = 0 then "Copay Paid" else if [Copay Difference] > 0 then "Extra Copay Paid" else if [Copay Difference] < 0 then "Copay Missed" else "No Copay Information")
				in
				    #"Added Conditional Column"

	annotation PBI_ResultType = Exception

