table vwVisitCosignPending
	lineageTag: 85af91f5-66f5-4934-bc95-d9df3b15b182

	measure '__ VisitsCosingPending RequestID' = COUNT(vwVisitCosignPending[RequestId])
		lineageTag: b9bcf243-297f-409b-a26c-d6b23d052bb8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RequestId
		dataType: int64
		formatString: 0
		lineageTag: aa83235f-66a6-4169-8394-c5a17d587eb4
		summarizeBy: count
		sourceColumn: RequestId

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 6aa8c35f-9601-4747-b9bd-56b4ccd9586c
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Market
		dataType: string
		lineageTag: 13b76001-4646-4dbe-881c-56310cd62e81
		summarizeBy: none
		sourceColumn: Market

		annotation SummarizationSetBy = Automatic

	column FacilityName
		dataType: string
		lineageTag: ed8498fd-f764-4c65-8220-aab201b9924f
		summarizeBy: none
		sourceColumn: FacilityName

		annotation SummarizationSetBy = Automatic

	column VisitDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: b4eb1ae4-137b-408e-bf2a-b03d7fdf58c3
		summarizeBy: none
		sourceColumn: VisitDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DurationGroup
		dataType: string
		lineageTag: af2cdd65-07da-4a9d-a1f6-a4da8c7625e6
		summarizeBy: none
		sourceColumn: DurationGroup
		sortByColumn: DurationGroupSort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column NoteClosedDateTime
		dataType: dateTime
		formatString: Short Date
		lineageTag: 7841e45f-7aa0-4670-9bce-1adb32495710
		summarizeBy: none
		sourceColumn: NoteClosedDateTime

		variation Variation
			isDefault
			relationship: 9fb6e1d3-a66e-4a6f-b14e-faf6c0e8a49b
			defaultHierarchy: LocalDateTable_f204f287-5077-455f-8519-6c9b1db58110.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column EncounterType
		dataType: string
		lineageTag: 08920b99-1e31-474a-b995-be097cc4aaac
		summarizeBy: none
		sourceColumn: EncounterType

		annotation SummarizationSetBy = Automatic

	column PatientName
		dataType: string
		lineageTag: 9dab8f1c-5859-443a-a798-c84da9d5d4ce
		summarizeBy: none
		sourceColumn: PatientName

		annotation SummarizationSetBy = Automatic

	column ProviderName
		dataType: string
		lineageTag: ad65102c-ee8d-48d0-bee7-34a2f7c90e2a
		summarizeBy: none
		sourceColumn: ProviderName

		annotation SummarizationSetBy = Automatic

	column CoSignerName
		dataType: string
		lineageTag: 15cab93c-23be-4a6d-b3bf-a57d2e3582cc
		summarizeBy: none
		sourceColumn: CoSignerName

		annotation SummarizationSetBy = Automatic

	column MRNNumber
		dataType: string
		lineageTag: df0f135b-3239-4314-be2a-79f692af1813
		summarizeBy: none
		sourceColumn: MRNNumber

		annotation SummarizationSetBy = Automatic

	column DurationGroupSort
		dataType: double
		lineageTag: 7dc15b52-9ef2-42aa-bf44-7e1733eeadbe
		summarizeBy: sum
		sourceColumn: DurationGroupSort

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition vwVisitCosignPending = m
		mode: import
		source =
				let
				    Source = Sql.Database("azr-cbh-use1-sql-server01.database.windows.net", "CollectiveBH"),
				    dbo_vwVisitCosignPending = Source{[Schema="dbo",Item="vwVisitCosignPending"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(dbo_vwVisitCosignPending,{{"RequestId", Int64.Type}}),
				    #"Added Conditional Column" = Table.AddColumn(#"Changed Type", "DurationGroupSort", each if [DurationGroup] = "0-14 Days" then 1 else if [DurationGroup] = "15-28 Days" then 2 else if [DurationGroup] = "29-90 Days" then 3 else if [DurationGroup] = "91-180 Days" then 4 else if [DurationGroup] = "180+ Days" then 5 else 6),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Conditional Column",{{"DurationGroupSort", type number}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

