table vwVisitStatusIssues
	lineageTag: cda8daf9-066d-426f-82aa-dcfe3da67a04

	measure __countVSI =
			
			COUNTROWS(vwVisitStatusIssues)
		formatString: #,0
		lineageTag: d5bc4a27-8cfa-4497-8b38-6ea78269f0e5

	column VisitID
		dataType: int64
		formatString: 0
		lineageTag: fbf1f565-33cd-44a7-93a1-c9620f41d847
		summarizeBy: count
		sourceColumn: VisitID

		annotation SummarizationSetBy = Automatic

	column MRNNumber
		dataType: string
		lineageTag: c7632403-f1e7-495b-8651-208af7db166c
		summarizeBy: none
		sourceColumn: MRNNumber

		annotation SummarizationSetBy = Automatic

	column Market
		dataType: string
		lineageTag: 5f91a45c-51c8-49f1-8cac-00886e602003
		summarizeBy: none
		sourceColumn: Market

		annotation SummarizationSetBy = Automatic

	column FacilityName
		dataType: string
		lineageTag: b50ee48d-892a-41cd-a4b3-63924fca899f
		summarizeBy: none
		sourceColumn: FacilityName

		annotation SummarizationSetBy = Automatic

	column ProviderCategory
		dataType: string
		lineageTag: 7c81e28e-8ecc-4c4e-98e3-4e28c0bdd2a0
		summarizeBy: none
		sourceColumn: ProviderCategory

		annotation SummarizationSetBy = Automatic

	column VisitDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: e0a02db7-092f-4bfd-9948-4dc77beb21c3
		summarizeBy: none
		sourceColumn: VisitDate

		variation Variation
			isDefault
			relationship: 87f067ff-d3fe-4b09-9914-5581cd4a8a60
			defaultHierarchy: LocalDateTable_a2e57f2e-3ac5-4f9f-83bf-2315d4f3b7d0.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Duration
		dataType: int64
		formatString: 0
		lineageTag: 675e7d61-d68a-4ae4-a906-4e4e76277c33
		summarizeBy: sum
		sourceColumn: Duration

		annotation SummarizationSetBy = Automatic

	column EncounterCloseDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 0ce355d3-2dd4-4d2b-9406-f8a7f8d482ca
		summarizeBy: none
		sourceColumn: EncounterCloseDate

		variation Variation
			isDefault
			relationship: b9ee1d3d-7219-49bd-9921-a36e74fcce8d
			defaultHierarchy: LocalDateTable_76d38d5e-4eea-4f6b-bfc0-e7a39f714a50.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column VisitStatus
		dataType: string
		lineageTag: b0a49f03-1c3c-4a6d-ac03-7d13f8c32201
		summarizeBy: none
		sourceColumn: VisitStatus

		annotation SummarizationSetBy = Automatic

	column Clinician
		dataType: string
		lineageTag: 43a2d6d6-dad9-4456-a68a-497687dfdba3
		summarizeBy: none
		sourceColumn: Clinician

		annotation SummarizationSetBy = Automatic

	partition vwVisitStatusIssues = m
		mode: import
		queryGroup: FACT\DailyOps
		source =
				let
				    Source = Source,
				    dbo_vwVisitStatusIssues = Source{[Schema="dbo",Item="vwVisitStatusIssues"]}[Data],
				    #"Merged Columns" = Table.CombineColumns(dbo_vwVisitStatusIssues,{"ProviderLastName", "ProviderFirstName"},Combiner.CombineTextByDelimiter(", ", QuoteStyle.None),"Clinician"),
				    #"Changed Type" = Table.TransformColumnTypes(#"Merged Columns",{{"Duration", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

