table vwVisitIssueLog
	lineageTag: f35fb000-cdfd-493e-9979-82075aaeece6

	measure '__ Visits Issue log' = ```
			COUNT( vwVisitIssueLog[VisitID] ) 
			```
		formatString: #,0
		lineageTag: ebaa70ff-e1d7-45f3-9a78-a8b320f4e9f6

	measure '__ Visits Issue log distinct' = ```
			DISTINCTCOUNT( vwVisitIssueLog[VisitID] ) 
			```
		formatString: #,0
		lineageTag: cae0a51c-eaf1-4d93-92e7-a138c9a1aa25

	column VisitID
		dataType: int64
		formatString: 0
		lineageTag: a99dbe1f-0821-4395-81bd-74926dbb0459
		summarizeBy: count
		sourceColumn: VisitID

		annotation SummarizationSetBy = Automatic

	column MRNNumber
		dataType: string
		lineageTag: e653e09b-c9e2-45b8-aba5-c30aa9c7045e
		summarizeBy: none
		sourceColumn: MRNNumber

		annotation SummarizationSetBy = Automatic

	column Market
		dataType: string
		lineageTag: 60a915d2-4a0d-4c30-9c3d-3ecc39438fc8
		summarizeBy: none
		sourceColumn: Market

		annotation SummarizationSetBy = Automatic

	column FacilityName
		dataType: string
		lineageTag: 454b8816-9d74-4c72-9e6e-f5b993f15737
		summarizeBy: none
		sourceColumn: FacilityName

		annotation SummarizationSetBy = Automatic

	column ProviderCategory
		dataType: string
		lineageTag: e8130c1e-eed3-4626-8f8e-bfb20d180a87
		summarizeBy: none
		sourceColumn: ProviderCategory

		annotation SummarizationSetBy = Automatic

	column ServicingProvider
		dataType: string
		lineageTag: 628794a3-07c0-4334-8f86-4d9efc1b7e08
		summarizeBy: none
		sourceColumn: ServicingProvider

		annotation SummarizationSetBy = Automatic

	column BillingProvider
		dataType: string
		lineageTag: 912956f8-2a0b-4f0b-b905-e9a24f3f3dfd
		summarizeBy: none
		sourceColumn: BillingProvider

		annotation SummarizationSetBy = Automatic

	column VisitDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 2904bf53-be97-4d8f-b793-293ae59ee77e
		summarizeBy: none
		sourceColumn: VisitDate

		variation Variation
			isDefault
			relationship: 3ee2f5db-bb18-442f-8a1f-fecf723efa2e
			defaultHierarchy: LocalDateTable_5d38f683-cf73-4820-a314-1dcbaf918089.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column VisitStatus
		dataType: string
		lineageTag: 4ffd8f41-41eb-4c12-9fe6-f069f304a0cd
		summarizeBy: none
		sourceColumn: VisitStatus

		annotation SummarizationSetBy = Automatic

	column PayerPlanName
		dataType: string
		lineageTag: 1b987ce7-cf39-48cd-adfc-f189b347b024
		summarizeBy: none
		sourceColumn: PayerPlanName

		annotation SummarizationSetBy = Automatic

	column PayerName
		dataType: string
		lineageTag: 701ca458-4ec1-457d-b222-2b3d6f443c39
		summarizeBy: none
		sourceColumn: PayerName

		annotation SummarizationSetBy = Automatic

	column EnocunterCloseDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: faae260d-280f-4603-967d-85696a989439
		summarizeBy: none
		sourceColumn: EnocunterCloseDate

		variation Variation
			isDefault
			relationship: e4191afb-6174-4b46-84b5-60530f4815c5
			defaultHierarchy: LocalDateTable_a5b89273-934a-4982-b9b5-4f9b75949b1b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column IssueType
		dataType: string
		lineageTag: 3c86581a-698c-4d3b-8041-978731ad1528
		summarizeBy: none
		sourceColumn: IssueType

		annotation SummarizationSetBy = Automatic

	column PatientLastName
		dataType: string
		lineageTag: f65d3864-bcdc-48eb-b072-ef569dc4fb16
		summarizeBy: none
		sourceColumn: PatientLastName

		annotation SummarizationSetBy = Automatic

	column ProviderStatus
		dataType: string
		lineageTag: 136bcb8d-6319-4fce-a784-1c0a969d857c
		summarizeBy: none
		sourceColumn: ProviderStatus

		annotation SummarizationSetBy = Automatic

	column PatientID
		dataType: int64
		formatString: 0
		lineageTag: 0d05d087-5c85-417b-b885-70ff22541750
		summarizeBy: count
		sourceColumn: PatientID

		annotation SummarizationSetBy = Automatic

	column ResourceEmail
		dataType: string
		lineageTag: f1b7cabe-b553-4635-a53b-3f7154d31cbd
		summarizeBy: none
		sourceColumn: ResourceEmail

		annotation SummarizationSetBy = Automatic

	column CPTCode
		dataType: string
		lineageTag: 864f33db-61bb-4c63-82e0-cef3196f2140
		summarizeBy: none
		sourceColumn: CPTCode

		annotation SummarizationSetBy = Automatic

	column DurationGroup
		dataType: string
		lineageTag: e42b6f61-fa88-4a40-baf6-8d40bc681f5b
		summarizeBy: none
		sourceColumn: DurationGroup
		sortByColumn: DurationGroupSort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column DurationGroupSort
		dataType: double
		lineageTag: 49e99aec-dc62-4cbe-919b-1f0936f7fd10
		summarizeBy: sum
		sourceColumn: DurationGroupSort

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition vwVisitIssueLog = m
		mode: import
		queryGroup: FACT\DailyOps
		source =
				let
				    Source = Sql.Database("azr-cbh-use1-sql-server01.database.windows.net", "CollectiveBH"),
				    dbo_vwVisitIssueLog = Source{[Schema="dbo",Item="vwVisitIssueLog"]}[Data],
				    #"Added Conditional Column" = Table.AddColumn(dbo_vwVisitIssueLog, "DurationGroupSort", each if [DurationGroup] = "0-14 Days" then 1 else if [DurationGroup] = "15-28 Days" then 2 else if [DurationGroup] = "29-90 Days" then 3 else if [DurationGroup] = "91-180 Days" then 4 else if [DurationGroup] = "180+ Days" then 5 else 6),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Conditional Column",{{"DurationGroupSort", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

