table vwVisitTrendByResourceNew
	lineageTag: e1a40be0-e454-465d-b901-b95a5d609cde

	measure 'Completed Visits' = SUM(vwVisitTrendByResourceNew[Completed_Total_Comb])
		lineageTag: a9848590-a488-4c96-905c-1d9d1b67cae2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Completed & Scheduled Visits' = ```
			SUM(vwVisitTrendByResourceNew[Completed_Total_Comb]) + SUM(vwVisitTrendByResourceNew[Pending_Visits]) 
			```
		lineageTag: aaa66f42-e137-4c0c-a8f9-d1b38fddba8a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Scheduled Visits' = ```
			SUM(vwVisitTrendByResourceNew[Pending_Visits]) 
			```
		lineageTag: c4e5973b-70b1-4e94-a87e-04e4327a9a72

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Completed & Scheduled Hrs' = SUM(vwVisitTrendByResourceNew[CompHours]) + SUM(vwVisitTrendByResourceNew[SchdHours])
		lineageTag: 8022d690-e7c9-41b0-854e-ece556189a58

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Scheduled Hrs' = SUM(vwVisitTrendByResourceNew[SchdHours])
		lineageTag: 9141bdb1-2ac4-4249-a80d-e1b496b37044

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Completed Hrs' = SUM(vwVisitTrendByResourceNew[CompHours])
		lineageTag: e793ddf1-78a6-4453-9185-dda59598a8e4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Visual Trend Hrs Title' =
			
			VAR SelectedValue = VALUES('Visit Hrs filter'[Visit Hrs filter Order])
			RETURN
			    SWITCH(
			        TRUE(),
			        SelectedValue= 0,"Completed & Scheduled Hours by Facility",
			        SelectedValue= 1,"Completed Hours by Facility",
			        SelectedValue= 2,"Scheduled Hours by Facility",
			        "Not Selected any"
			        )
		lineageTag: 1abf18cf-8ed3-4d8f-b793-53298cf684fc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Visual Trend Title' = ```
			
			 VAR SelectedValue= VALUES('Visit Status'[Visit Status Order])
			 RETURN
			    SWITCH(
			        TRUE(),
			        SelectedValue = 0,"Completed and Scheduled Appointments by Facility",
			        SelectedValue = 1,"Completed Appointments by Facility",
			        SelectedValue = 2, "Scheduled Appointments by Facility",
			        "Not Selected any values"
			    )
			```
		lineageTag: 1259b638-b83b-41e8-bd0c-4169ef34ebcf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VisitDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 3a1f06f6-72a4-4ca5-bebd-96f6373be2f8
		summarizeBy: none
		sourceColumn: VisitDate

		annotation SummarizationSetBy = Automatic

	column FacilityID
		dataType: int64
		formatString: 0
		lineageTag: ee272e53-5ba7-4d9a-a954-f456c00fd335
		summarizeBy: none
		sourceColumn: FacilityID

		annotation SummarizationSetBy = Automatic

	column Clinician
		dataType: string
		lineageTag: 024703ac-c66b-420f-a2c0-6ca8d86c94e1
		summarizeBy: none
		sourceColumn: Clinician

		annotation SummarizationSetBy = Automatic

	column ProviderCategoryID
		dataType: int64
		formatString: 0
		lineageTag: 463344df-68dd-4ecc-bd1a-573793ff9284
		summarizeBy: count
		sourceColumn: ProviderCategoryID

		annotation SummarizationSetBy = Automatic

	column ResourceId
		dataType: int64
		formatString: 0
		lineageTag: 0b8e8047-38c9-4312-99f8-4c1b0a436bb6
		summarizeBy: count
		sourceColumn: ResourceId

		annotation SummarizationSetBy = Automatic

	column Checkin_Visits
		dataType: int64
		formatString: 0
		lineageTag: 1bf4d702-d212-4674-982c-3eaf079b6eb2
		summarizeBy: sum
		sourceColumn: Checkin_Visits

		annotation SummarizationSetBy = Automatic

	column Checkout_Visits
		dataType: int64
		formatString: 0
		lineageTag: 085f3eef-5434-45f4-bc25-2a91cfb5d18c
		summarizeBy: sum
		sourceColumn: Checkout_Visits

		annotation SummarizationSetBy = Automatic

	column Pending_Visits
		dataType: int64
		formatString: 0
		lineageTag: 2db19c33-2a2a-491b-a32b-a57218fc86a8
		summarizeBy: sum
		sourceColumn: Pending_Visits

		annotation SummarizationSetBy = Automatic

	column Cancel_Visits
		dataType: int64
		formatString: 0
		lineageTag: 18b7450b-84c2-4314-9b63-b28f78b0b9b8
		summarizeBy: sum
		sourceColumn: Cancel_Visits

		annotation SummarizationSetBy = Automatic

	column Waiting_List_Visits
		dataType: int64
		formatString: 0
		lineageTag: 0a73ec31-b0d5-4e5c-8e00-07bda08f6829
		summarizeBy: sum
		sourceColumn: Waiting_List_Visits

		annotation SummarizationSetBy = Automatic

	column Confrim
		dataType: int64
		formatString: 0
		lineageTag: 3ee77c7c-457c-47ce-bf63-f7ecd99bf4b5
		summarizeBy: sum
		sourceColumn: Confrim

		annotation SummarizationSetBy = Automatic

	column No_Show
		dataType: int64
		formatString: 0
		lineageTag: 3f73aa89-ba45-4a19-81e6-dc5b378abb22
		summarizeBy: sum
		sourceColumn: No_Show

		annotation SummarizationSetBy = Automatic

	column Waiting_Visits
		dataType: int64
		formatString: 0
		lineageTag: 1eceb55f-9a04-4077-a0de-be40cf87df21
		summarizeBy: sum
		sourceColumn: Waiting_Visits

		annotation SummarizationSetBy = Automatic

	column Force_Close_Visits
		dataType: int64
		formatString: 0
		lineageTag: 3ccb78d8-d7da-4293-9736-03a2afb6f853
		summarizeBy: sum
		sourceColumn: Force_Close_Visits

		annotation SummarizationSetBy = Automatic

	column Pre_Check_In_Visits
		dataType: int64
		formatString: 0
		lineageTag: b032dbf7-162f-49e7-96da-7ecacbf7ce38
		summarizeBy: sum
		sourceColumn: Pre_Check_In_Visits

		annotation SummarizationSetBy = Automatic

	column Completed_Total_Comb
		dataType: int64
		formatString: 0
		lineageTag: b8d4278d-dc19-4dd2-82d8-04e282517329
		summarizeBy: sum
		sourceColumn: Completed_Total_Comb

		annotation SummarizationSetBy = Automatic

	column CompHours
		dataType: double
		lineageTag: 7f92ba44-5caa-4398-9fd9-56004e54d01c
		summarizeBy: sum
		sourceColumn: CompHours

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SchdHours
		dataType: double
		lineageTag: 04879efc-0914-4fe7-9613-f3721e8008f3
		summarizeBy: sum
		sourceColumn: SchdHours

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TotHours
		dataType: double
		lineageTag: 8cd33ddb-fdba-4aeb-9a59-cbfa87f28d7c
		summarizeBy: sum
		sourceColumn: TotHours

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition vwVisitTrendByResourceNew = m
		mode: import
		source =
				let
				    Source = Sql.Database("azr-cbh-use1-sql-server01.database.windows.net", "CollectiveBH"),
				    dbo_vwVisitTrendByResourceNew = Source{[Schema="dbo",Item="vwVisitTrendByResourceNew"]}[Data]
				in
				    dbo_vwVisitTrendByResourceNew

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

