table vwVisitStatus
	lineageTag: 106534a0-938e-4c77-838f-a955f4587cbc

	column VisitStatusID
		dataType: int64
		formatString: 0
		lineageTag: 662629b3-4c5c-4a19-9dce-08d489e435e7
		summarizeBy: none
		sourceColumn: VisitStatusID

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: c2eb7d9f-5e93-45a1-865c-3417b2022196
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	partition vwVisitStatus-af895055-cbfe-47fe-9530-175030509b7c = m
		mode: import
		queryGroup: DIM
		source =
				let
				    Source = Sql.Database(ServerName, DBName),
				    dbo_vwVisitStatus = Source{[Schema="dbo",Item="vwVisitStatus"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(dbo_vwVisitStatus,{{"VisitStatusID", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Exception

