table 'z_RefreshDate (UTC)'
	lineageTag: 65dbdb71-3ccb-408c-a2c8-919c4f543f3b

	measure Measure = "Last Update: MST " & FORMAT(MIN('z_RefreshDate (UTC)'[Fecha.]),"General Date")
		lineageTag: 71cf5f79-1365-4148-840e-6c2a4b728257

	column 'Fecha.'
		dataType: dateTime
		formatString: General Date
		lineageTag: 734af451-fd29-4873-850e-db1e25b86e64
		summarizeBy: none
		sourceColumn: Fecha.

		variation Variation
			isDefault
			relationship: 6b051e44-4520-4ec3-8d9e-157038b401e7
			defaultHierarchy: LocalDateTable_ac9c6940-2561-4df7-82b9-34ab72415cc1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition 'z_RefreshDate (UTC)' = m
		mode: import
		source =
				let
				    Origen = DateTimeZone.SwitchZone( DateTimeZone.UtcNow(),  -7,0),
				    #"Convertida en tabla" = #table(1, {{Origen}}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Convertida en tabla",{{"Column1", "Fecha."}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Columnas con nombre cambiado",{{"Fecha.", type datetimezone}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Exception

