table cfgRevenueVisits
	lineageTag: c6fd2459-d139-42c0-abd3-7acc38977788

	column 'Type Provider ID'
		dataType: int64
		formatString: 0
		lineageTag: 69e13f45-6a0c-4dd4-b93c-d83ac2c1d2df
		summarizeBy: count
		sourceColumn: Type Provider ID

		annotation SummarizationSetBy = Automatic

	column 'Type Provider'
		dataType: string
		lineageTag: cc2421b0-56a6-4a78-997f-5104221e8a63
		summarizeBy: none
		sourceColumn: Type Provider

		annotation SummarizationSetBy = Automatic

	column 'Existent Revenue Visit'
		dataType: int64
		formatString: 0
		lineageTag: 514f36b3-cc73-4ac1-ba9e-21de45a26ef7
		summarizeBy: none
		sourceColumn: Existent Revenue Visit

		annotation SummarizationSetBy = User

	column 'New Revenue Visit'
		dataType: int64
		formatString: 0
		lineageTag: 9cd52dab-c65d-4c65-866b-83b03530c5f1
		summarizeBy: none
		sourceColumn: New Revenue Visit

		annotation SummarizationSetBy = User

	column 'Revenue No Show'
		dataType: int64
		formatString: 0
		lineageTag: ae578f59-6359-4202-b7cc-de73449b74a4
		summarizeBy: none
		sourceColumn: Revenue No Show

		annotation SummarizationSetBy = User

	column 'Revenue Cancel'
		dataType: int64
		formatString: 0
		lineageTag: 13305967-27e7-4b11-82c9-6272e87f2ef2
		summarizeBy: none
		sourceColumn: Revenue Cancel

		annotation SummarizationSetBy = User

	column Market
		dataType: string
		lineageTag: 52a3000e-04c2-40ab-9019-5e254eb9fb39
		summarizeBy: none
		sourceColumn: Market

		annotation SummarizationSetBy = Automatic

	column FromDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: bd72f6df-958a-41ae-b7d5-599fb7440760
		summarizeBy: none
		sourceColumn: FromDate

		variation Variation
			isDefault
			relationship: bb45b540-f9aa-49c7-94d6-a6a44ec9b7fa
			defaultHierarchy: LocalDateTable_75607ea8-abcb-4c89-9cc9-85cc1d33e64a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ThruDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 46eb5ebb-3441-49a6-9f9c-3a2f8bd99b64
		summarizeBy: none
		sourceColumn: ThruDate

		variation Variation
			isDefault
			relationship: 830f0e27-658a-4a80-832c-e769ad93f03b
			defaultHierarchy: LocalDateTable_e25997e3-a06d-4e55-9dee-6e8cd7e7c438.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Columna =
			
			IF(
			    DATEVALUE("12/31/2023") > cfgRevenueVisits[FromDate] && DATEVALUE("12/31/2023") <= cfgRevenueVisits[ThruDate] , 1, 0 )
		formatString: 0
		lineageTag: 10a7944c-67ce-4e2e-93f9-576bb3aaa4e2
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition cfgRevenueVisits-39ac3772-f242-4929-9a4f-de4ccb192eda = m
		mode: import
		queryGroup: CFGs
		source =
				let
				    Source = Sql.Database(ServerName, DBName),
				    dbo_cfgRevenueVisits = Source{[Schema="dbo",Item="cfgRevenueVisits"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(dbo_cfgRevenueVisits,{{"Type Provider ID", Int64.Type}, {"Type Provider", type text}, {"Existent Revenue Visit", Int64.Type}, {"New Revenue Visit", Int64.Type}, {"Revenue No Show", Int64.Type}, {"Revenue Cancel", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Exception

