table EmrSfMatch
	lineageTag: 99393af2-7067-48b1-b1f1-a9c48bb3fd9b

	column emr_patientid
		dataType: int64
		formatString: 0
		lineageTag: 4c183528-510a-4149-b54d-0172b33aa695
		summarizeBy: sum
		sourceColumn: emr_patientid

		annotation SummarizationSetBy = Automatic

	column emr_mrnNumber
		dataType: string
		lineageTag: ffa98882-3c06-4f9e-9008-13b18a59d05f
		summarizeBy: none
		sourceColumn: emr_mrnNumber

		annotation SummarizationSetBy = Automatic

	column emr_PlanNAme
		dataType: string
		lineageTag: b8cab8f3-ba50-4380-8c1c-5391eb20dc96
		summarizeBy: none
		sourceColumn: emr_PlanNAme

		annotation SummarizationSetBy = Automatic

	column emr_CreatedBy
		dataType: string
		lineageTag: fab19017-5b60-4233-9e73-9e64af3cb13e
		summarizeBy: none
		sourceColumn: emr_CreatedBy

		annotation SummarizationSetBy = Automatic

	column emr_CreatedOn
		dataType: dateTime
		formatString: Short Date
		lineageTag: 3ab48c16-7594-46dd-a232-19bf3366baf7
		summarizeBy: none
		sourceColumn: emr_CreatedOn

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column emr_ModifiedBy
		dataType: string
		lineageTag: cf55ea7c-f7e2-4c21-aaa4-adf12b69bfc0
		summarizeBy: none
		sourceColumn: emr_ModifiedBy

		annotation SummarizationSetBy = Automatic

	column emr_ModifiedOn
		dataType: dateTime
		formatString: Short Date
		lineageTag: f0475b93-2e67-46d2-bfe1-7076518d908b
		summarizeBy: none
		sourceColumn: emr_ModifiedOn

		variation Variation
			isDefault
			relationship: 25a75f19-0a48-471a-8953-ba950ff79c6b
			defaultHierarchy: LocalDateTable_1d431358-b6d5-4733-ad0a-4848b5c2f352.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column sf_patientid
		dataType: int64
		formatString: 0
		lineageTag: 774a8885-0fc8-4790-a266-67a0aa4478ef
		summarizeBy: sum
		sourceColumn: sf_patientid

		annotation SummarizationSetBy = Automatic

	column sf_Insurance
		dataType: string
		lineageTag: e05d312f-75b8-4e90-9cc6-93247f87989d
		summarizeBy: none
		sourceColumn: sf_Insurance

		annotation SummarizationSetBy = Automatic

	column sf_InsGroup
		dataType: string
		lineageTag: 54407f6a-186f-4d4c-bf79-1973fade2cec
		summarizeBy: none
		sourceColumn: sf_InsGroup

		annotation SummarizationSetBy = Automatic

	column sf_InsPolicy
		dataType: string
		lineageTag: fc805823-b49c-4d4d-84cc-4ec318eac8a9
		summarizeBy: none
		sourceColumn: sf_InsPolicy

		annotation SummarizationSetBy = Automatic

	column sf_LeadSource
		dataType: string
		lineageTag: d3e6309e-cc98-4138-8289-933632741881
		summarizeBy: none
		sourceColumn: sf_LeadSource

		annotation SummarizationSetBy = Automatic

	column sf_CreatedOn
		dataType: dateTime
		formatString: Short Date
		lineageTag: a7eb01dc-671a-4e40-90e2-cd16ffb4a796
		summarizeBy: none
		sourceColumn: sf_CreatedOn

		variation Variation
			isDefault
			relationship: 571e4d4c-e7bd-4365-a9e5-142874d42624
			defaultHierarchy: LocalDateTable_150ae7cb-7029-4538-b8d3-164c735d5f03.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column sf_CreatedBy
		dataType: string
		lineageTag: ce85b557-80a0-4700-adbc-a450a8720487
		summarizeBy: none
		sourceColumn: sf_CreatedBy

		annotation SummarizationSetBy = Automatic

	column PlanNullFlag
		dataType: string
		lineageTag: e194e25b-de21-44fe-a0fa-7881c2a22127
		summarizeBy: none
		sourceColumn: PlanNullFlag

		annotation SummarizationSetBy = Automatic

	column CreatedByFlag
		dataType: string
		lineageTag: 156befa8-e63c-4db1-b084-9463cab7237e
		summarizeBy: none
		sourceColumn: CreatedByFlag

		annotation SummarizationSetBy = Automatic

	column PlanInsuranceFlag
		dataType: int64
		formatString: 0
		lineageTag: 7b076d11-a5d3-4358-8a0e-d4e1ca452305
		summarizeBy: sum
		sourceColumn: PlanInsuranceFlag

		annotation SummarizationSetBy = Automatic

	column Market
		dataType: string
		lineageTag: 4a9242b7-3ad1-4337-a232-1a862afd57d3
		summarizeBy: none
		sourceColumn: Market

		annotation SummarizationSetBy = Automatic

	column FacilityName
		dataType: string
		lineageTag: 0e7bf8fc-adf0-4ae1-936f-ab1d4d131e81
		summarizeBy: none
		sourceColumn: FacilityName

		annotation SummarizationSetBy = Automatic

	column IsEnable
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 2c72421c-7837-4855-89a6-5e3b9fe73437
		summarizeBy: none
		sourceColumn: IsEnable

		annotation SummarizationSetBy = Automatic

	column CardType
		dataType: string
		lineageTag: c454fb7a-e3df-41f1-b466-e21081123f62
		summarizeBy: none
		sourceColumn: CardType

		annotation SummarizationSetBy = Automatic

	column CC_On_File
		dataType: string
		lineageTag: 74f8f217-acf9-4675-8d69-c8a93656c75d
		summarizeBy: none
		sourceColumn: CC_On_File

		annotation SummarizationSetBy = Automatic

	column ConsentSignDate
		dataType: dateTime
		formatString: mm/dd/yyyy
		lineageTag: 9c20bdfc-9c36-47b7-810b-2d35c7a77872
		summarizeBy: none
		sourceColumn: ConsentSignDate

		variation Variation
			isDefault
			relationship: 6f719a4a-12dc-4556-ac2b-41f1cc97cd66
			defaultHierarchy: LocalDateTable_9450bbe6-a19b-4cd1-a936-21b821c0c915.'Date Hierarchy'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	partition EmrSfMatch = m
		mode: import
		queryGroup: FACT\DailyOps
		source = ```
				let
				    Source = EmrSfMatch_raw,
				    // Plan and Modified By are null 
				    #"Added Conditional Column" = Table.AddColumn(Source, "PlanNullFlag", each if [emr_PlanNAme] = null  then "Yes" else "No" ),
				    // Created By is not collectiveadmin or System_User
				    #"Added Conditional Column1" = Table.AddColumn(#"Added Conditional Column", "CreatedByFlag", each if [emr_CreatedBy] <> "collectiveadmin" and [emr_CreatedBy] <> "System_User" then "No" else "Yes"),
				    // Plan is not same as Insurance Flag
				    #"Added Conditional Column2" = Table.AddColumn(#"Added Conditional Column1", "PlanInsuranceFlag", each if [emr_PlanNAme] <> [sf_Insurance] then 1 else 0),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Conditional Column2",{{"PlanInsuranceFlag", Int64.Type}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type", {"emr_Facility"}, vwFacilitiesMaster, {"FacilityName"}, "vwFacilitiesMaster", JoinKind.LeftOuter),
				    #"Expanded vwFacilitiesMaster" = Table.ExpandTableColumn(#"Merged Queries", "vwFacilitiesMaster", {"Market", "FacilityName"}, {"Market", "FacilityName"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Expanded vwFacilitiesMaster",{"emr_Facility"}),
				    #"Extracted Text Before Delimiter" = Table.TransformColumns(#"Removed Columns", {{"sf_CreatedBy", each Text.BeforeDelimiter(_, "@"), type text}})
				in
				    #"Extracted Text Before Delimiter"
				```

	annotation PBI_ResultType = Exception

