table 'vwEncounterPayroll - PRV'
	lineageTag: ec20c45e-50ec-45f2-977d-0d4efcd034cd

	column EncounterID
		dataType: int64
		formatString: 0
		lineageTag: 354fbbe4-c659-4366-aee4-4ac888e7b2f1
		summarizeBy: count
		sourceColumn: EncounterID

		annotation SummarizationSetBy = Automatic

	column EncounterTypeID
		dataType: int64
		formatString: 0
		lineageTag: 61167ab2-8527-4e91-82ab-92ebc3a19b3c
		summarizeBy: count
		sourceColumn: EncounterTypeID

		annotation SummarizationSetBy = Automatic

	column MRNNumber
		dataType: string
		lineageTag: bcf1b488-35b5-4c87-ac00-cac62f3976cd
		summarizeBy: none
		sourceColumn: MRNNumber

		annotation SummarizationSetBy = Automatic

	column Market
		dataType: string
		lineageTag: 527d5dbc-ed3e-4e9a-98fa-ea1a0998c49b
		summarizeBy: none
		sourceColumn: Market

		annotation SummarizationSetBy = Automatic

	column FacilityId
		dataType: int64
		formatString: 0
		lineageTag: 4a0ac4c3-e977-47ae-b3cb-c2eef646370d
		summarizeBy: count
		sourceColumn: FacilityId

		annotation SummarizationSetBy = Automatic

	column FacilityName
		dataType: string
		lineageTag: d729bc9c-1af4-49fc-a287-575e5aa32991
		summarizeBy: none
		sourceColumn: FacilityName

		annotation SummarizationSetBy = Automatic

	column PatientID
		dataType: int64
		formatString: 0
		lineageTag: 70b9daa5-e19a-4943-96f4-097a3801f855
		summarizeBy: count
		sourceColumn: PatientID

		annotation SummarizationSetBy = Automatic

	column ResourceId
		dataType: int64
		formatString: 0
		lineageTag: 33666e31-de6f-442e-a64d-7ebb2f384bda
		summarizeBy: none
		sourceColumn: ResourceId

		annotation SummarizationSetBy = Automatic

	column Duration
		dataType: int64
		formatString: 0
		lineageTag: 9180e415-6947-4180-86ed-d59b9e57c104
		summarizeBy: sum
		sourceColumn: Duration

		annotation SummarizationSetBy = Automatic

	column VisitDate
		dataType: dateTime
		formatString: mm/dd/yyyy
		lineageTag: 926f8b2c-9604-4bdd-90be-501e023c43de
		summarizeBy: none
		sourceColumn: VisitDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column EncounterDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2e4aa252-5022-4885-ad84-9772df2b0397
		summarizeBy: none
		sourceColumn: EncounterDate

		variation Variation
			isDefault
			relationship: 1f6a0e03-39aa-475b-af5f-5abd2276fab5
			defaultHierarchy: LocalDateTable_096ab59f-6e75-43ba-a37a-271847a146bf.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column NoteClosedDateTime
		dataType: dateTime
		formatString: mm/dd/yyyy
		lineageTag: 0f738d0a-e5bb-437e-8ab2-3f1610d305bf
		summarizeBy: none
		sourceColumn: NoteClosedDateTime

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column PatientLastName
		dataType: string
		lineageTag: 5f36ccd5-29ad-4408-9d46-2556102a5b93
		summarizeBy: none
		sourceColumn: PatientLastName

		annotation SummarizationSetBy = Automatic

	column PatientFirstName
		dataType: string
		lineageTag: e128d773-4c7c-46ca-b409-866d505af8c3
		summarizeBy: none
		sourceColumn: PatientFirstName

		annotation SummarizationSetBy = Automatic

	column visitid
		dataType: int64
		formatString: 0
		lineageTag: fb9ed6e8-62ac-4a0d-a352-75eb8cf5ee16
		summarizeBy: sum
		sourceColumn: visitid

		annotation SummarizationSetBy = Automatic

	column VisitPeriod
		dataType: string
		lineageTag: 759984d2-98c1-4d27-a45c-d13d896f729a
		summarizeBy: none
		sourceColumn: VisitPeriod

		annotation SummarizationSetBy = Automatic

	column NCDPeriod
		dataType: string
		lineageTag: 1be5586c-d90a-47d0-97f4-e4d9f408db58
		summarizeBy: none
		sourceColumn: NCDPeriod

		annotation SummarizationSetBy = Automatic

	column NCDFlag
		dataType: string
		lineageTag: ea390a91-0553-4e69-a6da-9c8781d3d45b
		summarizeBy: none
		sourceColumn: NCDFlag

		annotation SummarizationSetBy = Automatic

	column VisitTypeGroup
		dataType: string
		lineageTag: 83027005-6320-46a7-b05a-cfbf7fbfea5a
		summarizeBy: none
		sourceColumn: VisitTypeGroup

		annotation SummarizationSetBy = Automatic

	column FlagClosed
		dataType: int64
		formatString: 0
		lineageTag: 7317b344-dbec-4130-9618-477fa3bd8399
		summarizeBy: sum
		sourceColumn: FlagClosed

		annotation SummarizationSetBy = Automatic

	column FlagHasEncounter
		dataType: int64
		formatString: 0
		lineageTag: e2d8cc09-69a5-4e32-b42f-a8970cc629d0
		summarizeBy: sum
		sourceColumn: FlagHasEncounter

		annotation SummarizationSetBy = Automatic

	column EncounterType
		dataType: string
		lineageTag: e6190f59-e398-46de-9b84-995842f6afde
		summarizeBy: none
		sourceColumn: EncounterType

		annotation SummarizationSetBy = Automatic

	column VisitStatus
		dataType: string
		lineageTag: 7bfc3c2b-6b27-4964-82c4-15b9269e2b8e
		summarizeBy: none
		sourceColumn: VisitStatus

		annotation SummarizationSetBy = Automatic

	column CPTCode
		dataType: string
		lineageTag: 734577c7-819a-4fe3-b984-745c8436274a
		summarizeBy: none
		sourceColumn: CPTCode

		annotation SummarizationSetBy = Automatic

	column VisitType
		dataType: string
		lineageTag: d413933f-a323-4be9-8cec-a558bc87fd06
		summarizeBy: none
		sourceColumn: VisitType

		annotation SummarizationSetBy = Automatic

	column Clinician
		dataType: string
		lineageTag: fbb38ad9-058f-4166-8347-77692f43f60b
		summarizeBy: none
		sourceColumn: Clinician

		annotation SummarizationSetBy = Automatic

	partition 'vwEncounterPayroll - PRV' = m
		mode: import
		queryGroup: FACT\Payroll
		source =
				let
				    Source = Sql.Database(ServerName, DBName),
				    PRV_vwEncounterPayroll = Source{[Schema="PRV",Item="vwEncounterPayroll"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(PRV_vwEncounterPayroll,{{"VisitPeriod", type text}, {"NCDPeriod", type text}}),
				    #"Merged Columns" = Table.CombineColumns(#"Changed Type",{"LastName", "FirstName"},Combiner.CombineTextByDelimiter(", ", QuoteStyle.None),"Clinician"),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Merged Columns",{{"VisitDate", type date}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type1", each [VisitDate] > #date(2023, 12, 18))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

