table vwLeadActivityElapsedTime
	lineageTag: 96a844b0-726c-4110-bfc3-4878c36f349d

	measure 'Leads_FA - New' = DISTINCTCOUNT( 'vwLeadActivityElapsedTime'[recordId])
		lineageTag: 6edcaf6e-11a9-4479-ba06-516bd2f37871

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Avg_day_of_duration = AVERAGE(vwLeadActivityElapsedTime[Duration_Days])
		lineageTag: 2809ddaf-44d3-4f3d-b961-574bee05eb75

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column recordId
		dataType: string
		lineageTag: 9cd87aba-5ff8-470a-a069-a48fb9c33351
		summarizeBy: none
		sourceColumn: recordId

		annotation SummarizationSetBy = Automatic

	column FullName
		dataType: string
		lineageTag: e0b08313-2dfa-4397-823a-624942db7607
		summarizeBy: none
		sourceColumn: FullName

		annotation SummarizationSetBy = Automatic

	column referralType
		dataType: string
		lineageTag: 4599a9b8-947f-4828-879a-c83a998a2a08
		summarizeBy: none
		sourceColumn: referralType

		annotation SummarizationSetBy = Automatic

	column LeadStatus
		dataType: string
		lineageTag: 930f138e-983e-474a-92d7-bac2d7a12132
		summarizeBy: none
		sourceColumn: LeadStatus

		annotation SummarizationSetBy = Automatic

	column Market
		dataType: string
		lineageTag: f2d9bb13-0599-445f-b5d7-9142dcc21777
		summarizeBy: none
		sourceColumn: Market

		annotation SummarizationSetBy = Automatic

	column LeadSource
		dataType: string
		lineageTag: 31d7fa03-08c5-463e-b997-1b397ed86a8f
		summarizeBy: none
		sourceColumn: LeadSource

		annotation SummarizationSetBy = Automatic

	column ParentOrg
		dataType: string
		lineageTag: 1c4055d3-bc80-4929-a060-1b3c5c5a3f66
		summarizeBy: none
		sourceColumn: ParentOrg

		annotation SummarizationSetBy = Automatic

	column Cohort
		dataType: string
		lineageTag: 64d075d2-cff9-40a6-bde4-f3f70bcccb10
		summarizeBy: none
		sourceColumn: Cohort

		annotation SummarizationSetBy = Automatic

	column MinLeadDatetime
		dataType: dateTime
		formatString: General Date
		lineageTag: 698804a6-a9ea-4a40-958c-a98916e708c3
		summarizeBy: none
		sourceColumn: MinLeadDatetime

		annotation SummarizationSetBy = Automatic

	column MinActivityDatetime
		dataType: dateTime
		formatString: General Date
		lineageTag: a75b0589-9184-4e0e-9910-a0cfcdcb1562
		summarizeBy: none
		sourceColumn: MinActivityDatetime

		annotation SummarizationSetBy = Automatic

	column Duration_Minutes
		dataType: int64
		formatString: 0
		lineageTag: 56a6866f-dc92-4232-ba9c-b531e2ae0397
		summarizeBy: sum
		sourceColumn: Duration_Minutes

		annotation SummarizationSetBy = Automatic

	column Duration_Hours
		dataType: double
		formatString: 0
		lineageTag: 7c1befb9-90b8-4053-a3b6-44fb81e60fb8
		summarizeBy: sum
		sourceColumn: Duration_Hours

		annotation SummarizationSetBy = Automatic

	column Duration_Days
		dataType: int64
		formatString: 0
		lineageTag: d0fb5005-6f91-491d-acec-5d92abf97ef0
		summarizeBy: sum
		sourceColumn: Duration_Days

		annotation SummarizationSetBy = Automatic

	column GroupDays
		dataType: string
		lineageTag: 99cac36b-e39e-4cdd-aac0-73bd47813069
		summarizeBy: none
		sourceColumn: GroupDays
		sortByColumn: GroupDaysSort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column GroupDaysSort
		dataType: int64
		formatString: 0
		lineageTag: 5b96eb83-29f8-48d6-a6f7-77453099760f
		summarizeBy: sum
		sourceColumn: GroupDaysSort

		annotation SummarizationSetBy = Automatic

	partition vwLeadActivityElapsedTime = m
		mode: import
		queryGroup: Settings
		source =
				let
				    Source = Sql.Database(ServerName, DBName),
				    SFO_vwLeadActivityElapsedTime = Source{[Schema="SFO",Item="vwLeadActivityElapsedTime"]}[Data],
				    #"Replaced Value" = Table.ReplaceValue(SFO_vwLeadActivityElapsedTime,"Zoc Doc","ZocDoc",Replacer.ReplaceText,{"referralType"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Word of Mouth / Friend","Word of Mouth",Replacer.ReplaceText,{"referralType"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","Physician / Clinician Referral","Physician / Clinician / Medical Facility",Replacer.ReplaceText,{"referralType"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","Insurance Provider Website","Insurance Provider",Replacer.ReplaceText,{"referralType"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","Other Medical Facility","Physician / Clinician / Medical Facility",Replacer.ReplaceText,{"referralType"}),
				    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","Needs Follow-Up","Needs Follow Up",Replacer.ReplaceText,{"LeadStatus"})
				in
				    #"Replaced Value5"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

