table vwPanelRetention
	lineageTag: 071f187e-406e-4a88-9538-83fce7395a38

	column ResourceId
		dataType: int64
		formatString: 0
		lineageTag: 40d6973c-cdb3-45af-bb51-f0a81651d605
		summarizeBy: none
		sourceColumn: ResourceId

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: 34120de9-afd8-4819-866d-30b7d4062170
		summarizeBy: none
		sourceColumn: LastName

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		lineageTag: 55bd9e88-2b06-4013-89f4-2fc962d3d618
		summarizeBy: none
		sourceColumn: FirstName

		annotation SummarizationSetBy = Automatic

	column RangeName
		dataType: string
		lineageTag: 0c8436b1-7738-42a0-b869-f367dea19af5
		summarizeBy: none
		sourceColumn: RangeName
		sortByColumn: Custom

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column TotalCount
		dataType: int64
		formatString: 0
		lineageTag: c8c9a693-8faa-4055-bd0c-2b103dac0958
		summarizeBy: sum
		sourceColumn: TotalCount

		annotation SummarizationSetBy = Automatic

	column ActiveCount
		dataType: int64
		formatString: 0
		lineageTag: 5c4ab174-7573-48d4-b38a-88abc3eaa9fb
		summarizeBy: sum
		sourceColumn: ActiveCount

		annotation SummarizationSetBy = Automatic

	column Custom
		dataType: int64
		formatString: 0
		lineageTag: 266e2561-a005-4541-9a4b-f2b85a138c7c
		summarizeBy: sum
		sourceColumn: Custom

		annotation SummarizationSetBy = Automatic

	partition vwPanelRetention = m
		mode: import
		queryGroup: FACT\Panel
		source = ```
				let
				    Source = Source,
				    #"Filtered Rows" = Table.SelectRows(Source, each Text.Contains([Name], "Panel") and Text.Contains([Name], "Combined")),
				    dbo_vwSumClinicianPanelRetention = #"Filtered Rows"{[Schema="dbo",Item="vwSumClinicianPanelRetentionCombined"]}[Data],
				    #"Added Conditional Column" = Table.AddColumn(dbo_vwSumClinicianPanelRetention, "Custom", each 
				        if [RangeName] = "10 + Visits" then 3 
				        else if [RangeName] = "2+ Visits" then 1
				        else if [RangeName] = "6+ Visits" then 2 
				        else null, 
				    Int64.Type)
				in
				    #"Added Conditional Column"
				```

	annotation PBI_ResultType = Exception

