table vwProviderSchedule
	lineageTag: d1dea4fb-94db-4316-a542-ab7e930d5cf5

	column ApptType
		dataType: string
		lineageTag: 25e90932-e14c-4c8d-96fd-49deb10527ab
		summarizeBy: none
		sourceColumn: ApptType

		annotation SummarizationSetBy = Automatic

	column ProviderScheduleDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 065936b9-caf6-4497-b8e3-991f23a8bef3
		summarizeBy: none
		sourceColumn: ProviderScheduleDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Duration
		dataType: int64
		formatString: 0
		lineageTag: fb77ca82-501b-4a97-8a5d-183628d5938d
		summarizeBy: sum
		sourceColumn: Duration

		annotation SummarizationSetBy = Automatic

	column ProviderScheduleComment
		dataType: string
		lineageTag: 8a5e75e1-1d4e-4851-a7eb-1fc6e7c434ca
		summarizeBy: none
		sourceColumn: ProviderScheduleComment

		annotation SummarizationSetBy = Automatic

	column ResourceId
		dataType: int64
		formatString: 0
		lineageTag: a5880274-387f-4083-a9e0-4963f7b6224e
		summarizeBy: none
		sourceColumn: ResourceId

		annotation SummarizationSetBy = Automatic

	column FacilityName
		dataType: string
		lineageTag: 17f01185-46f3-419f-b3a9-2d7da8b3eb00
		summarizeBy: none
		sourceColumn: FacilityName

		annotation SummarizationSetBy = Automatic

	column Market
		dataType: string
		lineageTag: c0cc1e67-e802-475d-a1f9-70c252951060
		summarizeBy: none
		sourceColumn: Market

		annotation SummarizationSetBy = Automatic

	column Start
		dataType: dateTime
		formatString: General Date
		lineageTag: 0ed1cac6-5384-4285-8e87-19eac024f145
		summarizeBy: none
		sourceColumn: Start

		variation Variation
			isDefault
			relationship: 7fee2ac5-0277-4e05-9afb-cb8de0761764
			defaultHierarchy: LocalDateTable_c0cd688f-ee4a-47f8-ac60-0d68d9390e33.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column End
		dataType: dateTime
		formatString: General Date
		lineageTag: 1fbe7352-6cb7-4c80-89d6-c4e9c5c8d42e
		summarizeBy: none
		sourceColumn: End

		variation Variation
			isDefault
			relationship: 4459e40d-49ee-4a15-a71c-60ee0fe13980
			defaultHierarchy: LocalDateTable_bd03886a-904f-415d-ba6b-afc56778763d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition vwProviderSchedule = m
		mode: import
		queryGroup: 'FACT\Provider Schedule'
		source =
				let
				    Source = vwProviderSchedule_raw,
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"StartTime", type time}, {"EndTime", type time}, {"ProviderScheduleDate", type date}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"ProviderScheduleID"}),
				    #"Inserted Merged Date and Time" = Table.AddColumn(#"Removed Columns", "Merged", each [ProviderScheduleDate] & [StartTime], type datetime),
				    #"Inserted Merged Date and Time1" = Table.AddColumn(#"Inserted Merged Date and Time", "Merged.1", each [ProviderScheduleDate] & [EndTime], type datetime),
				    #"Renamed Columns" = Table.RenameColumns(#"Inserted Merged Date and Time1",{{"Merged", "Start"}, {"Merged.1", "End"}}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Renamed Columns",{ "StartTime", "EndTime", "FirstName", "LastName"})
				in
				    #"Removed Columns1"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

