table vwCadence
	lineageTag: 621a282b-437e-4dda-a35a-3f473314d7c0

	column Market
		dataType: string
		lineageTag: 61022b24-1a4b-4ce4-953e-f29ce82d0d07
		summarizeBy: none
		sourceColumn: Market

		annotation SummarizationSetBy = Automatic

	column PreferredFacility
		dataType: string
		lineageTag: cec1707b-77bc-4f64-9d04-ff64e26ddab0
		summarizeBy: none
		sourceColumn: PreferredFacility

		annotation SummarizationSetBy = Automatic

	column PsychIntakeDate
		dataType: dateTime
		formatString: mm/dd/yyyy
		lineageTag: c51ce419-0676-4fd1-bdc1-b885734f0c5d
		summarizeBy: none
		sourceColumn: PsychIntakeDate

		variation Variation
			isDefault
			relationship: d86efff0-3afa-49e8-9004-33506ba382a0
			defaultHierarchy: LocalDateTable_85dfe2ab-b5cf-4da6-bf19-d20ae3f1c521.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column LastCompletedVisit
		dataType: dateTime
		formatString: mm/dd/yyyy
		lineageTag: 0b510031-edc8-4099-be54-779ad8142f8e
		summarizeBy: none
		sourceColumn: LastCompletedVisit

		variation Variation
			isDefault
			relationship: 30e2e011-7a64-4f50-bbff-ba59577dd840
			defaultHierarchy: LocalDateTable_ce7902e7-96c9-48bc-90d0-db6666b766b2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Weeks
		dataType: int64
		formatString: 0
		lineageTag: fa78ab98-fb6d-4cae-a5a7-8652fc129df3
		summarizeBy: sum
		sourceColumn: Weeks

		annotation SummarizationSetBy = Automatic

	column WeeksToToday
		dataType: int64
		formatString: 0
		lineageTag: 81f08504-6327-48f6-a02b-58ff262677b1
		summarizeBy: sum
		sourceColumn: WeeksToToday

		annotation SummarizationSetBy = Automatic

	column Visits
		dataType: int64
		formatString: 0
		lineageTag: 63a7faf7-7d66-480b-b643-80202fd1d6fc
		summarizeBy: sum
		sourceColumn: Visits

		annotation SummarizationSetBy = Automatic

	column PsychVisits
		dataType: int64
		formatString: 0
		lineageTag: a199dded-4e31-47e3-8e98-f2faf48cca0d
		summarizeBy: sum
		sourceColumn: PsychVisits

		annotation SummarizationSetBy = Automatic

	column CadenceVisit
		dataType: int64
		formatString: 0
		lineageTag: 6d9845bf-ab36-4c4c-8974-672e16d61d0d
		summarizeBy: sum
		sourceColumn: CadenceVisit

		annotation SummarizationSetBy = Automatic

	column Clinician
		dataType: string
		lineageTag: e8a04e78-d518-40a5-85ac-0a2cc5d8584a
		summarizeBy: none
		sourceColumn: Clinician

		annotation SummarizationSetBy = Automatic

	column PatientName
		dataType: string
		lineageTag: a223388f-48e3-4fdc-8ad6-e893c45ba984
		summarizeBy: none
		sourceColumn: PatientName

		annotation SummarizationSetBy = Automatic

	column CadenceCol
		dataType: double
		lineageTag: 1fa79964-2c32-496b-9220-8af69d4d4a5e
		summarizeBy: sum
		sourceColumn: CadenceCol

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ResourceId
		dataType: int64
		formatString: 0
		lineageTag: 3529cdfa-cab4-4f46-87d1-27d69047178c
		summarizeBy: none
		sourceColumn: ResourceId

		annotation SummarizationSetBy = Automatic

	column Cohort
		dataType: string
		lineageTag: 78a262aa-5a05-42fd-9c2c-273e405b0f9d
		summarizeBy: none
		sourceColumn: Cohort

		annotation SummarizationSetBy = Automatic

	partition vwCadence = m
		mode: import
		queryGroup: Settings
		source =
				let
				    Source = Sql.Database(ServerName, DBName),
				    dbo_vwCadence = Source{[Schema="dbo",Item="vwCadence"]}[Data],
				    #"Merged Columns" = Table.CombineColumns(dbo_vwCadence,{"LastName", "FirstName"},Combiner.CombineTextByDelimiter(", ", QuoteStyle.None),"Clinician"),
				    #"Merged Columns1" = Table.CombineColumns(#"Merged Columns",{"PatientLastName", "PatientFirstName"},Combiner.CombineTextByDelimiter(", ", QuoteStyle.None),"PatientName"),
				    #"Added Custom" = Table.AddColumn(#"Merged Columns1", "CadenceCol", each [WeeksToToday]/[CadenceVisit]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom",{{"CadenceCol", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

