table vwClaimIssueLog
	lineageTag: a3c7883e-4812-4a18-9244-48aedf237a0b

	measure isuedIdcount = COUNT(vwClaimIssueLog[IssueId])
		lineageTag: 69121b2f-05a5-486b-9696-bdab0f36351a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column IssueId
		dataType: int64
		formatString: 0
		lineageTag: 943fa4da-7868-474b-b0b6-62f15676cfef
		summarizeBy: count
		sourceColumn: IssueId
		sortByColumn: DurationGroupSort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column ChargeId
		dataType: int64
		formatString: 0
		lineageTag: 68db7d53-f9da-436d-9a76-6d3ba45a8a50
		summarizeBy: count
		sourceColumn: ChargeId

		annotation SummarizationSetBy = Automatic

	column FacilityName
		dataType: string
		lineageTag: 45bd29b0-30ec-4ac3-a2c1-a7796f51d109
		summarizeBy: none
		sourceColumn: FacilityName

		annotation SummarizationSetBy = Automatic

	column Market
		dataType: string
		lineageTag: 2ccee298-a148-4af4-bb28-722e6df91112
		summarizeBy: none
		sourceColumn: Market

		annotation SummarizationSetBy = Automatic

	column PatientName
		dataType: string
		lineageTag: da23de20-e654-4c91-ac95-c646f792dbf3
		summarizeBy: none
		sourceColumn: PatientName

		annotation SummarizationSetBy = Automatic

	column ClinicianName
		dataType: string
		lineageTag: 6eb9cbdc-172f-4ccb-8ef3-c72b5f37a2a7
		summarizeBy: none
		sourceColumn: ClinicianName

		annotation SummarizationSetBy = Automatic

	column BillProvName
		dataType: string
		lineageTag: 5167b35c-eae0-4fac-b766-e54e502f48c8
		summarizeBy: none
		sourceColumn: BillProvName

		annotation SummarizationSetBy = Automatic

	column VisitDate
		dataType: dateTime
		formatString: mm/dd/yyyy
		lineageTag: 53b0fe75-b148-4ce0-aedc-285890a0140a
		summarizeBy: none
		sourceColumn: VisitDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column PayerName
		dataType: string
		lineageTag: a71701a0-4faf-49d9-bfec-1cb7e885b412
		summarizeBy: none
		sourceColumn: PayerName

		annotation SummarizationSetBy = Automatic

	column IssueType
		dataType: string
		lineageTag: b2b9341e-cbb9-4b0d-a885-c08f8b08163c
		summarizeBy: none
		sourceColumn: IssueType

		annotation SummarizationSetBy = Automatic

	column LastAction
		dataType: string
		lineageTag: 9bd28fe2-c5bb-4286-ad8b-00b8cf5ea98e
		summarizeBy: none
		sourceColumn: LastAction

		annotation SummarizationSetBy = Automatic

	column Response
		dataType: string
		lineageTag: 847cf09d-520e-4f20-a66e-26ced3bb58d8
		summarizeBy: none
		sourceColumn: Response

		annotation SummarizationSetBy = Automatic

	column Comment
		dataType: string
		lineageTag: dfb159c5-d537-4987-b679-1cd0f029c566
		summarizeBy: none
		sourceColumn: Comment

		annotation SummarizationSetBy = Automatic

	column DurationGroup
		dataType: string
		lineageTag: a4df695a-087d-4114-b8f5-d1af754c72fe
		summarizeBy: none
		sourceColumn: DurationGroup
		sortByColumn: DurationGroupSort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column DurationGroupSort
		dataType: double
		lineageTag: dccdda3b-0f3d-4ca5-ae6a-5eb5e2427cbf
		summarizeBy: sum
		sourceColumn: DurationGroupSort

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition vwClaimIssueLog = m
		mode: import
		queryGroup: FACT\DailyOps
		source =
				let
				    Source = Sql.Database("azr-cbh-use1-sql-server01.database.windows.net", "CollectiveBH"),
				    dbo_vwClaimIssueLog = Source{[Schema="dbo",Item="vwClaimIssueLog"]}[Data],
				    #"Added Conditional Column" = Table.AddColumn(dbo_vwClaimIssueLog, "DurationGroupSort", each if [DurationGroup] = "0-14 Days" then 1 else if [DurationGroup] = "15-28 Days" then 2 else if [DurationGroup] = "29-90 Days" then 5 else if [DurationGroup] = "91-180 Days" then 6 else if [DurationGroup] = "180+ Days" then 7 else 8),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Conditional Column",{{"DurationGroupSort", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

