table vwOnLineScheduleOpenSlots
	lineageTag: 0bc8a2a2-cacb-4569-afc4-1a58bb5bd4c6

	column ResourceID
		dataType: int64
		formatString: 0
		lineageTag: ae8adc99-f2c1-4f72-b0c9-67e074016bb2
		summarizeBy: none
		sourceColumn: ResourceID

		annotation SummarizationSetBy = Automatic

	column VisitDate
		dataType: string
		lineageTag: 8ddda2fb-705c-4091-b248-b2732a85cc91
		summarizeBy: none
		sourceColumn: VisitDate

		annotation SummarizationSetBy = Automatic

	column market
		dataType: string
		lineageTag: fcea6237-152f-4132-9532-4ca2ee9bbe4a
		summarizeBy: none
		sourceColumn: market

		annotation SummarizationSetBy = Automatic

	column FacilityID
		dataType: int64
		formatString: 0
		lineageTag: 00ba1a04-3b9b-4ce6-a3d9-5677abe1ae02
		summarizeBy: count
		sourceColumn: FacilityID

		annotation SummarizationSetBy = Automatic

	column facilityname
		dataType: string
		lineageTag: aaa7b535-cdc7-4cdc-9660-9b292199e272
		summarizeBy: none
		sourceColumn: facilityname

		annotation SummarizationSetBy = Automatic

	column SlotStartTime
		dataType: dateTime
		formatString: Long Time
		lineageTag: 7cb485ae-5cd0-43f0-9198-9f616209dfc1
		summarizeBy: none
		sourceColumn: SlotStartTime

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column SlotEndTime
		dataType: dateTime
		formatString: Long Time
		lineageTag: ce490522-feab-4c69-b44a-197f1dd2f9de
		summarizeBy: none
		sourceColumn: SlotEndTime

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column FullName
		dataType: string
		lineageTag: 0df99516-dfe5-4ad9-b757-e229582c28e0
		summarizeBy: none
		sourceColumn: FullName

		annotation SummarizationSetBy = Automatic

	column StartDateTime
		dataType: dateTime
		formatString: General Date
		lineageTag: 266c6bea-33d3-472a-ba13-e322364491ad
		summarizeBy: none
		sourceColumn: StartDateTime

		variation Variation
			isDefault
			relationship: c7fa6a8d-7a7e-414d-b4fb-fc5341a7a1d1
			defaultHierarchy: LocalDateTable_4664b199-0aa4-45eb-a89a-7ae40099ed92.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column EndDateTime
		dataType: dateTime
		formatString: General Date
		lineageTag: dffb6903-365c-4bae-8878-1d6c95574759
		summarizeBy: none
		sourceColumn: EndDateTime

		variation Variation
			isDefault
			relationship: d2bb34ce-3c81-462f-980b-54e82e38af7a
			defaultHierarchy: LocalDateTable_b50bdb6d-2c20-4e20-914b-136c13b09e2e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: b0a89b9b-cde2-4133-adbc-b582a4467947
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column FacilityLocation
		dataType: string
		lineageTag: c52ef921-eb5f-439c-8302-bcd56cfdcce0
		summarizeBy: none
		sourceColumn: FacilityLocation

		annotation SummarizationSetBy = Automatic

	column DateNumber = ```
			
			VAR YearPart = YEAR(vwOnLineScheduleOpenSlots[VisitDate])
			VAR MonthPart = FORMAT(MONTH(vwOnLineScheduleOpenSlots[VisitDate]), "00")
			VAR DayPart = FORMAT(DAY(vwOnLineScheduleOpenSlots[VisitDate]), "00") 
			
			RETURN YearPart * 10000 + MonthPart * 100 + DayPart
			```
		lineageTag: 21294f9f-b37a-4d46-965a-1ec89a20d454
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition vwOnLineScheduleOpenSlots = m
		mode: import
		queryGroup: 'FACT\Provider Schedule'
		source =
				let
				    Source = Sql.Database("azr-cbh-use1-sql-server01.database.windows.net", "CollectiveBH", [Query="SELECT ResourceID  #(lf)      ,VisitDate#(lf)      ,market#(lf)      ,FacilityID#(lf)      ,facilityname#(lf)      ,SlotStartTime#(lf)      ,SlotEndTime#(lf)      ,Location#(lf)      ,facilityname + ', ' + Location AS FacilityLocation#(lf), firstname + ', ' + lastname as FullName#(lf)FROM vwOnLineScheduleOpenSlotsCombined"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"VisitDate", type date}}),
				    #"Inserted Merged Column" = Table.AddColumn(#"Changed Type", "StartDateTime", each Text.Combine({Text.From([VisitDate], "en-US"), Text.From([SlotStartTime], "en-US")}, " "), type text),
				    #"Inserted Merged Column1" = Table.AddColumn(#"Inserted Merged Column", "EndDateTime", each Text.Combine({Text.From([VisitDate], "en-US"), Text.From([SlotEndTime], "en-US")}, " "), type text),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Inserted Merged Column1",{{"StartDateTime", type datetime}, {"EndDateTime", type datetime}, {"VisitDate", type text}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

